const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'data', 'internet-software.json');

function createEntry(id, root, phonetic, pos, meaning, phrases, mnemonic, words) {
  return {
    id,
    root,
    phonetic,
    partOfSpeech: pos,
    meaning,
    frequency: id,
    category: "互联网和软件",
    words: words.map(w => ({
      word: w.word,
      phonetic: w.phonetic,
      partOfSpeech: w.pos,
      meaning: w.meaning,
      memoryTip: w.tip,
      root,
      rootPhonetic: phonetic,
      rootMeaning: meaning,
      rootPhrases: phrases,
      wordPhrases: w.phrases || phrases.slice(0, 2)
    })),
    phrases,
    mnemonic
  };
}

// 541-600: 测试与质量保证
const allRoots = [
  // 测试框架 (541-560)
  { id: 541, root: "jest", phonetic: "/dʒest/", pos: "名词", meaning: "Jest测试框架", phrases: ["jest test Jest测试", "jest mock Jest模拟", "jest snapshot Jest快照", "jest coverage Jest覆盖率"], mnemonic: "Jest是Facebook的JavaScript测试框架", words: [{ word: "jest", phonetic: "/dʒest/", pos: "n.", meaning: "Jest", tip: "玩笑，测试框架" }, { word: "jest-test", phonetic: "/dʒest test/", pos: "n.", meaning: "Jest测试", tip: "jest + test" }, { word: "jest-mock", phonetic: "/dʒest mɒk/", pos: "n.", meaning: "Jest模拟", tip: "jest + mock" }, { word: "jest-config", phonetic: "/dʒest kənˈfɪɡ/", pos: "n.", meaning: "Jest配置", tip: "jest + config" }] },
  { id: 542, root: "mocha", phonetic: "/ˈmoʊkə/", pos: "名词", meaning: "Mocha测试框架", phrases: ["mocha test Mocha测试", "mocha runner Mocha运行器", "mocha chai Mocha+Chai", "mocha describe Mocha describe"], mnemonic: "Mocha是灵活的JavaScript测试框架", words: [{ word: "mocha", phonetic: "/ˈmoʊkə/", pos: "n.", meaning: "Mocha", tip: "摩卡，测试框架" }, { word: "mocha-test", phonetic: "/ˈmoʊkə test/", pos: "n.", meaning: "Mocha测试", tip: "mocha + test" }, { word: "mochajs", phonetic: "/ˈmoʊkədʒeɪɛs/", pos: "n.", meaning: "Mocha.js", tip: "mocha + js" }, { word: "mocha-runner", phonetic: "/ˈmoʊkə ˈrʌnər/", pos: "n.", meaning: "Mocha运行器", tip: "mocha + runner" }] },
  { id: 543, root: "jasmine", phonetic: "/ˈdʒæzmɪn/", pos: "名词", meaning: "Jasmine测试框架", phrases: ["jasmine test Jasmine测试", "jasmine spec Jasmine规格", "jasmine bdd BDD测试", "jasmine karma Karma+Jasmine"], mnemonic: "Jasmine是行为驱动开发测试框架", words: [{ word: "jasmine", phonetic: "/ˈdʒæzmɪn/", pos: "n.", meaning: "Jasmine", tip: "茉莉，测试框架" }, { word: "jasmine-test", phonetic: "/ˈdʒæzmɪn test/", pos: "n.", meaning: "Jasmine测试", tip: "jasmine + test" }, { word: "jasmine-bdd", phonetic: "/ˈdʒæzmɪn biːdiːdiː/", pos: "n.", meaning: "Jasmine BDD", tip: "jasmine + bdd" }, { word: "jasmine-core", phonetic: "/ˈdʒæzmɪn kɔːr/", pos: "n.", meaning: "Jasmine核心", tip: "jasmine + core" }] },
  { id: 544, root: "cypress", phonetic: "/ˈsaɪprəs/", pos: "名词", meaning: "Cypress端到端测试", phrases: ["cypress e2e Cypress端到端", "cypress test Cypress测试", "cypress runner Cypress运行器", "cypress dashboard Cypress仪表板"], mnemonic: "Cypress是现代化的前端端到端测试工具", words: [{ word: "cypress", phonetic: "/ˈsaɪprəs/", pos: "n.", meaning: "Cypress", tip: "柏树，E2E测试框架" }, { word: "cypress-io", phonetic: "/ˈsaɪprəs aɪoʊ/", pos: "n.", meaning: "Cypress.io", tip: "cypress + io" }, { word: "cypress-test", phonetic: "/ˈsaɪprəs test/", pos: "n.", meaning: "Cypress测试", tip: "cypress + test" }, { word: "cypress-e2e", phonetic: "/ˈsaɪprəs iːtuːiː/", pos: "n.", meaning: "Cypress E2E", tip: "cypress + e2e" }] },
  { id: 545, root: "playwright", phonetic: "/ˈpleɪraɪt/", pos: "名词", meaning: "Playwright测试工具", phrases: ["playwright test Playwright测试", "playwright browser Playwright浏览器", "playwright codegen 代码生成", "playwright trace Playwright追踪"], mnemonic: "Playwright是微软的现代Web测试框架", words: [{ word: "playwright", phonetic: "/ˈpleɪraɪt/", pos: "n.", meaning: "Playwright", tip: "剧作家，测试框架" }, { word: "playwright-test", phonetic: "/ˈpleɪraɪt test/", pos: "n.", meaning: "Playwright测试", tip: "playwright + test" }, { word: "playwright-core", phonetic: "/ˈpleɪraɪt kɔːr/", pos: "n.", meaning: "Playwright核心", tip: "playwright + core" }, { word: "playwright-chromium", phonetic: "/ˈpleɪraɪt ˈkroʊmiəm/", pos: "n.", meaning: "Playwright Chromium", tip: "playwright + chromium" }] },
  { id: 546, root: "selenium", phonetic: "/səˈliːniəm/", pos: "名词", meaning: "Selenium测试工具", phrases: ["selenium webdriver Selenium驱动", "selenium grid Selenium网格", "selenium ide Selenium IDE", "selenium test Selenium测试"], mnemonic: "Selenium是经典的浏览器自动化测试工具", words: [{ word: "selenium", phonetic: "/səˈliːniəm/", pos: "n.", meaning: "Selenium", tip: "硒，自动化测试" }, { word: "selenium-webdriver", phonetic: "/səˈliːniəm ˈwɛbdraɪvər/", pos: "n.", meaning: "Selenium WebDriver", tip: "selenium + webdriver" }, { word: "selenium-grid", phonetic: "/səˈliːniəm ɡrɪd/", pos: "n.", meaning: "Selenium Grid", tip: "selenium + grid" }, { word: "selenium-ide", phonetic: "/səˈliːniəm aɪdiːiː/", pos: "n.", meaning: "Selenium IDE", tip: "selenium + ide" }] },
  { id: 547, root: "puppeteer", phonetic: "/ˈpʌpɪtɪər/", pos: "名词", meaning: "Puppeteer无头浏览器", phrases: ["puppeteer browser Puppeteer浏览器", "puppeteer page Puppeteer页面", "puppeteer screenshot Puppeteer截图", "puppeteer pdf Puppeteer PDF"], mnemonic: "Puppeteer用代码控制Chrome浏览器像操纵木偶", words: [{ word: "puppeteer", phonetic: "/ˈpʌpɪtɪər/", pos: "n.", meaning: "Puppeteer", tip: "木偶师，无头浏览器" }, { word: "puppeteer-core", phonetic: "/ˈpʌpɪtɪər kɔːr/", pos: "n.", meaning: "Puppeteer核心", tip: "puppeteer + core" }, { word: "puppeteer-cluster", phonetic: "/ˈpʌpɪtɪər ˈklʌstər/", pos: "n.", meaning: "Puppeteer集群", tip: "puppeteer + cluster" }, { word: "headless-chrome", phonetic: "/ˈhɛdləs kroʊm/", pos: "n.", meaning: "无头Chrome", tip: "headless + chrome" }] },
  { id: 548, root: "testing-library", phonetic: "/ˈtɛstɪŋ ˈlaɪbrɛri/", pos: "名词", meaning: "Testing Library", phrases: ["testing-library react React测试库", "testing-library vue Vue测试库", "testing-library dom DOM测试库", "testing-library user 用户事件"], mnemonic: "Testing Library鼓励好的测试实践", words: [{ word: "testing-library", phonetic: "/ˈtɛstɪŋ ˈlaɪbrɛri/", pos: "n.", meaning: "Testing Library", tip: "testing + library" }, { word: "react-testing-library", phonetic: "/riːækt ˈtɛstɪŋ ˈlaɪbrɛri/", pos: "n.", meaning: "React Testing Library", tip: "react + testing-library" }, { word: "vue-testing-library", phonetic: "/vjuː ˈtɛstɪŋ ˈlaɪbrɛri/", pos: "n.", meaning: "Vue Testing Library", tip: "vue + testing-library" }, { word: "user-event", phonetic: "/ˈjuːzər ɪˈvɛnt/", pos: "n.", meaning: "User Event", tip: "user + event" }] },
  { id: 549, root: "enzyme", phonetic: "/ˈɛnzaɪm/", pos: "名词", meaning: "Enzyme React测试工具", phrases: ["enzyme shallow 浅渲染", "enzyme mount 挂载渲染", "enzyme react React测试", "enzyme test Enzyme测试"], mnemonic: "Enzyme是React组件测试工具", words: [{ word: "enzyme", phonetic: "/ˈɛnzaɪm/", pos: "n.", meaning: "Enzyme", tip: "酶，React测试工具" }, { word: "enzyme-shallow", phonetic: "/ˈɛnzaɪm ˈʃæloʊ/", pos: "n.", meaning: "Enzyme浅渲染", tip: "enzyme + shallow" }, { word: "enzyme-mount", phonetic: "/ˈɛnzaɪm maʊnt/", pos: "n.", meaning: "Enzyme挂载", tip: "enzyme + mount" }, { word: "enzyme-adapter", phonetic: "/ˈɛnzaɪm əˈdæptər/", pos: "n.", meaning: "Enzyme适配器", tip: "enzyme + adapter" }] },
  { id: 550, root: "karma", phonetic: "/ˈkɑːrmə/", pos: "名词", meaning: "Karma测试运行器", phrases: ["karma runner Karma运行器", "karma jasmine Karma+Jasmine", "karma config Karma配置", "karma browser Karma浏览器"], mnemonic: "Karma在真实浏览器中运行测试", words: [{ word: "karma", phonetic: "/ˈkɑːrmə/", pos: "n.", meaning: "Karma", tip: "因果，测试运行器" }, { word: "karma-runner", phonetic: "/ˈkɑːrmə ˈrʌnər/", pos: "n.", meaning: "Karma运行器", tip: "karma + runner" }, { word: "karma-jasmine", phonetic: "/ˈkɑːrmə ˈdʒæzmɪn/", pos: "n.", meaning: "Karma Jasmine", tip: "karma + jasmine" }, { word: "karma-config", phonetic: "/ˈkɑːrmə kənˈfɪɡ/", pos: "n.", meaning: "Karma配置", tip: "karma + config" }] },
  { id: 551, root: "ava", phonetic: "/ˈɑːvə/", pos: "名词", meaning: "AVA测试框架", phrases: ["ava test AVA测试", "ava runner AVA运行器", "ava concurrent AVA并发", "ava macro AVA宏"], mnemonic: "AVA是极简的JavaScript测试框架", words: [{ word: "ava", phonetic: "/ˈɑːvə/", pos: "n.", meaning: "AVA", tip: "AVA测试框架" }, { word: "ava-test", phonetic: "/ˈɑːvə test/", pos: "n.", meaning: "AVA测试", tip: "ava + test" }, { word: "ava-runner", phonetic: "/ˈɑːvə ˈrʌnər/", pos: "n.", meaning: "AVA运行器", tip: "ava + runner" }, { word: "ava-config", phonetic: "/ˈɑːvə kənˈfɪɡ/", pos: "n.", meaning: "AVA配置", tip: "ava + config" }] },
  { id: 552, root: "tape", phonetic: "/teɪp/", pos: "名词", meaning: "Tape测试框架", phrases: ["tape test Tape测试", "tape tap TAP格式", "tape output Tape输出", "tape stream Tape流"], mnemonic: "Tape是轻量级的TAP生成测试工具", words: [{ word: "tape", phonetic: "/teɪp/", pos: "n.", meaning: "Tape", tip: "磁带，测试框架" }, { word: "tape-test", phonetic: "/teɪp test/", pos: "n.", meaning: "Tape测试", tip: "tape + test" }, { word: "tap-format", phonetic: "/tæp ˈfɔːrmæt/", pos: "n.", meaning: "TAP格式", tip: "Test Anything Protocol" }, { word: "tape-assert", phonetic: "/teɪp əˈsɜːrt/", pos: "n.", meaning: "Tape断言", tip: "tape + assert" }] },
  { id: 553, root: "qunit", phonetic: "/kjuːˈnɪt/", pos: "名词", meaning: "QUnit测试框架", phrases: ["qunit test QUnit测试", "qunit jquery jQuery测试", "qunit assertion QUnit断言", "qunit module QUnit模块"], mnemonic: "QUnit是jQuery的单元测试框架", words: [{ word: "qunit", phonetic: "/kjuːˈnɪt/", pos: "n.", meaning: "QUnit", tip: "Query Unit，测试框架" }, { word: "qunit-test", phonetic: "/kjuːˈnɪt test/", pos: "n.", meaning: "QUnit测试", tip: "qunit + test" }, { word: "qunit-module", phonetic: "/kjuːˈnɪt ˈmɒdjuːl/", pos: "n.", meaning: "QUnit模块", tip: "qunit + module" }, { word: "qunit-assert", phonetic: "/kjuːˈnɪt əˈsɜːrt/", pos: "n.", meaning: "QUnit断言", tip: "qunit + assert" }] },
  { id: 554, root: "vitest", phonetic: "/ˈviːtest/", pos: "名词", meaning: "Vitest测试框架", phrases: ["vitest test Vitest测试", "vitest config Vitest配置", "vitest coverage Vitest覆盖率", "vitest mock Vitest模拟"], mnemonic: "Vitest是Vite的单元测试框架", words: [{ word: "vitest", phonetic: "/ˈviːtest/", pos: "n.", meaning: "Vitest", tip: "vite + test" }, { word: "vitest-config", phonetic: "/ˈviːtest kənˈfɪɡ/", pos: "n.", meaning: "Vitest配置", tip: "vitest + config" }, { word: "vitest-ui", phonetic: "/ˈviːtest juːaɪ/", pos: "n.", meaning: "Vitest UI", tip: "vitest + ui" }, { word: "vitest-coverage", phonetic: "/ˈviːtest ˈkʌvərɪdʒ/", pos: "n.", meaning: "Vitest覆盖率", tip: "vitest + coverage" }] },
  { id: 555, root: "storybook", phonetic: "/ˈstɔːribʊk/", pos: "名词", meaning: "Storybook组件开发工具", phrases: ["storybook story Storybook故事", "storybook component Storybook组件", "storybook addon Storybook插件", "storybook design 设计系统"], mnemonic: "Storybook独立开发和测试UI组件", words: [{ word: "storybook", phonetic: "/ˈstɔːribʊk/", pos: "n.", meaning: "Storybook", tip: "故事书，组件开发" }, { word: "story", phonetic: "/ˈstɔːri/", pos: "n.", meaning: "Story", tip: "故事，组件状态" }, { word: "storybook-addon", phonetic: "/ˈstɔːribʊk ˈædɒn/", pos: "n.", meaning: "Storybook插件", tip: "storybook + addon" }, { word: "storybook-design-system", phonetic: "/ˈstɔːribʊk dɪˈzaɪn ˈsɪstəm/", pos: "n.", meaning: "Storybook设计系统", tip: "storybook + design system" }] },
  { id: 556, root: "lighthouse", phonetic: "/ˈlaɪthaʊs/", pos: "名词", meaning: "Lighthouse性能分析工具", phrases: ["lighthouse audit Lighthouse审计", "lighthouse score Lighthouse分数", "lighthouse ci Lighthouse CI", "lighthouse report Lighthouse报告"], mnemonic: "Lighthouse像灯塔一样指引性能优化方向", words: [{ word: "lighthouse", phonetic: "/ˈlaɪthaʊs/", pos: "n.", meaning: "Lighthouse", tip: "灯塔，性能分析" }, { word: "lighthouse-ci", phonetic: "/ˈlaɪthaʊs siːaɪ/", pos: "n.", meaning: "Lighthouse CI", tip: "lighthouse + ci" }, { word: "lighthouse-score", phonetic: "/ˈlaɪthaʊs skɔːr/", pos: "n.", meaning: "Lighthouse分数", tip: "lighthouse + score" }, { word: "lighthouse-report", phonetic: "/ˈlaɪthaʊs rɪˈpɔːrt/", pos: "n.", meaning: "Lighthouse报告", tip: "lighthouse + report" }] },
  { id: 557, root: "webdriver", phonetic: "/ˈwɛbdraɪvər/", pos: "名词", meaning: "WebDriver浏览器驱动", phrases: ["webdriver selenium Selenium WebDriver", "webdriver io WebDriverIO", "webdriver protocol WebDriver协议", "webdriver automation WebDriver自动化"], mnemonic: "WebDriver是浏览器自动化的标准协议", words: [{ word: "webdriver", phonetic: "/ˈwɛbdraɪvər/", pos: "n.", meaning: "WebDriver", tip: "web + driver，浏览器驱动" }, { word: "webdriverio", phonetic: "/ˈwɛbdraɪvərioʊ/", pos: "n.", meaning: "WebDriverIO", tip: "webdriver + io" }, { word: "selenium-webdriver", phonetic: "/səˈliːniəm ˈwɛbdraɪvər/", pos: "n.", meaning: "Selenium WebDriver", tip: "selenium + webdriver" }, { word: "webdriver-protocol", phonetic: "/ˈwɛbdraɪvər ˈproʊtəkɒl/", pos: "n.", meaning: "WebDriver协议", tip: "webdriver + protocol" }] },
  { id: 558, root: "nightwatch", phonetic: "/ˈnaɪtwɒtʃ/", pos: "名词", meaning: "Nightwatch.js测试框架", phrases: ["nightwatch test Nightwatch测试", "nightwatch selenium Nightwatch Selenium", "nightwatch bdd Nightwatch BDD", "nightwatch page Nightwatch页面对象"], mnemonic: "Nightwatch是夜间值守的端到端测试框架", words: [{ word: "nightwatch", phonetic: "/ˈnaɪtwɒtʃ/", pos: "n.", meaning: "Nightwatch", tip: "守夜人，E2E测试" }, { word: "nightwatchjs", phonetic: "/ˈnaɪtwɒtʃdʒeɪɛs/", pos: "n.", meaning: "Nightwatch.js", tip: "nightwatch + js" }, { word: "nightwatch-test", phonetic: "/ˈnaɪtwɒtʃ test/", pos: "n.", meaning: "Nightwatch测试", tip: "nightwatch + test" }, { word: "nightwatch-config", phonetic: "/ˈnaɪtwɒtʃ kənˈfɪɡ/", pos: "n.", meaning: "Nightwatch配置", tip: "nightwatch + config" }] },
  { id: 559, root: "codecept", phonetic: "/koʊdˈsɛpt/", pos: "名词", meaning: "CodeceptJS测试框架", phrases: ["codeceptjs test CodeceptJS测试", "codeceptjs bdd BDD测试", "codeceptjs helper CodeceptJS助手", "codeceptjs actor CodeceptJS执行者"], mnemonic: "CodeceptJS采用BDD风格的行为驱动测试", words: [{ word: "codeceptjs", phonetic: "/koʊdˈsɛpt dʒeɪɛs/", pos: "n.", meaning: "CodeceptJS", tip: "code + concept + js" }, { word: "codecept", phonetic: "/koʊdˈsɛpt/", pos: "n.", meaning: "Codecept", tip: "code concept" }, { word: "codeceptjs-test", phonetic: "/koʊdˈsɛpt dʒeɪɛs test/", pos: "n.", meaning: "CodeceptJS测试", tip: "codeceptjs + test" }, { word: "codeceptjs-bdd", phonetic: "/koʊdˈsɛpt dʒeɪɛs biːdiːdiː/", pos: "n.", meaning: "CodeceptJS BDD", tip: "codeceptjs + bdd" }] },
  { id: 560, root: "mock", phonetic: "/mɒk/", pos: "动词/名词", meaning: "模拟", phrases: ["mock function 模拟函数", "mock api 模拟API", "mock server 模拟服务器", "mock data 模拟数据"], mnemonic: "Mock用假数据模拟真实场景", words: [{ word: "mock", phonetic: "/mɒk/", pos: "v./n.", meaning: "模拟", tip: "mock模拟" }, { word: "mocking", phonetic: "/ˈmɒkɪŋ/", pos: "n.", meaning: "模拟", tip: "mock + ing" }, { word: "mocked", phonetic: "/mɒkt/", pos: "adj.", meaning: "已模拟的", tip: "mock + ed" }, { word: "mock-server", phonetic: "/mɒk ˈsɜːrvər/", pos: "n.", meaning: "Mock服务器", tip: "mock + server" }] }
];

console.log(`Adding ${allRoots.length} new entries (541-560)`);

const newEntries = allRoots.map(r => createEntry(r.id, r.root, r.phonetic, r.pos, r.meaning, r.phrases, r.mnemonic, r.words));

const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
console.log(`Current entries: ${data.length}`);

const updatedData = [...data, ...newEntries];
console.log(`New total: ${updatedData.length}`);

fs.writeFileSync(filePath, JSON.stringify(updatedData, null, 2));
console.log('Batch 3 done!');
