const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'src', 'data', 'internet-software.json');

function createEntry(id, root, phonetic, pos, meaning, phrases, mnemonic, words) {
  return {
    id, root, phonetic, partOfSpeech: pos, meaning, frequency: id, category: "互联网和软件",
    words: words.map(w => ({ word: w.word, phonetic: w.phonetic, partOfSpeech: w.pos, meaning: w.meaning, memoryTip: w.tip, root, rootPhonetic: phonetic, rootMeaning: meaning, rootPhrases: phrases, wordPhrases: w.phrases || phrases.slice(0, 2) })),
    phrases, mnemonic
  };
}

const allRoots = [
  // 561-600: 后端与数据库
  { id: 561, root: "express", phonetic: "/ɪkˈspres/", pos: "名词", meaning: "Express框架", phrases: ["express server Express服务器", "express route Express路由", "express middleware Express中间件", "express app Express应用"], mnemonic: "Express是快速、极简的Node.js Web框架", words: [{ word: "express", phonetic: "/ɪkˈspres/", pos: "n.", meaning: "Express", tip: "表达，Node.js框架" }, { word: "expressjs", phonetic: "/ɪkˈspresdʒeɪɛs/", pos: "n.", meaning: "Express.js", tip: "express + js" }, { word: "express-router", phonetic: "/ɪkˈspres ˈruːtər/", pos: "n.", meaning: "Express路由", tip: "express + router" }, { word: "express-middleware", phonetic: "/ɪkˈspres ˈmɪdlwer/", pos: "n.", meaning: "Express中间件", tip: "express + middleware" }] },
  { id: 562, root: "koa", phonetic: "/ˈkoʊə/", pos: "名词", meaning: "Koa框架", phrases: ["koa server Koa服务器", "koa middleware Koa中间件", "koa context Koa上下文", "koa async Koa异步"], mnemonic: "Koa是Express原班人马打造的下一代框架", words: [{ word: "koa", phonetic: "/ˈkoʊə/", pos: "n.", meaning: "Koa", tip: "Koa，Node.js框架" }, { word: "koajs", phonetic: "/ˈkoʊədʒeɪɛs/", pos: "n.", meaning: "Koa.js", tip: "koa + js" }, { word: "koa-router", phonetic: "/ˈkoʊə ˈruːtər/", pos: "n.", meaning: "Koa路由", tip: "koa + router" }, { word: "koa-compose", phonetic: "/ˈkoʊə kəmˈpoʊz/", pos: "n.", meaning: "Koa组合", tip: "koa + compose" }] },
  { id: 563, root: "fastify", phonetic: "/ˈfæstɪfaɪ/", pos: "名词", meaning: "Fastify框架", phrases: ["fastify server Fastify服务器", "fastify route Fastify路由", "fastify plugin Fastify插件", "fastify benchmark Fastify基准"], mnemonic: "Fastify是极快的低开销Node.js框架", words: [{ word: "fastify", phonetic: "/ˈfæstɪfaɪ/", pos: "n.", meaning: "Fastify", tip: "fast快 + ify化，快速框架" }, { word: "fastifyjs", phonetic: "/ˈfæstɪfaɪdʒeɪɛs/", pos: "n.", meaning: "Fastify.js", tip: "fastify + js" }, { word: "fastify-plugin", phonetic: "/ˈfæstɪfaɪ ˈplʌɡɪn/", pos: "n.", meaning: "Fastify插件", tip: "fastify + plugin" }, { word: "fastify-schema", phonetic: "/ˈfæstɪfaɪ ˈskiːmə/", pos: "n.", meaning: "Fastify模式", tip: "fastify + schema" }] },
  { id: 564, root: "nestjs", phonetic: "/nɛst dʒeɪɛs/", pos: "名词", meaning: "NestJS框架", phrases: ["nestjs module NestJS模块", "nestjs controller NestJS控制器", "nestjs service NestJS服务", "nestjs decorator NestJS装饰器"], mnemonic: "NestJS是渐进式Node.js框架，支持TypeScript", words: [{ word: "nestjs", phonetic: "/nɛst dʒeɪɛs/", pos: "n.", meaning: "NestJS", tip: "nest巢 + js" }, { word: "nest", phonetic: "/nɛst/", pos: "n.", meaning: "Nest", tip: "巢穴，NestJS" }, { word: "nestjs-module", phonetic: "/nɛst dʒeɪɛs ˈmɒdjuːl/", pos: "n.", meaning: "NestJS模块", tip: "nestjs + module" }, { word: "nestjs-provider", phonetic: "/nɛst dʒeɪɛs prəˈvaɪdər/", pos: "n.", meaning: "NestJS提供者", tip: "nestjs + provider" }] },
  { id: 565, root: "hapi", phonetic: "/ˈhæpi/", pos: "名词", meaning: "Hapi框架", phrases: ["hapi server Hapi服务器", "hapi route Hapi路由", "hapi plugin Hapi插件", "hapi config Hapi配置"], mnemonic: "Hapi是配置驱动的Node.js框架", words: [{ word: "hapi", phonetic: "/ˈhæpi/", pos: "n.", meaning: "Hapi", tip: "happy的变体，Node.js框架" }, { word: "hapijs", phonetic: "/ˈhæpidʒeɪɛs/", pos: "n.", meaning: "Hapi.js", tip: "hapi + js" }, { word: "hapi-server", phonetic: "/ˈhæpi ˈsɜːrvər/", pos: "n.", meaning: "Hapi服务器", tip: "hapi + server" }, { word: "hapi-plugin", phonetic: "/ˈhæpi ˈplʌɡɪn/", pos: "n.", meaning: "Hapi插件", tip: "hapi + plugin" }] },
  { id: 566, root: "sails", phonetic: "/seɪlz/", pos: "名词", meaning: "Sails.js框架", phrases: ["sails model Sails模型", "sails controller Sails控制器", "sails waterline Waterline ORM", "sails blueprint Sails蓝图"], mnemonic: "Sails是MVC模式的实时Node.js框架", words: [{ word: "sails", phonetic: "/seɪlz/", pos: "n.", meaning: "Sails", tip: "帆，Node.js MVC框架" }, { word: "sailsjs", phonetic: "/seɪlzdʒeɪɛs/", pos: "n.", meaning: "Sails.js", tip: "sails + js" }, { word: "waterline", phonetic: "/ˈwɔːtərlaɪn/", pos: "n.", meaning: "Waterline", tip: "吃水线，Sails的ORM" }, { word: "sails-blueprint", phonetic: "/seɪlz ˈbluːprɪnt/", pos: "n.", meaning: "Sails蓝图", tip: "sails + blueprint" }] },
  { id: 567, root: "egg", phonetic: "/ɛɡ/", pos: "名词", meaning: "Egg.js框架", phrases: ["egg controller Egg控制器", "egg service Egg服务", "egg plugin Egg插件", "egg schedule Egg定时任务"], mnemonic: "Egg.js是阿里出品的Node.js企业级框架", words: [{ word: "egg", phonetic: "/ɛɡ/", pos: "n.", meaning: "Egg", tip: "蛋，Node.js框架" }, { word: "eggjs", phonetic: "/ɛɡdʒeɪɛs/", pos: "n.", meaning: "Egg.js", tip: "egg + js" }, { word: "egg-cluster", phonetic: "/ɛɡ ˈklʌstər/", pos: "n.", meaning: "Egg集群", tip: "egg + cluster" }, { word: "egg-scripts", phonetic: "/ɛɡ skrɪpts/", pos: "n.", meaning: "Egg脚本", tip: "egg + scripts" }] },
  { id: 568, root: "adonis", phonetic: "/əˈdɒnɪs/", pos: "名词", meaning: "AdonisJS框架", phrases: ["adonis auth Adonis认证", "adonis orm Adonis ORM", "adonis ace Adonis命令行", "adonis lucid Adonis Lucid"], mnemonic: "AdonisJS是优雅的Node.js Web框架", words: [{ word: "adonis", phonetic: "/əˈdɒnɪs/", pos: "n.", meaning: "Adonis", tip: "美少年，Node.js框架" }, { word: "adonisjs", phonetic: "/əˈdɒnɪsdʒeɪɛs/", pos: "n.", meaning: "AdonisJS", tip: "adonis + js" }, { word: "adonis-lucid", phonetic: "/əˈdɒnɪs ˈluːsɪd/", pos: "n.", meaning: "Adonis Lucid", tip: "adonis + lucid，ORM" }, { word: "adonis-ace", phonetic: "/əˈdɒnɪs eɪs/", pos: "n.", meaning: "Adonis Ace", tip: "adonis + ace，CLI" }] },
  { id: 569, root: "feathers", phonetic: "/ˈfeðərz/", pos: "名词", meaning: "FeathersJS框架", phrases: ["feathers service Feathers服务", "feathers hook Feathers钩子", "feathers real-time Feathers实时", "feathers socket Feathers Socket"], mnemonic: "FeathersJS是轻量级的实时API框架", words: [{ word: "feathers", phonetic: "/ˈfeðərz/", pos: "n.", meaning: "Feathers", tip: "羽毛，实时框架" }, { word: "feathersjs", phonetic: "/ˈfeðərzdʒeɪɛs/", pos: "n.", meaning: "FeathersJS", tip: "feathers + js" }, { word: "feathers-service", phonetic: "/ˈfeðərz ˈsɜːrvɪs/", pos: "n.", meaning: "Feathers服务", tip: "feathers + service" }, { word: "feathers-hook", phonetic: "/ˈfeðərz hʊk/", pos: "n.", meaning: "Feathers钩子", tip: "feathers + hook" }] },
  { id: 570, root: "loopback", phonetic: "/ˈluːpbæk/", pos: "名词", meaning: "LoopBack框架", phrases: ["loopback model LoopBack模型", "loopback api LoopBack API", "loopback explorer LoopBack探索器", "loopback datasource LoopBack数据源"], mnemonic: "LoopBack是创建API的Node.js框架", words: [{ word: "loopback", phonetic: "/ˈluːpbæk/", pos: "n.", meaning: "LoopBack", tip: "环回，API框架" }, { word: "loopback4", phonetic: "/ˈluːpbæk fɔːr/", pos: "n.", meaning: "LoopBack 4", tip: "loopback + 4" }, { word: "loopback-model", phonetic: "/ˈluːpbæk ˈmɒdl/", pos: "n.", meaning: "LoopBack模型", tip: "loopback + model" }, { word: "loopback-connector", phonetic: "/ˈluːpbæk kəˈnɛktər/", pos: "n.", meaning: "LoopBack连接器", tip: "loopback + connector" }] },
  { id: 571, root: "mysql", phonetic: "/maɪˈɛskjuːɛl/", pos: "名词", meaning: "MySQL数据库", phrases: ["mysql database MySQL数据库", "mysql query MySQL查询", "mysql table MySQL表", "mysql index MySQL索引"], mnemonic: "MySQL是最流行的开源关系型数据库", words: [{ word: "mysql", phonetic: "/maɪˈɛskjuːɛl/", pos: "n.", meaning: "MySQL", tip: "My + SQL，数据库" }, { word: "mariadb", phonetic: "/məriːɑːdiːbiː/", pos: "n.", meaning: "MariaDB", tip: "MySQL分支" }, { word: "mysql-client", phonetic: "/maɪˈɛskjuːɛl ˈklaɪənt/", pos: "n.", meaning: "MySQL客户端", tip: "mysql + client" }, { word: "mysql-server", phonetic: "/maɪˈɛskjuːɛl ˈsɜːrvər/", pos: "n.", meaning: "MySQL服务器", tip: "mysql + server" }] },
  { id: 572, root: "postgresql", phonetic: "/ˈpoʊstɡrɛs kjuːɛl/", pos: "名词", meaning: "PostgreSQL数据库", phrases: ["postgres database Postgres数据库", "postgresql query PostgreSQL查询", "postgres json Postgres JSON", "postgresql index PostgreSQL索引"], mnemonic: "PostgreSQL是功能强大的开源对象关系数据库", words: [{ word: "postgresql", phonetic: "/ˈpoʊstɡrɛs kjuːɛl/", pos: "n.", meaning: "PostgreSQL", tip: "Postgres + SQL，数据库" }, { word: "postgres", phonetic: "/ˈpoʊstɡrɛs/", pos: "n.", meaning: "Postgres", tip: "PostgreSQL简称" }, { word: "pgsql", phonetic: "/piːdʒiːˈɛskjuːɛl/", pos: "n.", meaning: "PGSQL", tip: "PostgreSQL简称" }, { word: "postgresql-server", phonetic: "/ˈpoʊstɡrɛs kjuːɛl ˈsɜːrvər/", pos: "n.", meaning: "PostgreSQL服务器", tip: "postgresql + server" }] },
  { id: 573, root: "mongodb", phonetic: "/ˈmɒŋɡoʊ diːbiː/", pos: "名词", meaning: "MongoDB数据库", phrases: ["mongodb collection MongoDB集合", "mongodb document MongoDB文档", "mongodb query MongoDB查询", "mongodb atlas MongoDB Atlas"], mnemonic: "MongoDB是最流行的文档型NoSQL数据库", words: [{ word: "mongodb", phonetic: "/ˈmɒŋɡoʊ diːbiː/", pos: "n.", meaning: "MongoDB", tip: "Mongo + DB，文档数据库" }, { word: "mongo", phonetic: "/ˈmɒŋɡoʊ/", pos: "n.", meaning: "Mongo", tip: "MongoDB简称" }, { word: "mongoose", phonetic: "/ˈmɒŋɡuːs/", pos: "n.", meaning: "Mongoose", tip: "MongoDB ODM" }, { word: "mongodb-compass", phonetic: "/ˈmɒŋɡoʊ diːbiː ˈkʌmpəs/", pos: "n.", meaning: "MongoDB Compass", tip: "mongodb + compass" }] },
  { id: 574, root: "redis", phonetic: "/ˈrɛdɪs/", pos: "名词", meaning: "Redis缓存数据库", phrases: ["redis cache Redis缓存", "redis key Redis键", "redis value Redis值", "redis pubsub Redis发布订阅"], mnemonic: "Redis是内存中的数据结构存储系统", words: [{ word: "redis", phonetic: "/ˈrɛdɪs/", pos: "n.", meaning: "Redis", tip: "Remote Dictionary Server，缓存" }, { word: "redis-cli", phonetic: "/ˈrɛdɪs siːɛlaɪ/", pos: "n.", meaning: "Redis CLI", tip: "redis + cli" }, { word: "redis-server", phonetic: "/ˈrɛdɪs ˈsɜːrvər/", pos: "n.", meaning: "Redis服务器", tip: "redis + server" }, { word: "redis-cluster", phonetic: "/ˈrɛdɪs ˈklʌstər/", pos: "n.", meaning: "Redis集群", tip: "redis + cluster" }] },
  { id: 575, root: "sqlite", phonetic: "/ˈɛskjuːɛlaɪt/", pos: "名词", meaning: "SQLite嵌入式数据库", phrases: ["sqlite database SQLite数据库", "sqlite query SQLite查询", "sqlite file SQLite文件", "sqlite memory SQLite内存"], mnemonic: "SQLite是嵌入式关系型数据库", words: [{ word: "sqlite", phonetic: "/ˈɛskjuːɛlaɪt/", pos: "n.", meaning: "SQLite", tip: "SQL + lite轻量，嵌入式数据库" }, { word: "sqlite3", phonetic: "/ˈɛskjuːɛlaɪt θriː/", pos: "n.", meaning: "SQLite3", tip: "sqlite + 3" }, { word: "sqlite-browser", phonetic: "/ˈɛskjuːɛlaɪt ˈbraʊzər/", pos: "n.", meaning: "SQLite浏览器", tip: "sqlite + browser" }, { word: "sqlite-file", phonetic: "/ˈɛskjuːɛlaɪt faɪl/", pos: "n.", meaning: "SQLite文件", tip: "sqlite + file" }] },
  { id: 576, root: "elasticsearch", phonetic: "/ɪˈlæstɪk sɜːrtʃ/", pos: "名词", meaning: "Elasticsearch搜索引擎", phrases: ["elasticsearch index ES索引", "elasticsearch query ES查询", "elasticsearch cluster ES集群", "elasticsearch mapping ES映射"], mnemonic: "Elasticsearch是分布式搜索和分析引擎", words: [{ word: "elasticsearch", phonetic: "/ɪˈlæstɪk sɜːrtʃ/", pos: "n.", meaning: "Elasticsearch", tip: "elastic弹性 + search搜索" }, { word: "elastic", phonetic: "/ɪˈlæstɪk/", pos: "n.", meaning: "Elastic", tip: "弹性的，Elastic Stack" }, { word: "elk", phonetic: "/ɛlk/", pos: "n.", meaning: "ELK", tip: "Elasticsearch Logstash Kibana" }, { word: "elasticsearch-query", phonetic: "/ɪˈlæstɪk sɜːrtʃ kwɪəri/", pos: "n.", meaning: "ES查询", tip: "elasticsearch + query" }] },
  { id: 577, root: "cassandra", phonetic: "/kəˈsændrə/", pos: "名词", meaning: "Cassandra分布式数据库", phrases: ["cassandra node Cassandra节点", "cassandra cluster Cassandra集群", "cassandra keyspace Cassandra键空间", "cassandra query Cassandra查询"], mnemonic: "Cassandra是高可用的分布式NoSQL数据库", words: [{ word: "cassandra", phonetic: "/kəˈsændrə/", pos: "n.", meaning: "Cassandra", tip: "卡珊德拉，分布式数据库" }, { word: "apache-cassandra", phonetic: "/əˈpætʃi kəˈsændrə/", pos: "n.", meaning: "Apache Cassandra", tip: "apache + cassandra" }, { word: "cql", phonetic: "/siːkjuːɛl/", pos: "n.", meaning: "CQL", tip: "Cassandra Query Language" }, { word: "cassandra-ring", phonetic: "/kəˈsændrə rɪŋ/", pos: "n.", meaning: "Cassandra环", tip: "cassandra + ring" }] },
  { id: 578, root: "dynamodb", phonetic: "/ˈdaɪnəməʊ diːbiː/", pos: "名词", meaning: "DynamoDB数据库", phrases: ["dynamodb table DynamoDB表", "dynamodb item DynamoDB项", "dynamodb partition DynamoDB分区", "dynamodb stream DynamoDB流"], mnemonic: "DynamoDB是AWS的全托管NoSQL数据库", words: [{ word: "dynamodb", phonetic: "/ˈdaɪnəməʊ diːbiː/", pos: "n.", meaning: "DynamoDB", tip: "Dynamo + DB，AWS数据库" }, { word: "dynamo", phonetic: "/ˈdaɪnəməʊ/", pos: "n.", meaning: "Dynamo", tip: "发电机，DynamoDB" }, { word: "aws-dynamodb", phonetic: "/eɪdʌbəljuːˈɛs ˈdaɪnəməʊ diːbiː/", pos: "n.", meaning: "AWS DynamoDB", tip: "aws + dynamodb" }, { word: "dynamodb-client", phonetic: "/ˈdaɪnəməʊ diːbiː ˈklaɪənt/", pos: "n.", meaning: "DynamoDB客户端", tip: "dynamodb + client" }] },
  { id: 579, root: "couchdb", phonetic: "/ˈkaʊtʃ diːbiː/", pos: "名词", meaning: "CouchDB数据库", phrases: ["couchdb document CouchDB文档", "couchdb view CouchDB视图", "couchdb mapreduce CouchDB MapReduce", "couchdb replication CouchDB复制"], mnemonic: "CouchDB是用Erlang编写的面向文档数据库", words: [{ word: "couchdb", phonetic: "/ˈkaʊtʃ diːbiː/", pos: "n.", meaning: "CouchDB", tip: "Couch沙发 + DB，文档数据库" }, { word: "couch", phonetic: "/ˈkaʊtʃ/", pos: "n.", meaning: "Couch", tip: "沙发，CouchDB" }, { word: "pouchdb", phonetic: "/ˈpaʊtʃ diːbiː/", pos: "n.", meaning: "PouchDB", tip: "Pouch小袋，浏览器端CouchDB" }, { word: "couchbase", phonetic: "/ˈkaʊtʃbeɪs/", pos: "n.", meaning: "Couchbase", tip: "Couch + base，NoSQL数据库" }] },
  { id: 580, root: "neo4j", phonetic: "/niːoʊ fɔːr dʒeɪ/", pos: "名词", meaning: "Neo4j图数据库", phrases: ["neo4j graph Neo4j图", "neo4j node Neo4j节点", "neo4j relationship Neo4j关系", "neo4j cypher Neo4j Cypher"], mnemonic: "Neo4j是最流行的图数据库", words: [{ word: "neo4j", phonetic: "/niːoʊ fɔːr dʒeɪ/", pos: "n.", meaning: "Neo4j", tip: "Neo新 + 4j，图数据库" }, { word: "neo", phonetic: "/niːoʊ/", pos: "n.", meaning: "Neo", tip: "新的，Neo4j" }, { word: "cypher", phonetic: "/ˈsaɪfər/", pos: "n.", meaning: "Cypher", tip: "密码，Neo4j查询语言" }, { word: "neo4j-browser", phonetic: "/niːoʊ fɔːr dʒeɪ ˈbraʊzər/", pos: "n.", meaning: "Neo4j浏览器", tip: "neo4j + browser" }] }
];

console.log(`Adding ${allRoots.length} entries (561-580)`);

const newEntries = allRoots.map(r => createEntry(r.id, r.root, r.phonetic, r.pos, r.meaning, r.phrases, r.mnemonic, r.words));

const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
console.log(`Current: ${data.length}`);

const updatedData = [...data, ...newEntries];
console.log(`New total: ${updatedData.length}`);

fs.writeFileSync(filePath, JSON.stringify(updatedData, null, 2));
console.log('Batch 4 (part 1) done!');
