const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'data', 'internet-software.json');

function createEntry(id, root, phonetic, pos, meaning, phrases, mnemonic, words) {
  return {
    id,
    root,
    phonetic,
    partOfSpeech: pos,
    meaning,
    frequency: id,
    category: "互联网和软件",
    words: words.map(w => ({
      word: w.word,
      phonetic: w.phonetic,
      partOfSpeech: w.pos,
      meaning: w.meaning,
      memoryTip: w.tip,
      root,
      rootPhonetic: phonetic,
      rootMeaning: meaning,
      rootPhrases: phrases,
      wordPhrases: w.phrases || phrases.slice(0, 2)
    })),
    phrases,
    mnemonic
  };
}

// 521-600: CSS与样式、UI组件相关
const allRoots = [
  // CSS与样式工具 (521-540)
  { id: 521, root: "sass", phonetic: "/sæs/", pos: "名词", meaning: "Sass CSS预处理器", phrases: ["sass variable Sass变量", "sass mixin Sass混合", "sass nesting Sass嵌套", "sass import Sass导入"], mnemonic: "Sass让CSS像编程语言一样强大", words: [{ word: "sass", phonetic: "/sæs/", pos: "n.", meaning: "Sass", tip: "Syntactically Awesome Style Sheets" }, { word: "scss", phonetic: "/ɛssiːɛsɛs/", pos: "n.", meaning: "SCSS", tip: "Sassy CSS，Sass语法" }, { word: "sass-compiler", phonetic: "/sæs kəmˈpaɪlər/", pos: "n.", meaning: "Sass编译器", tip: "sass + compiler" }, { word: "sass-loader", phonetic: "/sæs ˈloʊdər/", pos: "n.", meaning: "Sass加载器", tip: "sass + loader" }] },
  { id: 522, root: "less", phonetic: "/les/", pos: "名词", meaning: "Less CSS预处理器", phrases: ["less variable Less变量", "less mixin Less混合", "less function Less函数", "less import Less导入"], mnemonic: "Less让CSS编写更少代码，实现更多功能", words: [{ word: "less", phonetic: "/les/", pos: "n.", meaning: "Less", tip: "Leaner Style Sheets" }, { word: "lesscss", phonetic: "/les siːɛsɛs/", pos: "n.", meaning: "Less CSS", tip: "less + css" }, { word: "less-compiler", phonetic: "/les kəmˈpaɪlər/", pos: "n.", meaning: "Less编译器", tip: "less + compiler" }, { word: "less-loader", phonetic: "/les ˈloʊdər/", pos: "n.", meaning: "Less加载器", tip: "less + loader" }] },
  { id: 523, root: "stylus", phonetic: "/ˈstaɪləs/", pos: "名词", meaning: "Stylus CSS预处理器", phrases: ["stylus variable Stylus变量", "stylus mixin Stylus混合", "stylus function Stylus函数", "stylus import Stylus导入"], mnemonic: "Stylus像画笔一样自由书写CSS", words: [{ word: "stylus", phonetic: "/ˈstaɪləs/", pos: "n.", meaning: "Stylus", tip: "画笔，CSS预处理器" }, { word: "stylus-css", phonetic: "/ˈstaɪləs siːɛsɛs/", pos: "n.", meaning: "Stylus CSS", tip: "stylus + css" }, { word: "stylus-compiler", phonetic: "/ˈstaɪləs kəmˈpaɪlər/", pos: "n.", meaning: "Stylus编译器", tip: "stylus + compiler" }, { word: "stylus-loader", phonetic: "/ˈstaɪləs ˈloʊdər/", pos: "n.", meaning: "Stylus加载器", tip: "stylus + loader" }] },
  { id: 524, root: "postcss", phonetic: "/poʊst siːɛsɛs/", pos: "名词", meaning: "PostCSS后处理器", phrases: ["postcss plugin PostCSS插件", "postcss autoprefixer 自动前缀", "postcss config PostCSS配置", "postcss preset-env 预设环境"], mnemonic: "PostCSS用JavaScript插件转换CSS", words: [{ word: "postcss", phonetic: "/poʊst siːɛsɛs/", pos: "n.", meaning: "PostCSS", tip: "post后 + css，后处理" }, { word: "autoprefixer", phonetic: "/ˈɔːtoʊprɪfɪksər/", pos: "n.", meaning: "Autoprefixer", tip: "auto自动 + prefix前缀" }, { word: "postcss-loader", phonetic: "/poʊst siːɛsɛs ˈloʊdər/", pos: "n.", meaning: "PostCSS加载器", tip: "postcss + loader" }, { word: "cssnano", phonetic: "/siːɛsɛsˈnɑːnoʊ/", pos: "n.", meaning: "CSSNano", tip: "css + nano纳米，压缩" }] },
  { id: 525, root: "tailwind", phonetic: "/ˈteɪlwɪnd/", pos: "名词", meaning: "Tailwind CSS框架", phrases: ["tailwind config Tailwind配置", "tailwind utility 工具类", "tailwind component Tailwind组件", "tailwind plugin Tailwind插件"], mnemonic: "Tailwind提供工具类优先的CSS框架", words: [{ word: "tailwind", phonetic: "/ˈteɪlwɪnd/", pos: "n.", meaning: "Tailwind", tip: "尾风，CSS框架" }, { word: "tailwindcss", phonetic: "/ˈteɪlwɪnd siːɛsɛs/", pos: "n.", meaning: "Tailwind CSS", tip: "tailwind + css" }, { word: "tailwind-config", phonetic: "/ˈteɪlwɪnd kənˈfɪɡ/", pos: "n.", meaning: "Tailwind配置", tip: "tailwind + config" }, { word: "tailwind-ui", phonetic: "/ˈteɪlwɪnd juːaɪ/", pos: "n.", meaning: "Tailwind UI", tip: "tailwind + ui" }] },
  { id: 526, root: "bootstrap", phonetic: "/ˈbuːtstræp/", pos: "名词", meaning: "Bootstrap CSS框架", phrases: ["bootstrap grid Bootstrap网格", "bootstrap component Bootstrap组件", "bootstrap theme Bootstrap主题", "bootstrap modal Bootstrap模态框"], mnemonic: "Bootstrap用橡皮筋帮你快速搭建响应式网站", words: [{ word: "bootstrap", phonetic: "/ˈbuːtstræp/", pos: "n.", meaning: "Bootstrap", tip: "靴带，自举，CSS框架" }, { word: "bootstrap4", phonetic: "/ˈbuːtstræp fɔːr/", pos: "n.", meaning: "Bootstrap 4", tip: "bootstrap + 4" }, { word: "bootstrap5", phonetic: "/ˈbuːtstræp faɪv/", pos: "n.", meaning: "Bootstrap 5", tip: "bootstrap + 5" }, { word: "bootstrap-vue", phonetic: "/ˈbuːtstræp vjuː/", pos: "n.", meaning: "Bootstrap Vue", tip: "bootstrap + vue" }] },
  { id: 527, root: "bulma", phonetic: "/ˈbʊlmə/", pos: "名词", meaning: "Bulma CSS框架", phrases: ["bulma column Bulma列", "bulma layout Bulma布局", "bulma element Bulma元素", "bulma component Bulma组件"], mnemonic: "Bulma基于Flexbox的现代CSS框架", words: [{ word: "bulma", phonetic: "/ˈbʊlmə/", pos: "n.", meaning: "Bulma", tip: "布尔玛，CSS框架" }, { word: "bulma-css", phonetic: "/ˈbʊlmə siːɛsɛs/", pos: "n.", meaning: "Bulma CSS", tip: "bulma + css" }, { word: "bulma-vue", phonetic: "/ˈbʊlmə vjuː/", pos: "n.", meaning: "Bulma Vue", tip: "bulma + vue" }, { word: "buefy", phonetic: "/ˈbjuːfɪ/", pos: "n.", meaning: "Buefy", tip: "bulma + vue + fy" }] },
  { id: 528, root: "foundation", phonetic: "/faʊnˈdeɪʃn/", pos: "名词", meaning: "Foundation CSS框架", phrases: ["foundation grid Foundation网格", "foundation component Foundation组件", "foundation site Foundation站点", "foundation email Foundation邮件"], mnemonic: "Foundation是响应式前端框架的基础", words: [{ word: "foundation", phonetic: "/faʊnˈdeɪʃn/", pos: "n.", meaning: "Foundation", tip: "基础，CSS框架" }, { word: "foundation-sites", phonetic: "/faʊnˈdeɪʃn saɪts/", pos: "n.", meaning: "Foundation Sites", tip: "foundation + sites" }, { word: "foundation-css", phonetic: "/faʊnˈdeɪʃn siːɛsɛs/", pos: "n.", meaning: "Foundation CSS", tip: "foundation + css" }, { word: "foundation-email", phonetic: "/faʊnˈdeɪʃn ˈiːmeɪl/", pos: "n.", meaning: "Foundation Email", tip: "foundation + email" }] },
  { id: 529, root: "semantic", phonetic: "/sɪˈmæntɪk/", pos: "形容词", meaning: "语义的", phrases: ["semantic html 语义化HTML", "semantic ui Semantic UI", "semantic web 语义网", "semantic versioning 语义化版本"], mnemonic: "Semantic关注HTML的语义含义", words: [{ word: "semantic", phonetic: "/sɪˈmæntɪk/", pos: "adj.", meaning: "语义的", tip: "语义，含义" }, { word: "semantic-ui", phonetic: "/sɪˈmæntɪk juːaɪ/", pos: "n.", meaning: "Semantic UI", tip: "semantic + ui" }, { word: "semantics", phonetic: "/sɪˈmæntɪks/", pos: "n.", meaning: "语义学", tip: "semantic + s" }, { word: "semantic-html", phonetic: "/sɪˈmæntɪk eɪtʃtiːɛmɛl/", pos: "n.", meaning: "语义化HTML", tip: "semantic + html" }] },
  { id: 530, root: "material", phonetic: "/məˈtɪəriəl/", pos: "名词", meaning: "Material Design", phrases: ["material ui Material UI", "material design Material设计", "material icon Material图标", "material component Material组件"], mnemonic: "Material Design是Google的 Material 设计语言", words: [{ word: "material", phonetic: "/məˈtɪəriəl/", pos: "n.", meaning: "Material", tip: "材料，Material Design" }, { word: "material-ui", phonetic: "/məˈtɪəriəl juːaɪ/", pos: "n.", meaning: "Material UI", tip: "material + ui" }, { word: "materialize", phonetic: "/məˈtɪəriəlaɪz/", pos: "n.", meaning: "Materialize", tip: "materialize CSS框架" }, { word: "material-design", phonetic: "/məˈtɪəriəl dɪˈzaɪn/", pos: "n.", meaning: "Material Design", tip: "material + design" }] },
  { id: 531, root: "styled", phonetic: "/staɪld/", pos: "形容词", meaning: "样式化的", phrases: ["styled-components 样式化组件", "styled-jsx Styled JSX", "styled-system Styled系统", "emotion Emotion样式库"], mnemonic: "Styled-components用CSS-in-JS方式写样式", words: [{ word: "styled", phonetic: "/staɪld/", pos: "adj.", meaning: "样式化的", tip: "style + ed" }, { word: "styled-components", phonetic: "/staɪld kəmˈpoʊnənts/", pos: "n.", meaning: "Styled Components", tip: "styled + components" }, { word: "styled-jsx", phonetic: "/staɪld dʒeɪɛseks/", pos: "n.", meaning: "Styled JSX", tip: "styled + jsx" }, { word: "emotion", phonetic: "/ɪˈmoʊʃn/", pos: "n.", meaning: "Emotion", tip: "情感，CSS-in-JS库" }] },
  { id: 532, root: "css-module", phonetic: "/siːɛsɛs ˈmɒdjuːl/", pos: "名词", meaning: "CSS模块", phrases: ["css module CSS模块", "css module local 局部CSS", "css module global 全局CSS", "css module compose CSS组合"], mnemonic: "CSS Modules让CSS类名局部化，避免冲突", words: [{ word: "css-module", phonetic: "/siːɛsɛs ˈmɒdjuːl/", pos: "n.", meaning: "CSS模块", tip: "css + module" }, { word: "css-modules", phonetic: "/siːɛsɛs ˈmɒdjuːlz/", pos: "n.", meaning: "CSS模块", tip: "css + modules" }, { word: "module-css", phonetic: "/ˈmɒdjuːl siːɛsɛs/", pos: "n.", meaning: "模块CSS", tip: "module + css" }, { word: "scoped-css", phonetic: "/skoʊpt siːɛsɛs/", pos: "n.", meaning: "作用域CSS", tip: "scoped + css" }] },
  { id: 533, root: "bem", phonetic: "/biːiːɛm/", pos: "名词", meaning: "BEM命名规范", phrases: ["bem naming BEM命名", "bem block BEM块", "bem element BEM元素", "bem modifier BEM修饰符"], mnemonic: "BEM=Block Element Modifier，CSS命名规范", words: [{ word: "bem", phonetic: "/biːiːɛm/", pos: "n.", meaning: "BEM", tip: "Block Element Modifier" }, { word: "bem-css", phonetic: "/biːiːɛm siːɛsɛs/", pos: "n.", meaning: "BEM CSS", tip: "bem + css" }, { word: "block-element-modifier", phonetic: "/blɒk ˈelɪmənt ˈmɒdɪfaɪər/", pos: "n.", meaning: "块元素修饰符", tip: "BEM全称" }, { word: "bem-methodology", phonetic: "/biːiːɛm meθəˈdɒlədʒi/", pos: "n.", meaning: "BEM方法论", tip: "bem + methodology" }] },
  { id: 534, root: "atomic", phonetic: "/əˈtɒmɪk/", pos: "形容词", meaning: "原子的", phrases: ["atomic css Atomic CSS", "atomic design Atomic设计", "atomic component Atomic组件", "atomic commit Atomic提交"], mnemonic: "Atomic CSS每个类只做一件事", words: [{ word: "atomic", phonetic: "/əˈtɒmɪk/", pos: "adj.", meaning: "原子的", tip: "atom + ic" }, { word: "atomic-css", phonetic: "/əˈtɒmɪk siːɛsɛs/", pos: "n.", meaning: "Atomic CSS", tip: "atomic + css" }, { word: "atomic-design", phonetic: "/əˈtɒmɪk dɪˈzaɪn/", pos: "n.", meaning: "Atomic Design", tip: "atomic + design" }, { word: "tachyons", phonetic: "/ˈtækiɒnz/", pos: "n.", meaning: "Tachyons", tip: "速子，Atomic CSS库" }] },
  { id: 535, root: "normalize", phonetic: "/ˈnɔːrməlaɪz/", pos: "动词", meaning: "标准化", phrases: ["normalize.css 标准化CSS", "normalize reset 标准化重置", "normalize browser 浏览器标准化", "normalize style 样式标准化"], mnemonic: "Normalize.css让浏览器渲染所有元素更一致", words: [{ word: "normalize", phonetic: "/ˈnɔːrməlaɪz/", pos: "v.", meaning: "标准化", tip: "normal正常 + ize化" }, { word: "normalize-css", phonetic: "/ˈnɔːrməlaɪz siːɛsɛs/", pos: "n.", meaning: "Normalize.css", tip: "normalize + css" }, { word: "normalization", phonetic: "/ˈnɔːrmələˈzeɪʃn/", pos: "n.", meaning: "标准化", tip: "normalize + ation" }, { word: "reset-css", phonetic: "/ˈreset siːɛsɛs/", pos: "n.", meaning: "Reset CSS", tip: "reset + css" }] },
  { id: 536, root: "minify", phonetic: "/ˈmɪnɪfaɪ/", pos: "动词", meaning: "压缩", phrases: ["minify css CSS压缩", "minify js JS压缩", "minify html HTML压缩", "minify bundle 包压缩"], mnemonic: "Minify把代码压缩成最小体积", words: [{ word: "minify", phonetic: "/ˈmɪnɪfaɪ/", pos: "v.", meaning: "压缩", tip: "mini小 + fy化" }, { word: "minification", phonetic: "/ˈmɪnɪfɪˈkeɪʃn/", pos: "n.", meaning: "压缩", tip: "minify + cation" }, { word: "minified", phonetic: "/ˈmɪnɪfaɪd/", pos: "adj.", meaning: "已压缩的", tip: "minify + ed" }, { word: "unminify", phonetic: "/ʌnˈmɪnɪfaɪ/", pos: "v.", meaning: "解压", tip: "un + minify" }] },
  { id: 537, root: "purge", phonetic: "/pɜːrdʒ/", pos: "动词", meaning: "清除", phrases: ["purge css 清除CSS", "purge unused 清除未使用", "purge cache 清除缓存", "purge css webpack PurgeCSS"], mnemonic: "PurgeCSS清除未使用的CSS样式", words: [{ word: "purge", phonetic: "/pɜːrdʒ/", pos: "v.", meaning: "清除", tip: "清洗，净化" }, { word: "purgecss", phonetic: "/pɜːrdʒ siːɛsɛs/", pos: "n.", meaning: "PurgeCSS", tip: "purge + css" }, { word: "purging", phonetic: "/ˈpɜːrdʒɪŋ/", pos: "n.", meaning: "清除中", tip: "purge + ing" }, { word: "purged", phonetic: "/pɜːrdʒd/", pos: "adj.", meaning: "已清除的", tip: "purge + ed" }] },
  { id: 538, root: "critical", phonetic: "/ˈkrɪtɪkl/", pos: "形容词", meaning: "关键的", phrases: ["critical css 关键CSS", "critical path 关键路径", "critical resource 关键资源", "critical render 关键渲染"], mnemonic: "Critical CSS提取首屏关键样式", words: [{ word: "critical", phonetic: "/ˈkrɪtɪkl/", pos: "adj.", meaning: "关键的", tip: "critic批评 + al" }, { word: "critical-css", phonetic: "/ˈkrɪtɪkl siːɛsɛs/", pos: "n.", meaning: "关键CSS", tip: "critical + css" }, { word: "critical-path", phonetic: "/ˈkrɪtɪkl pæθ/", pos: "n.", meaning: "关键路径", tip: "critical + path" }, { word: "critical-rendering", phonetic: "/ˈkrɪtɪkl ˈrɛndərɪŋ/", pos: "n.", meaning: "关键渲染", tip: "critical + rendering" }] },
  { id: 539, root: "polyfill", phonetic: "/ˈpɒlifɪl/", pos: "名词", meaning: "垫片", phrases: ["polyfill js JS垫片", "polyfill browser 浏览器垫片", "polyfill feature 功能垫片", "polyfill core-js CoreJS垫片"], mnemonic: "Polyfill填补浏览器缺失的功能", words: [{ word: "polyfill", phonetic: "/ˈpɒlifɪl/", pos: "n.", meaning: "垫片", tip: "poly多 + fill填充" }, { word: "polyfilling", phonetic: "/ˈpɒlifɪlɪŋ/", pos: "n.", meaning: "垫片填充", tip: "polyfill + ing" }, { word: "core-js", phonetic: "/kɔːr dʒeɪɛs/", pos: "n.", meaning: "CoreJS", tip: "core + js，模块化JS标准库" }, { word: "polyfilled", phonetic: "/ˈpɒlifɪld/", pos: "adj.", meaning: "已填充的", tip: "polyfill + ed" }] },
  { id: 540, root: "shim", phonetic: "/ʃɪm/", pos: "名词", meaning: "垫片", phrases: ["shim code 垫片代码", "shim library 垫片库", "shim pattern 垫片模式", "es6-shim ES6垫片"], mnemonic: "Shim是小型垫片库，让旧环境支持新API", words: [{ word: "shim", phonetic: "/ʃɪm/", pos: "n.", meaning: "垫片", tip: "垫片，填隙片" }, { word: "es6-shim", phonetic: "/iːɛsɛks ʃɪm/", pos: "n.", meaning: "ES6 Shim", tip: "es6 + shim" }, { word: "shimming", phonetic: "/ˈʃɪmɪŋ/", pos: "n.", meaning: "垫片技术", tip: "shim + ming" }, { word: "shim-layer", phonetic: "/ʃɪm ˈleɪər/", pos: "n.", meaning: "垫片层", tip: "shim + layer" }] }
];

console.log(`Adding ${allRoots.length} new entries (521-540)`);

const newEntries = allRoots.map(r => createEntry(r.id, r.root, r.phonetic, r.pos, r.meaning, r.phrases, r.mnemonic, r.words));

const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
console.log(`Current entries: ${data.length}`);

const updatedData = [...data, ...newEntries];
console.log(`New total: ${updatedData.length}`);

fs.writeFileSync(filePath, JSON.stringify(updatedData, null, 2));
console.log('Batch 2 done!');
