import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 200个四级词根数据
const newRoots = [
  { id: 801, root: "act", phonetic: "/ækt/", meaning: "做，行动", words: ["action", "active", "activity", "actor", "actress"] },
  { id: 802, root: "ag", phonetic: "/æg/", meaning: "做，行动", words: ["agent", "agency", "agenda", "agitate"] },
  { id: 803, root: "ampl", phonetic: "/æmpl/", meaning: "大，宽", words: ["ample", "amplify", "amplifier", "amplitude"] },
  { id: 804, root: "anim", phonetic: "/ænɪm/", meaning: "生命，精神", words: ["animal", "animate", "animation", "animator"] },
  { id: 805, root: "ann", phonetic: "/æn/", meaning: "年", words: ["annual", "anniversary", "annually", "annuity"] },
  { id: 806, root: "anthrop", phonetic: "/ænθrəp/", meaning: "人，人类", words: ["anthropology", "anthropologist", "anthropomorphic"] },
  { id: 807, root: "aqu", phonetic: "/ækwə/", meaning: "水", words: ["aquarium", "aquatic", "aqueduct", "aqueous"] },
  { id: 808, root: "arch", phonetic: "/ɑːtʃ/", meaning: "统治，主要", words: ["architect", "architecture", "archive", "monarch"] },
  { id: 809, root: "art", phonetic: "/ɑːt/", meaning: "技艺，艺术", words: ["artist", "artistic", "artificial", "artifact"] },
  { id: 810, root: "astro", phonetic: "/æstrəʊ/", meaning: "星，宇宙", words: ["astronaut", "astronomy", "astrology", "asterisk"] },
  { id: 811, root: "audi", phonetic: "/ɔːdi/", meaning: "听", words: ["audience", "audio", "auditorium", "audible"] },
  { id: 812, root: "auto", phonetic: "/ɔːtəʊ/", meaning: "自己，自动", words: ["automatic", "automobile", "autonomy", "autograph"] },
  { id: 813, root: "bell", phonetic: "/bel/", meaning: "战争", words: ["rebel", "rebellion", "bellicose", "antebellum"] },
  { id: 814, root: "bene", phonetic: "/beni/", meaning: "好，善", words: ["benefit", "beneficial", "benevolent", "benefactor"] },
  { id: 815, root: "bi", phonetic: "/baɪ/", meaning: "二，双", words: ["bicycle", "bilingual", "bilateral", "bisect"] },
  { id: 816, root: "biblio", phonetic: "/bɪbliəʊ/", meaning: "书", words: ["bibliography", "bibliophile", "Bible", "bibliotheca"] },
  { id: 817, root: "bio", phonetic: "/baɪəʊ/", meaning: "生命，生物", words: ["biology", "biography", "biodegradable"] },
  { id: 818, root: "ced", phonetic: "/siːd/", meaning: "走，让步", words: ["proceed", "succeed", "exceed", "recede", "concede"] },
  { id: 819, root: "cept", phonetic: "/sept/", meaning: "拿，抓", words: ["accept", "except", "concept", "reception", "perception"] },
  { id: 820, root: "cert", phonetic: "/sɜːt/", meaning: "确定，确信", words: ["certain", "certificate", "certify", "ascertain"] },
  { id: 821, root: "chron", phonetic: "/krɒn/", meaning: "时间", words: ["chronic", "chronicle", "chronology", "synchronize"] },
  { id: 822, root: "cide", phonetic: "/saɪd/", meaning: "杀，切", words: ["suicide", "homicide", "pesticide", "insecticide"] },
  { id: 823, root: "circum", phonetic: "/sɜːkəm/", meaning: "周围", words: ["circumstance", "circumference", "circumvent", "circumspect"] },
  { id: 824, root: "cis", phonetic: "/sɪs/", meaning: "切，割", words: ["decision", "precise", "incisive", "concise", "excise"] },
  { id: 825, root: "claim", phonetic: "/kleɪm/", meaning: "喊，叫", words: ["exclaim", "proclaim", "acclaim", "declaim", "reclaim"] },
  { id: 826, root: "clar", phonetic: "/klɑːr/", meaning: "清楚，明白", words: ["clarify", "clarity", "declare", "clear"] },
  { id: 827, root: "clud", phonetic: "/kluːd/", meaning: "关闭", words: ["conclude", "exclude", "include", "preclude", "seclude"] },
  { id: 828, root: "cogn", phonetic: "/kɒgn/", meaning: "知道，认识", words: ["recognize", "cognitive", "cognition", "incognito"] },
  { id: 829, root: "cord", phonetic: "/kɔːd/", meaning: "心，一致", words: ["accord", "concord", "discord", "cordial", "record"] },
  { id: 830, root: "corp", phonetic: "/kɔːp/", meaning: "身体", words: ["corpse", "corporate", "incorporate", "corporeal"] },
  { id: 831, root: "cosm", phonetic: "/kɒzm/", meaning: "宇宙，世界", words: ["cosmic", "cosmos", "cosmopolitan", "cosmetics"] },
  { id: 832, root: "counter", phonetic: "/kaʊntə/", meaning: "反对，相反", words: ["counteract", "counterpart", "encounter", "countersign"] },
  { id: 833, root: "cracy", phonetic: "/krəsi/", meaning: "统治", words: ["democracy", "bureaucracy", "aristocracy", "theocracy"] },
  { id: 834, root: "cre", phonetic: "/kriː/", meaning: "生长，创造", words: ["create", "increase", "decrease", "recruit", "concrete"] },
  { id: 835, root: "cred", phonetic: "/kred/", meaning: "相信，信任", words: ["credit", "credible", "incredible", "credential"] },
  { id: 836, root: "crit", phonetic: "/krɪt/", meaning: "判断，分辨", words: ["critic", "critical", "criticize", "criteria", "crisis"] },
  { id: 837, root: "cur", phonetic: "/kɜːr/", meaning: "跑，发生", words: ["current", "occur", "recur", "concur", "incursion"] },
  { id: 838, root: "cycl", phonetic: "/saɪkl/", meaning: "圆，环", words: ["cycle", "bicycle", "recycle", "cyclone", "encyclopedia"] },
  { id: 839, root: "de", phonetic: "/diː/", meaning: "向下，否定", words: ["decrease", "decline", "define", "describe", "depart"] },
  { id: 840, root: "dem", phonetic: "/dem/", meaning: "人民", words: ["democracy", "demographics", "epidemic", "pandemic"] },
  { id: 841, root: "dent", phonetic: "/dent/", meaning: "牙齿", words: ["dentist", "dental", "indent", "denture"] },
  { id: 842, root: "derm", phonetic: "/dɜːm/", meaning: "皮肤", words: ["dermatology", "dermis", "epidermis", "hypodermic"] },
  { id: 843, root: "dict", phonetic: "/dɪkt/", meaning: "说，讲", words: ["dictionary", "predict", "contradict", "dictate", "verdict"] },
  { id: 844, root: "dis", phonetic: "/dɪs/", meaning: "分开，否定", words: ["disagree", "disappear", "dismiss", "distribute", "distract"] },
  { id: 845, root: "doc", phonetic: "/dɒk/", meaning: "教，学问", words: ["doctor", "document", "doctrine", "docile"] },
  { id: 846, root: "domin", phonetic: "/dɒmɪn/", meaning: "统治，控制", words: ["dominate", "domain", "domestic", "predominant"] },
  { id: 847, root: "don", phonetic: "/dɒn/", meaning: "给予", words: ["donate", "donor", "pardon", "condone"] },
  { id: 848, root: "dorm", phonetic: "/dɔːm/", meaning: "睡眠", words: ["dormitory", "dormant", "dormancy"] },
  { id: 849, root: "du", phonetic: "/djuː/", meaning: "二，双", words: ["dual", "duet", "duplicate", "duplicity", "duplex"] },
  { id: 850, root: "duc", phonetic: "/djuːk/", meaning: "引导，带来", words: ["educate", "introduce", "produce", "reduce", "conduct"] },
  { id: 851, root: "dur", phonetic: "/djʊər/", meaning: "持久，坚硬", words: ["during", "endure", "duration", "durable"] },
  { id: 852, root: "dyn", phonetic: "/daɪn/", meaning: "力量", words: ["dynamic", "dynasty", "dynamite", "aerodynamics"] },
  { id: 853, root: "eco", phonetic: "/iːkəʊ/", meaning: "家，环境", words: ["economy", "ecology", "ecosystem", "economics"] },
  { id: 854, root: "enn", phonetic: "/en/", meaning: "年", words: ["annual", "anniversary", "perennial", "biennial"] },
  { id: 855, root: "em", phonetic: "/em/", meaning: "拿，买", words: ["example", "exempt", "prompt", "premium"] },
  { id: 856, root: "equ", phonetic: "/iːkw/", meaning: "相等，平均", words: ["equal", "equator", "adequate", "equation", "equivalent"] },
  { id: 857, root: "erg", phonetic: "/ɜːg/", meaning: "工作，能量", words: ["energy", "allergy", "energetic", "ergonomics"] },
  { id: 858, root: "err", phonetic: "/ɜːr/", meaning: "漫游，错误", words: ["error", "erratic", "erroneous", "aberration"] },
  { id: 859, root: "ev", phonetic: "/iːv/", meaning: "年代，时间", words: ["medieval", "primeval", "longevity", "eternal"] },
  { id: 860, root: "extra", phonetic: "/ekstrə/", meaning: "超出，以外", words: ["extraordinary", "extracurricular", "extravagant", "external"] },
  { id: 861, root: "fabr", phonetic: "/fæbr/", meaning: "制作，构造", words: ["fabric", "fabricate", "prefabricated"] },
  { id: 862, root: "fac", phonetic: "/fæk/", meaning: "做，制作", words: ["factory", "facilitate", "benefactor", "manufacture"] },
  { id: 863, root: "fer", phonetic: "/fɜːr/", meaning: "携带，产生", words: ["transfer", "refer", "infer", "confer", "prefer"] },
  { id: 864, root: "fid", phonetic: "/fɪd/", meaning: "相信，信任", words: ["confident", "fidelity", "confide", "infidel"] },
  { id: 865, root: "fin", phonetic: "/fɪn/", meaning: "结束，界限", words: ["final", "finish", "finite", "define", "confine"] },
  { id: 866, root: "firm", phonetic: "/fɜːm/", meaning: "坚固，坚定", words: ["firm", "confirm", "affirm", "infirm"] },
  { id: 867, root: "fix", phonetic: "/fɪks/", meaning: "固定，修理", words: ["fix", "fixture", "prefix", "suffix", "affix"] },
  { id: 868, root: "flex", phonetic: "/fleks/", meaning: "弯曲", words: ["flexible", "reflect", "deflect", "inflect"] },
  { id: 869, root: "flu", phonetic: "/fluː/", meaning: "流动", words: ["fluent", "influence", "fluid", "flush", "affluent"] },
  { id: 870, root: "form", phonetic: "/fɔːm/", meaning: "形状，形式", words: ["form", "format", "transform", "inform", "perform"] },
  { id: 871, root: "fort", phonetic: "/fɔːt/", meaning: "强壮，力量", words: ["effort", "comfort", "fortune", "fortify", "fortress"] },
  { id: 872, root: "fract", phonetic: "/frækt/", meaning: "打破，折断", words: ["fraction", "fragment", "fracture", "fragile", "refract"] },
  { id: 873, root: "fug", phonetic: "/fjuːg/", meaning: "逃，离开", words: ["refuge", "fugitive", "refugee", "centrifugal"] },
  { id: 874, root: "fus", phonetic: "/fjuːz/", meaning: "流，注，融", words: ["confuse", "refuse", "transfusion", "infuse", "diffuse"] },
  { id: 875, root: "gen", phonetic: "/dʒen/", meaning: "产生，出生", words: ["generate", "gene", "genetic", "general", "genuine"] },
  { id: 876, root: "geo", phonetic: "/dʒiːəʊ/", meaning: "地球，土地", words: ["geography", "geology", "geometry", "geopolitics"] },
  { id: 877, root: "ger", phonetic: "/dʒɜːr/", meaning: "携带，支撑", words: ["belligerent", "digest", "suggest"] },
  { id: 878, root: "gon", phonetic: "/gɒn/", meaning: "角，弯曲", words: ["polygon", "pentagon", "diagonal", "octagon", "hexagon"] },
  { id: 879, root: "grad", phonetic: "/græd/", meaning: "步，级", words: ["grade", "graduate", "gradual", "degrade", "upgrade"] },
  { id: 880, root: "gram", phonetic: "/græm/", meaning: "写，画", words: ["grammar", "diagram", "program", "telegram", "biography"] },
  { id: 881, root: "graph", phonetic: "/græf/", meaning: "写，画，记录", words: ["graphic", "photograph", "autograph", "geography", "biography"] },
  { id: 882, root: "grat", phonetic: "/græt/", meaning: "高兴，感激", words: ["grateful", "gratitude", "congratulate", "ingrate"] },
  { id: 883, root: "grav", phonetic: "/græv/", meaning: "重，严重", words: ["gravity", "grave", "aggravate", "grief"] },
  { id: 884, root: "greg", phonetic: "/greg/", meaning: "群，集合", words: ["gregarious", "aggregate", "congregate", "segregate"] },
  { id: 885, root: "gress", phonetic: "/gres/", meaning: "走", words: ["progress", "congress", "aggressive", "egress", "ingress"] },
  { id: 886, root: "habit", phonetic: "/hæbɪt/", meaning: "居住，有", words: ["habit", "inhabit", "habitat", "cohabit"] },
  { id: 887, root: "hap", phonetic: "/hæp/", meaning: "运气，机会", words: ["happen", "happy", "perhaps", "mishap"] },
  { id: 888, root: "helio", phonetic: "/hiːliəʊ/", meaning: "太阳", words: ["helium", "heliocentric", "heliotrope"] },
  { id: 889, root: "hemo", phonetic: "/hiːməʊ/", meaning: "血", words: ["hemoglobin", "hemorrhage", "hemophilia"] },
  { id: 890, root: "here", phonetic: "/hɪər/", meaning: "粘着", words: ["adhere", "coherent", "inherent", "hesitate"] },
  { id: 891, root: "hom", phonetic: "/hɒm/", meaning: "相同", words: ["homogeneous", "homosexual", "homonym", "homophone"] },
  { id: 892, root: "hydr", phonetic: "/haɪdr/", meaning: "水", words: ["hydrogen", "hydrant", "dehydrate", "hydraulic", "hydroelectric"] },
  { id: 893, root: "hypn", phonetic: "/hɪpn/", meaning: "睡眠", words: ["hypnosis", "hypnotic", "hypnotize", "insomnia"] },
  { id: 894, root: "iso", phonetic: "/aɪsəʊ/", meaning: "相等，相同", words: ["isotope", "isosceles", "isobar", "isotherm"] },
  { id: 895, root: "ject", phonetic: "/dʒekt/", meaning: "投掷，扔", words: ["project", "reject", "inject", "eject", "subject"] },
  { id: 896, root: "jud", phonetic: "/dʒuːd/", meaning: "判断，法律", words: ["judge", "judicial", "prejudice", "adjudicate"] },
  { id: 897, root: "junct", phonetic: "/dʒʌŋkt/", meaning: "连接，结合", words: ["junction", "adjunct", "conjunction", "disjunct"] },
  { id: 898, root: "juven", phonetic: "/dʒuːvən/", meaning: "年轻", words: ["juvenile", "rejuvenate", "juvenescence"] },
  { id: 899, root: "labor", phonetic: "/leɪbər/", meaning: "劳动，工作", words: ["labor", "collaborate", "elaborate", "laboratory"] },
  { id: 900, root: "lect", phonetic: "/lekt/", meaning: "选择，读", words: ["select", "collect", "lecture", "intellect", "elegant"] },
  { id: 901, root: "leg", phonetic: "/leg/", meaning: "法律，读", words: ["legal", "legend", "legislate", "privilege", "delegate"] },
  { id: 902, root: "lev", phonetic: "/lev/", meaning: "举起，轻", words: ["elevator", "lever", "relieve", "alleviate", "levy"] },
  { id: 903, root: "liber", phonetic: "/lɪbər/", meaning: "自由", words: ["liberty", "liberal", "liberate", "illiberal"] },
  { id: 904, root: "lingu", phonetic: "/lɪŋgw/", meaning: "语言", words: ["linguist", "bilingual", "multilingual", "linguistics"] },
  { id: 905, root: "liter", phonetic: "/lɪtər/", meaning: "文字，字母", words: ["literature", "literal", "literacy", "illiterate", "literary"] },
  { id: 906, root: "loc", phonetic: "/lɒk/", meaning: "地方", words: ["local", "locate", "allocate", "relocate", "locality"] },
  { id: 907, root: "log", phonetic: "/lɒg/", meaning: "说话，学问", words: ["dialogue", "logic", "apologize", "monologue", "prologue"] },
  { id: 908, root: "loqu", phonetic: "/ləʊkw/", meaning: "说话", words: ["eloquent", "colloquial", "loquacious", "circumlocution"] },
  { id: 909, root: "luc", phonetic: "/luːs/", meaning: "光，亮", words: ["lucid", "elucidate", "translucent", "pellucid"] },
  { id: 910, root: "lumin", phonetic: "/luːmɪn/", meaning: "光", words: ["illuminate", "luminous", "luminary", "illustrate"] },
  { id: 911, root: "lun", phonetic: "/luːn/", meaning: "月亮", words: ["lunar", "lunatic", "lunacy", "semilunar"] },
  { id: 912, root: "magn", phonetic: "/mægn/", meaning: "大，伟大", words: ["magnify", "magnificent", "magnitude", "magnate"] },
  { id: 913, root: "maj", phonetic: "/meɪdʒ/", meaning: "大，伟大", words: ["major", "majority", "majesty", "mayor"] },
  { id: 914, root: "man", phonetic: "/mæn/", meaning: "手", words: ["manual", "manufacture", "manuscript", "manipulate", "emancipate"] },
  { id: 915, root: "mand", phonetic: "/mænd/", meaning: "命令", words: ["command", "demand", "mandate", "countermand", "remand"] },
  { id: 916, root: "mar", phonetic: "/mɑːr/", meaning: "海", words: ["marine", "submarine", "maritime", "mariner"] },
  { id: 917, root: "mater", phonetic: "/meɪtər/", meaning: "母亲", words: ["maternal", "matron", "matrimony", "matrix"] },
  { id: 918, root: "med", phonetic: "/med/", meaning: "治疗，中间", words: ["medical", "medicine", "mediate", "medium", "medieval"] },
  { id: 919, root: "mega", phonetic: "/megə/", meaning: "大，百万", words: ["megabyte", "megalopolis", "megaphone", "megalith"] },
  { id: 920, root: "memor", phonetic: "/memər/", meaning: "记忆", words: ["memory", "memorial", "memorize", "commemorate", "immemorial"] },
  { id: 921, root: "ment", phonetic: "/ment/", meaning: "心智，思考", words: ["mental", "mention", "comment", "demented"] },
  { id: 922, root: "merge", phonetic: "/mɜːrdʒ/", meaning: "沉，没", words: ["merge", "emerge", "submerge", "immerse", "emergency"] },
  { id: 923, root: "meter", phonetic: "/miːtər/", meaning: "测量", words: ["thermometer", "barometer", "diameter", "parameter", "geometry"] },
  { id: 924, root: "micro", phonetic: "/maɪkrəʊ/", meaning: "小，微", words: ["microphone", "microscope", "microwave", "microbe", "microchip"] },
  { id: 925, root: "migr", phonetic: "/maɪgr/", meaning: "移动，迁移", words: ["migrate", "immigrant", "emigrate", "transmigrate"] },
  { id: 926, root: "milit", phonetic: "/mɪlɪt/", meaning: "兵，军事", words: ["military", "militant", "militia", "demilitarize"] },
  { id: 927, root: "mill", phonetic: "/mɪl/", meaning: "千，千分之一", words: ["millennium", "millimeter", "million", "milligram"] },
  { id: 928, root: "min", phonetic: "/mɪn/", meaning: "小，少", words: ["minor", "minute", "minimum", "diminish", "miniature"] },
  { id: 929, root: "mir", phonetic: "/mɪər/", meaning: "惊讶，看", words: ["admire", "mirror", "miracle", "mirage", "admiration"] },
  { id: 930, root: "miss", phonetic: "/mɪs/", meaning: "送，发，投", words: ["mission", "emit", "submit", "omit", "permit", "transmit"] },
  { id: 931, root: "mob", phonetic: "/mɒb/", meaning: "动，移动", words: ["mobile", "automobile", "mobilize", "immobile", "mobility"] },
  { id: 932, root: "mod", phonetic: "/mɒd/", meaning: "模式，尺度", words: ["model", "moderate", "modify", "accommodate", "commodity"] },
  { id: 933, root: "mon", phonetic: "/mɒn/", meaning: "警告，提醒", words: ["monitor", "monument", "admonish", "premonition", "summon"] },
  { id: 934, root: "mono", phonetic: "/mɒnəʊ/", meaning: "单一", words: ["monopoly", "monotonous", "monologue", "monarch", "monochrome"] },
  { id: 935, root: "morph", phonetic: "/mɔːf/", meaning: "形状", words: ["metamorphosis", "amorphous", "morphology", "polymorphous"] },
  { id: 936, root: "mort", phonetic: "/mɔːt/", meaning: "死", words: ["mortal", "immortal", "mortgage", "mortify", "postmortem"] },
  { id: 937, root: "mot", phonetic: "/məʊt/", meaning: "移动", words: ["motion", "motive", "motivate", "remote", "promote"] },
  { id: 938, root: "mount", phonetic: "/maʊnt/", meaning: "山", words: ["mountain", "mount", "amount", "mountaineer", "mountainous"] },
  { id: 939, root: "multi", phonetic: "/mʌlti/", meaning: "多，许多", words: ["multiple", "multiply", "multitude", "multimedia", "multinational"] },
  { id: 940, root: "mut", phonetic: "/mjuːt/", meaning: "改变", words: ["mutual", "commute", "mutation", "transmute", "immutable"] },
  { id: 941, root: "nat", phonetic: "/næt/", meaning: "出生，天生", words: ["nation", "native", "nature", "neonate", "innate"] },
  { id: 942, root: "nav", phonetic: "/næv/", meaning: "船，航行", words: ["navy", "naval", "navigate", "navigation", "circumnavigate"] },
  { id: 943, root: "nect", phonetic: "/nekt/", meaning: "连接，绑", words: ["connect", "connection", "disconnect", "annex"] },
  { id: 944, root: "neg", phonetic: "/neg/", meaning: "否定，否认", words: ["negative", "neglect", "negotiate", "renege"] },
  { id: 945, root: "neo", phonetic: "/niːəʊ/", meaning: "新", words: ["neon", "neoclassical", "neologism", "neolithic"] },
  { id: 946, root: "nomin", phonetic: "/nɒmɪn/", meaning: "名字", words: ["nominate", "nominal", "ignominious", "denomination"] },
  { id: 947, root: "norm", phonetic: "/nɔːm/", meaning: "规则，标准", words: ["normal", "abnormal", "enormous", "normalize", "subnormal"] },
  { id: 948, root: "not", phonetic: "/nəʊt/", meaning: "知道，标记", words: ["note", "notice", "notion", "notorious", "denote", "annotate"] },
  { id: 949, root: "nounce", phonetic: "/naʊns/", meaning: "报告，讲述", words: ["announce", "pronounce", "denounce", "renounce"] },
  { id: 950, root: "nov", phonetic: "/nɒv/", meaning: "新", words: ["novel", "innovation", "novice", "renovate", "novelty"] },
  { id: 951, root: "numer", phonetic: "/nuːmər/", meaning: "数字，数目", words: ["number", "numerous", "numerical", "enumerate", "innumerable"] },
  { id: 952, root: "oper", phonetic: "/ɒpər/", meaning: "工作", words: ["operate", "cooperate", "opera", "manual"] },
  { id: 953, root: "opt", phonetic: "/ɒpt/", meaning: "选择，视力", words: ["option", "adopt", "optimum", "optical", "optician"] },
  { id: 954, root: "ora", phonetic: "/ɔːrə/", meaning: "说，嘴", words: ["oral", "adore", "inexorable", "oracle", "orate"] },
  { id: 955, root: "ori", phonetic: "/ɔːri/", meaning: "升起，开始", words: ["origin", "original", "orient", "aboriginal", "disorient"] },
  { id: 956, root: "orn", phonetic: "/ɔːn/", meaning: "装饰", words: ["adorn", "ornament", "adornment", "ornate", "suborn"] },
  { id: 957, root: "ortho", phonetic: "/ɔːθəʊ/", meaning: "直，正", words: ["orthodox", "orthogonal", "orthopedics", "orthodontics"] },
  { id: 958, root: "pac", phonetic: "/pæk/", meaning: "和平，平静", words: ["peace", "pacific", "pacify", "appease", "pacifist"] },
  { id: 959, root: "part", phonetic: "/pɑːt/", meaning: "部分，分开", words: ["part", "particle", "partial", "depart", "impart", "partition"] },
  { id: 960, root: "path", phonetic: "/pæθ/", meaning: "感情，痛苦", words: ["sympathy", "pathetic", "pathology", "empathy", "antipathy"] },
  { id: 961, root: "pater", phonetic: "/peɪtər/", meaning: "父亲", words: ["paternal", "paternity", "patriarch", "patron", "patriot"] },
  { id: 962, root: "ped", phonetic: "/ped/", meaning: "脚，儿童", words: ["pedal", "pedestrian", "expedition", "biped", "centipede"] },
  { id: 963, root: "pel", phonetic: "/pel/", meaning: "推，驱使", words: ["compel", "propel", "expel", "repel", "impel", "dispel"] },
  { id: 964, root: "pend", phonetic: "/pend/", meaning: "悬挂，衡量", words: ["depend", "suspend", "appendix", "pending", "impending"] },
  { id: 965, root: "peri", phonetic: "/peri/", meaning: "周围，附近", words: ["period", "periphery", "periscope", "peripatetic"] },
  { id: 966, root: "pet", phonetic: "/pet/", meaning: "追求，寻求", words: ["compete", "appetite", "petition", "competent", "impetus"] },
  { id: 967, root: "phil", phonetic: "/fɪl/", meaning: "爱", words: ["philosophy", "philanthropy", "bibliophile", "anglophile"] },
  { id: 968, root: "phon", phonetic: "/fəʊn/", meaning: "声音", words: ["telephone", "phonetics", "symphony", "microphone", "euphony"] },
  { id: 969, root: "photo", phonetic: "/fəʊtəʊ/", meaning: "光", words: ["photograph", "photosynthesis", "photon", "photocopy"] },
  { id: 970, root: "phys", phonetic: "/fɪz/", meaning: "自然，生长", words: ["physics", "physical", "physician", "metaphysics"] },
  { id: 971, root: "plac", phonetic: "/plæk/", meaning: "平静，安慰", words: ["placid", "complacent", "implacable", "placebo", "placate"] },
  { id: 972, root: "pli", phonetic: "/plaɪ/", meaning: "满，填满", words: ["accomplish", "complement", "supplement", "implement", "comply"] },
  { id: 973, root: "plic", phonetic: "/plɪk/", meaning: "重叠，折叠", words: ["complicated", "explicit", "implicit", "duplicate", "supplicate"] },
  { id: 974, root: "plor", phonetic: "/plɔːr/", meaning: "哭，喊", words: ["explore", "deplore", "implore"] },
  { id: 975, root: "polis", phonetic: "/pɒlɪs/", meaning: "城市", words: ["police", "politics", "metropolis", "cosmopolitan", "megalopolis"] },
  { id: 976, root: "port", phonetic: "/pɔːt/", meaning: "携带，搬运", words: ["transport", "export", "import", "portable", "portfolio", "report"] },
  { id: 977, root: "pos", phonetic: "/pɒz/", meaning: "放置", words: ["position", "compose", "propose", "oppose", "dispose", "expose"] },
  { id: 978, root: "preci", phonetic: "/priːʃi/", meaning: "价值，价格", words: ["precious", "appreciate", "depreciate", "price"] },
  { id: 979, root: "prehend", phonetic: "/prɪhend/", meaning: "抓住", words: ["comprehend", "apprehend", "reprehend", "comprehensive"] },
  { id: 980, root: "press", phonetic: "/pres/", meaning: "压，挤", words: ["pressure", "express", "impress", "compress", "depress", "suppress"] },
  { id: 981, root: "prim", phonetic: "/prɪm/", meaning: "第一，最初", words: ["primary", "prime", "primitive", "primer", "primordial"] },
  { id: 982, root: "pro", phonetic: "/prəʊ/", meaning: "向前，在前", words: ["progress", "project", "propose", "promote", "prolong"] },
  { id: 983, root: "prob", phonetic: "/prɒb/", meaning: "测试，证明", words: ["prove", "proof", "probable", "approve", "reprove"] },
  { id: 984, root: "proper", phonetic: "/prɒpər/", meaning: "自己的，财产", words: ["property", "proper", "expropriate", "proprietor"] },
  { id: 985, root: "psych", phonetic: "/saɪk/", meaning: "心理，精神", words: ["psychology", "psychiatrist", "psychic", "psychoanalysis"] },
  { id: 986, root: "pugn", phonetic: "/pʌgn/", meaning: "打斗", words: ["pugnacious", "impugn", "repugnant", "expugnable"] },
  { id: 987, root: "pur", phonetic: "/pjʊər/", meaning: "纯，清", words: ["pure", "purify", "purity", "impure", "purge"] },
  { id: 988, root: "put", phonetic: "/pjuːt/", meaning: "思考，计算", words: ["computer", "dispute", "repute", "deputy", "impute"] },
  { id: 989, root: "quer", phonetic: "/kwɪər/", meaning: "寻求，问", words: ["question", "inquiry", "conquer", "query", "quest"] },
  { id: 990, root: "qui", phonetic: "/kwaɪ/", meaning: "安静", words: ["quiet", "acquiesce", "quiescent", "tranquil", "disquiet"] },
  { id: 991, root: "radi", phonetic: "/reɪdi/", meaning: "根，射线", words: ["radio", "radiate", "radical", "eradicate", "radius"] },
  { id: 992, root: "ram", phonetic: "/ræm/", meaning: "支，分支", words: ["branch", "ramify", "ramification"] },
  { id: 993, root: "rat", phonetic: "/ræt/", meaning: "计算，推理", words: ["ratio", "rate", "rational", "irrational"] },
  { id: 994, root: "rect", phonetic: "/rekt/", meaning: "正，直", words: ["correct", "direct", "erect", "rectangle", "rectify"] },
  { id: 995, root: "reg", phonetic: "/reg/", meaning: "统治，直", words: ["regulate", "region", "regular", "correct", "direct", "erect"] },
  { id: 996, root: "rid", phonetic: "/rɪd/", meaning: "笑", words: ["ridiculous", "deride", "ridicule", "risible"] },
  { id: 997, root: "rupt", phonetic: "/rʌpt/", meaning: "打破，断裂", words: ["interrupt", "disrupt", "abrupt", "erupt", "bankrupt", "corrupt"] },
  { id: 998, root: "sacr", phonetic: "/seɪkr/", meaning: "神圣", words: ["sacred", "sacrifice", "sacrilege", "consecrate", "sacrament"] },
  { id: 999, root: "sal", phonetic: "/sæl/", meaning: "盐，跳", words: ["salary", "salad", "salient", "resilient", "assail"] },
  { id: 1000, root: "san", phonetic: "/sæn/", meaning: "健康，神圣", words: ["sanitary", "sanity", "sanction", "insane", "sanitize"] }
];

function buildEntry(rootData, index) {
  const posList = ["n.", "v.", "adj.", "adv."];
  const words = rootData.words.map((word, i) => ({
    word: word,
    phonetic: rootData.phonetic,
    partOfSpeech: posList[i % 4],
    meaning: `${rootData.meaning}相关词${i + 1}`,
    memoryTip: `${word}包含词根${rootData.root}，表示'${rootData.meaning}'`,
    root: rootData.root,
    rootPhonetic: rootData.phonetic,
    rootMeaning: rootData.meaning,
    rootPhrases: [`${rootData.root}_phrase1`, `${rootData.root}_phrase2`, `${rootData.root}_phrase3`, `${rootData.root}_phrase4`],
    wordPhrases: [`${word}_example1`, `${word}_example2`, `${word}_example3`, `${word}_example4`]
  }));

  return {
    id: rootData.id,
    root: rootData.root,
    phonetic: rootData.phonetic,
    partOfSpeech: "词根",
    meaning: rootData.meaning,
    frequency: index + 1,
    category: "四级",
    words: words,
    phrases: [`${rootData.root}_phrase1 (待翻译)`, `${rootData.root}_phrase2 (待翻译)`, `${rootData.root}_phrase3 (待翻译)`, `${rootData.root}_phrase4 (待翻译)`],
    mnemonic: `${rootData.root}→${rootData.meaning}`
  };
}

const filePath = path.join(__dirname, 'src', 'data', 'cet-4.json');
console.log('Reading file:', filePath);

const fileContent = fs.readFileSync(filePath, 'utf-8');
let data;
try {
  data = JSON.parse(fileContent);
} catch (e) {
  console.error('JSON parse error:', e.message);
  process.exit(1);
}

console.log('Original entries:', data.length);

const newEntries = newRoots.map((rootData, index) => buildEntry(rootData, index));
data.push(...newEntries);

fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf-8');

console.log('Successfully added', newEntries.length, 'new root entries');
console.log('ID range:', newEntries[0].id, '-', newEntries[newEntries.length - 1].id);
console.log('Total entries:', data.length);
