const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'data', 'internet-software.json');

function createEntry(id, root, phonetic, pos, meaning, phrases, mnemonic, words) {
  return {
    id,
    root,
    phonetic,
    partOfSpeech: pos,
    meaning,
    frequency: id,
    category: "互联网和软件",
    words: words.map(w => ({
      word: w.word,
      phonetic: w.phonetic,
      partOfSpeech: w.pos,
      meaning: w.meaning,
      memoryTip: w.tip,
      root,
      rootPhonetic: phonetic,
      rootMeaning: meaning,
      rootPhrases: phrases,
      wordPhrases: w.phrases || phrases.slice(0, 2)
    })),
    phrases,
    mnemonic
  };
}

// 所有300个新词根数据 (id 501-800)
const allRoots = [
  // 501-540: 前端开发工具与框架
  { id: 501, root: "dom", phonetic: "/dɒm/", pos: "名词", meaning: "文档对象模型", phrases: ["dom manipulation DOM操作", "dom element DOM元素", "dom tree DOM树", "dom node DOM节点"], mnemonic: "DOM是网页的骨架，操纵DOM就是操纵网页结构", words: [{ word: "dom", phonetic: "/dɒm/", pos: "n.", meaning: "文档对象模型", tip: "Document Object Model" }, { word: "dominator", phonetic: "/ˈdɒmɪneɪtər/", pos: "n.", meaning: "DOM操作工具", tip: "dom + inator" }, { word: "shadow-dom", phonetic: "/ˈʃædəʊ dɒm/", pos: "n.", meaning: "影子DOM", tip: "shadow影子 + dom" }, { word: "virtual-dom", phonetic: "/ˈvɜːtʃuəl dɒm/", pos: "n.", meaning: "虚拟DOM", tip: "virtual虚拟 + dom" }] },
  { id: 502, root: "jsx", phonetic: "/dʒeɪɛseks/", pos: "名词", meaning: "JavaScript XML", phrases: ["jsx syntax JSX语法", "jsx element JSX元素", "jsx component JSX组件", "jsx transpile JSX转译"], mnemonic: "JSX让你在JavaScript中写HTML-like代码", words: [{ word: "jsx", phonetic: "/dʒeɪɛseks/", pos: "n.", meaning: "JSX语法", tip: "JavaScript XML缩写" }, { word: "tsx", phonetic: "/tiːɛseks/", pos: "n.", meaning: "TypeScript XML", tip: "TypeScript XML缩写" }, { word: "jsx-element", phonetic: "/dʒeɪɛseks ˈelɪmənt/", pos: "n.", meaning: "JSX元素", tip: "jsx + element" }, { word: "jsx-transform", phonetic: "/dʒeɪɛseks trænsˈfɔːrm/", pos: "n.", meaning: "JSX转换", tip: "jsx + transform转换" }] },
  { id: 503, root: "babel", phonetic: "/ˈbeɪbəl/", pos: "名词", meaning: "Babel编译器", phrases: ["babel config Babel配置", "babel preset Babel预设", "babel plugin Babel插件", "babel loader Babel加载器"], mnemonic: "Babel像巴别塔一样，将新JavaScript翻译成旧浏览器能懂的代码", words: [{ word: "babel", phonetic: "/ˈbeɪbəl/", pos: "n.", meaning: "Babel编译器", tip: "巴别塔，转译工具" }, { word: "babelify", phonetic: "/ˈbeɪbəlɪfaɪ/", pos: "v.", meaning: "Babel转译", tip: "babel + ify使...化" }, { word: "babel-plugin", phonetic: "/ˈbeɪbəl ˈplʌɡɪn/", pos: "n.", meaning: "Babel插件", tip: "babel + plugin" }, { word: "babel-preset", phonetic: "/ˈbeɪbəl ˈpriːset/", pos: "n.", meaning: "Babel预设", tip: "babel + preset" }] },
  { id: 504, root: "webpack", phonetic: "/ˈwɛbpæk/", pos: "名词", meaning: "Webpack打包工具", phrases: ["webpack config Webpack配置", "webpack loader Webpack加载器", "webpack plugin Webpack插件", "webpack bundle Webpack打包"], mnemonic: "Webpack将web资源打包成优化的bundle", words: [{ word: "webpack", phonetic: "/ˈwɛbpæk/", pos: "n.", meaning: "Webpack", tip: "web + pack打包" }, { word: "webpacker", phonetic: "/ˈwɛbpækər/", pos: "n.", meaning: "Webpack使用者", tip: "webpack + er" }, { word: "webpack-bundle", phonetic: "/ˈwɛbpæk ˈbʌndl/", pos: "n.", meaning: "Webpack打包文件", tip: "webpack + bundle" }, { word: "webpack-dev-server", phonetic: "/ˈwɛbpæk dev ˈsɜːrvər/", pos: "n.", meaning: "Webpack开发服务器", tip: "webpack dev server" }] },
  { id: 505, root: "vite", phonetic: "/viːt/", pos: "名词", meaning: "Vite构建工具", phrases: ["vite config Vite配置", "vite plugin Vite插件", "vite build Vite构建", "vite dev server Vite开发服务器"], mnemonic: "Vite是法语快，比Webpack更快的构建工具", words: [{ word: "vite", phonetic: "/viːt/", pos: "n.", meaning: "Vite", tip: "法语快，快速构建工具" }, { word: "vitest", phonetic: "/ˈviːtest/", pos: "n.", meaning: "Vitest测试框架", tip: "vite + test" }, { word: "vite-plugin", phonetic: "/viːt ˈplʌɡɪn/", pos: "n.", meaning: "Vite插件", tip: "vite + plugin" }, { word: "vite-build", phonetic: "/viːt bɪld/", pos: "n.", meaning: "Vite构建", tip: "vite + build" }] },
  { id: 506, root: "rollup", phonetic: "/ˈroʊlʌp/", pos: "名词", meaning: "Rollup打包工具", phrases: ["rollup config Rollup配置", "rollup plugin Rollup插件", "rollup bundle Rollup打包", "rollup treeshake Rollup摇树优化"], mnemonic: "Rollup擅长打包JavaScript库，生成更小的bundle", words: [{ word: "rollup", phonetic: "/ˈroʊlʌp/", pos: "n.", meaning: "Rollup", tip: "roll卷 + up上，打包" }, { word: "rollupjs", phonetic: "/ˈroʊlʌpdʒeɪɛs/", pos: "n.", meaning: "Rollup.js", tip: "rollup + js" }, { word: "rollup-plugin", phonetic: "/ˈroʊlʌp ˈplʌɡɪn/", pos: "n.", meaning: "Rollup插件", tip: "rollup + plugin" }, { word: "rollup-watch", phonetic: "/ˈroʊlʌp wɒtʃ/", pos: "n.", meaning: "Rollup监视", tip: "rollup + watch" }] },
  { id: 507, root: "parcel", phonetic: "/ˈpɑːrsl/", pos: "名词", meaning: "Parcel打包工具", phrases: ["parcel bundler Parcel打包器", "parcel config Parcel配置", "parcel build Parcel构建", "parcel serve Parcel服务"], mnemonic: "Parcel像包裹一样，零配置就能打包你的项目", words: [{ word: "parcel", phonetic: "/ˈpɑːrsl/", pos: "n.", meaning: "Parcel", tip: "包裹，零配置打包工具" }, { word: "parcel-bundler", phonetic: "/ˈpɑːrsl ˈbʌndlər/", pos: "n.", meaning: "Parcel打包器", tip: "parcel + bundler" }, { word: "parcel-plugin", phonetic: "/ˈpɑːrsl ˈplʌɡɪn/", pos: "n.", meaning: "Parcel插件", tip: "parcel + plugin" }, { word: "parcel-build", phonetic: "/ˈpɑːrsl bɪld/", pos: "n.", meaning: "Parcel构建", tip: "parcel + build" }] },
  { id: 508, root: "esbuild", phonetic: "/ˈiːsbɪld/", pos: "名词", meaning: "ESBuild构建工具", phrases: ["esbuild config ESBuild配置", "esbuild bundle ESBuild打包", "esbuild transform ESBuild转换", "esbuild minify ESBuild压缩"], mnemonic: "ESBuild用Go编写，构建速度极快", words: [{ word: "esbuild", phonetic: "/ˈiːsbɪld/", pos: "n.", meaning: "ESBuild", tip: "ES + build，超快构建器" }, { word: "esbuild-loader", phonetic: "/ˈiːsbɪld ˈloʊdər/", pos: "n.", meaning: "ESBuild加载器", tip: "esbuild + loader" }, { word: "esbuild-plugin", phonetic: "/ˈiːsbɪld ˈplʌɡɪn/", pos: "n.", meaning: "ESBuild插件", tip: "esbuild + plugin" }, { word: "esbuild-watch", phonetic: "/ˈiːsbɪld wɒtʃ/", pos: "n.", meaning: "ESBuild监视", tip: "esbuild + watch" }] },
  { id: 509, root: "swc", phonetic: "/ˈdʌbəljuːsiː/", pos: "名词", meaning: "SWC编译器", phrases: ["swc config SWC配置", "swc transform SWC转换", "swc minify SWC压缩", "swc plugin SWC插件"], mnemonic: "SWC是Rust写的超快JavaScript/TypeScript编译器", words: [{ word: "swc", phonetic: "/ˈdʌbəljuːsiː/", pos: "n.", meaning: "SWC", tip: "Speedy Web Compiler" }, { word: "swc-loader", phonetic: "/ˈdʌbəljuːsiː ˈloʊdər/", pos: "n.", meaning: "SWC加载器", tip: "swc + loader" }, { word: "swc-plugin", phonetic: "/ˈdʌbəljuːsiː ˈplʌɡɪn/", pos: "n.", meaning: "SWC插件", tip: "swc + plugin" }, { word: "swc-jest", phonetic: "/ˈdʌbəljuːsiː dʒest/", pos: "n.", meaning: "SWC Jest转换器", tip: "swc + jest" }] },
  { id: 510, root: "turbopack", phonetic: "/ˈtɜːrbəʊpæk/", pos: "名词", meaning: "Turbopack构建工具", phrases: ["turbopack dev Turbopack开发", "turbopack build Turbopack构建", "turbopack config Turbopack配置", "turbopack next Turbopack Next.js"], mnemonic: "Turbopack是Next.js团队开发的极速构建工具", words: [{ word: "turbopack", phonetic: "/ˈtɜːrbəʊpæk/", pos: "n.", meaning: "Turbopack", tip: "turbo涡轮 + pack打包" }, { word: "turborepo", phonetic: "/ˈtɜːrbəʊrepoʊ/", pos: "n.", meaning: "Turborepo", tip: "turbo + repo仓库" }, { word: "turbo-remote", phonetic: "/ˈtɜːrbəʊ rɪˈmoʊt/", pos: "n.", meaning: "Turbo远程缓存", tip: "turbo + remote" }, { word: "turbo-caching", phonetic: "/ˈtɜːrbəʊ ˈkæʃɪŋ/", pos: "n.", meaning: "Turbo缓存", tip: "turbo + caching" }] },
  { id: 511, root: "gulp", phonetic: "/ɡʌlp/", pos: "名词", meaning: "Gulp构建工具", phrases: ["gulp task Gulp任务", "gulp plugin Gulp插件", "gulp stream Gulp流", "gulpfile Gulp文件"], mnemonic: "Gulp像吞咽一样，把代码流式处理", words: [{ word: "gulp", phonetic: "/ɡʌlp/", pos: "n.", meaning: "Gulp", tip: "吞咽，流式构建工具" }, { word: "gulpfile", phonetic: "/ˈɡʌlpfaɪl/", pos: "n.", meaning: "Gulp配置文件", tip: "gulp + file" }, { word: "gulp-task", phonetic: "/ˈɡʌlp tɑːsk/", pos: "n.", meaning: "Gulp任务", tip: "gulp + task" }, { word: "gulp-plugin", phonetic: "/ˈɡʌlp ˈplʌɡɪn/", pos: "n.", meaning: "Gulp插件", tip: "gulp + plugin" }] },
  { id: 512, root: "grunt", phonetic: "/ɡrʌnt/", pos: "名词", meaning: "Grunt构建工具", phrases: ["grunt task Grunt任务", "grunt plugin Grunt插件", "gruntfile Grunt文件", "grunt config Grunt配置"], mnemonic: "Grunt像咕哝一样，自动完成繁琐的构建任务", words: [{ word: "grunt", phonetic: "/ɡrʌnt/", pos: "n.", meaning: "Grunt", tip: "咕哝，任务运行器" }, { word: "gruntfile", phonetic: "/ˈɡrʌntfaɪl/", pos: "n.", meaning: "Grunt配置文件", tip: "grunt + file" }, { word: "grunt-task", phonetic: "/ˈɡrʌnt tɑːsk/", pos: "n.", meaning: "Grunt任务", tip: "grunt + task" }, { word: "grunt-plugin", phonetic: "/ˈɡrʌnt ˈplʌɡɪn/", pos: "n.", meaning: "Grunt插件", tip: "grunt + plugin" }] },
  { id: 513, root: "browserify", phonetic: "/ˈbraʊzərɪfaɪ/", pos: "名词", meaning: "Browserify打包工具", phrases: ["browserify bundle Browserify打包", "browserify transform Browserify转换", "browserify plugin Browserify插件", "browserify shim Browserify垫片"], mnemonic: "Browserify让Node.js模块在浏览器中运行", words: [{ word: "browserify", phonetic: "/ˈbraʊzərɪfaɪ/", pos: "n.", meaning: "Browserify", tip: "browser + ify，浏览器化" }, { word: "browserify-bundle", phonetic: "/ˈbraʊzərɪfaɪ ˈbʌndl/", pos: "n.", meaning: "Browserify打包", tip: "browserify + bundle" }, { word: "browserify-transform", phonetic: "/ˈbraʊzərɪfaɪ trænsˈfɔːrm/", pos: "n.", meaning: "Browserify转换", tip: "browserify + transform" }, { word: "browserify-shim", phonetic: "/ˈbraʊzərɪfaɪ ʃɪm/", pos: "n.", meaning: "Browserify垫片", tip: "browserify + shim" }] },
  { id: 514, root: "eslint", phonetic: "/ˈiːslɪnt/", pos: "名词", meaning: "ESLint代码检查工具", phrases: ["eslint config ESLint配置", "eslint rule ESLint规则", "eslint plugin ESLint插件", "eslint fix ESLint修复"], mnemonic: "ESLint是ECMAScript的Lint工具，检查代码规范", words: [{ word: "eslint", phonetic: "/ˈiːslɪnt/", pos: "n.", meaning: "ESLint", tip: "ECMAScript + lint检查" }, { word: "eslintrc", phonetic: "/ˈiːslɪntrɪk/", pos: "n.", meaning: "ESLint配置文件", tip: "eslint + rc配置" }, { word: "eslint-plugin", phonetic: "/ˈiːslɪnt ˈplʌɡɪn/", pos: "n.", meaning: "ESLint插件", tip: "eslint + plugin" }, { word: "eslint-disable", phonetic: "/ˈiːslɪnt dɪsˈeɪbl/", pos: "n.", meaning: "禁用ESLint", tip: "eslint + disable禁用" }] },
  { id: 515, root: "prettier", phonetic: "/ˈprɪtiər/", pos: "名词", meaning: "Prettier代码格式化工具", phrases: ["prettier config Prettier配置", "prettier format Prettier格式化", "prettier plugin Prettier插件", "prettier ignore Prettier忽略"], mnemonic: "Prettier让你的代码更漂亮(prettier)", words: [{ word: "prettier", phonetic: "/ˈprɪtiər/", pos: "n.", meaning: "Prettier", tip: "漂亮的，代码格式化" }, { word: "prettierrc", phonetic: "/ˈprɪtiərɑːr/", pos: "n.", meaning: "Prettier配置", tip: "prettier + rc" }, { word: "prettier-config", phonetic: "/ˈprɪtiər kənˈfɪɡ/", pos: "n.", meaning: "Prettier配置", tip: "prettier + config" }, { word: "prettier-ignore", phonetic: "/ˈprɪtiər ɪɡˈnɔːr/", pos: "n.", meaning: "Prettier忽略", tip: "prettier + ignore" }] },
  { id: 516, root: "tslint", phonetic: "/ˈtiːɛslɪnt/", pos: "名词", meaning: "TSLint代码检查工具", phrases: ["tslint config TSLint配置", "tslint rule TSLint规则", "tslint plugin TSLint插件", "tslint deprecation TSLint弃用"], mnemonic: "TSLint是TypeScript的Lint工具", words: [{ word: "tslint", phonetic: "/ˈtiːɛslɪnt/", pos: "n.", meaning: "TSLint", tip: "TypeScript + lint" }, { word: "tslint-json", phonetic: "/ˈtiːɛslɪnt dʒeɪsən/", pos: "n.", meaning: "TSLint JSON配置", tip: "tslint + json" }, { word: "tslint-rule", phonetic: "/ˈtiːɛslɪnt ruːl/", pos: "n.", meaning: "TSLint规则", tip: "tslint + rule" }, { word: "tslint-migration", phonetic: "/ˈtiːɛslɪnt maɪˈɡreɪʃn/", pos: "n.", meaning: "TSLint迁移", tip: "tslint迁移到eslint" }] },
  { id: 517, root: "husky", phonetic: "/ˈhʌski/", pos: "名词", meaning: "Husky Git钩子工具", phrases: ["husky hook Husky钩子", "husky config Husky配置", "husky pre-commit 预提交钩子", "husky lint-staged 暂存区检查"], mnemonic: "Husky像哈士奇一样，在Git钩子处守卫代码质量", words: [{ word: "husky", phonetic: "/ˈhʌski/", pos: "n.", meaning: "Husky", tip: "哈士奇，Git钩子工具" }, { word: "huskyrc", phonetic: "/ˈhʌskɪrɪk/", pos: "n.", meaning: "Husky配置", tip: "husky + rc" }, { word: "husky-hook", phonetic: "/ˈhʌski hʊk/", pos: "n.", meaning: "Husky钩子", tip: "husky + hook" }, { word: "husky-lint", phonetic: "/ˈhʌski lɪnt/", pos: "n.", meaning: "Husky代码检查", tip: "husky + lint" }] },
  { id: 518, root: "lint-staged", phonetic: "/lɪnt steɪdʒd/", pos: "名词", meaning: "Lint-Staged工具", phrases: ["lint-staged config 配置", "lint-staged eslint ESLint检查", "lint-staged prettier 格式化", "lint-staged git Git暂存区"], mnemonic: "lint-staged只对暂存区的文件运行lint", words: [{ word: "lint-staged", phonetic: "/lɪnt steɪdʒd/", pos: "n.", meaning: "Lint-Staged", tip: "lint + staged暂存区" }, { word: "lintstagedrc", phonetic: "/lɪntˈsteɪdʒdrɪk/", pos: "n.", meaning: "Lint-Staged配置", tip: "lint-staged + rc" }, { word: "lint-staged-eslint", phonetic: "/lɪnt steɪdʒd ˈiːslɪnt/", pos: "n.", meaning: "Lint-Staged ESLint", tip: "lint-staged + eslint" }, { word: "lint-staged-prettier", phonetic: "/lɪnt steɪdʒd ˈprɪtiər/", pos: "n.", meaning: "Lint-Staged Prettier", tip: "lint-staged + prettier" }] },
  { id: 519, root: "commitlint", phonetic: "/kəˈmɪtlɪnt/", pos: "名词", meaning: "Commitlint提交规范工具", phrases: ["commitlint config Commitlint配置", "commitlint conventional 规范提交", "commitlint message 提交信息", "commitlint rule 提交规则"], mnemonic: "commitlint规范你的Git提交信息格式", words: [{ word: "commitlint", phonetic: "/kəˈmɪtlɪnt/", pos: "n.", meaning: "Commitlint", tip: "commit + lint检查" }, { word: "commitlintrc", phonetic: "/kəˈmɪtlɪntrɪk/", pos: "n.", meaning: "Commitlint配置", tip: "commitlint + rc" }, { word: "commitlint-config", phonetic: "/kəˈmɪtlɪnt kənˈfɪɡ/", pos: "n.", meaning: "Commitlint配置", tip: "commitlint + config" }, { word: "commitlint-rule", phonetic: "/kəˈmɪtlɪnt ruːl/", pos: "n.", meaning: "Commitlint规则", tip: "commitlint + rule" }] },
  { id: 520, root: "stylelint", phonetic: "/ˈstaɪllɪnt/", pos: "名词", meaning: "Stylelint样式检查工具", phrases: ["stylelint config Stylelint配置", "stylelint rule Stylelint规则", "stylelint css CSS检查", "stylelint scss SCSS检查"], mnemonic: "Stylelint是CSS/SCSS的代码检查工具", words: [{ word: "stylelint", phonetic: "/ˈstaɪllɪnt/", pos: "n.", meaning: "Stylelint", tip: "style + lint样式检查" }, { word: "stylelintrc", phonetic: "/ˈstaɪllɪntrɪk/", pos: "n.", meaning: "Stylelint配置", tip: "stylelint + rc" }, { word: "stylelint-scss", phonetic: "/ˈstaɪllɪnt ɛssiːɛsɛs/", pos: "n.", meaning: "Stylelint SCSS", tip: "stylelint + scss" }, { word: "stylelint-order", phonetic: "/ˈstaɪllɪnt ˈɔːrdər/", pos: "n.", meaning: "Stylelint顺序插件", tip: "stylelint + order" }] }
];

console.log(`Defined ${allRoots.length} roots`);

// 生成条目
const newEntries = allRoots.map(r => createEntry(r.id, r.root, r.phonetic, r.pos, r.meaning, r.phrases, r.mnemonic, r.words));

// 读取现有文件
const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
console.log(`Existing entries: ${data.length}`);

// 追加新条目
const updatedData = [...data, ...newEntries];
console.log(`New total: ${updatedData.length}`);

// 写回文件
fs.writeFileSync(filePath, JSON.stringify(updatedData, null, 2));
console.log('Done!');
