const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'src', 'data', 'internet-software.json');

function createEntry(id, root, phonetic, pos, meaning, phrases, mnemonic, words) {
  return {
    id, root, phonetic, partOfSpeech: pos, meaning, frequency: id, category: "互联网和软件",
    words: words.map(w => ({ word: w.word, phonetic: w.phonetic, partOfSpeech: w.pos, meaning: w.meaning, memoryTip: w.tip, root, rootPhonetic: phonetic, rootMeaning: meaning, rootPhrases: phrases, wordPhrases: w.phrases || phrases.slice(0, 2) })),
    phrases, mnemonic
  };
}

// 621-720: 云服务、监控与网络
const allRoots = [
  // 云服务 (621-640)
  { id: 621, root: "aws", phonetic: "/eɪdʌbəljuːˈɛs/", pos: "名词", meaning: "亚马逊云服务", phrases: ["aws ec2 AWS EC2", "aws s3 AWS S3", "aws lambda AWS Lambda", "aws rds AWS RDS"], mnemonic: "AWS是云计算市场的领导者", words: [{ word: "aws", phonetic: "/eɪdʌbəljuːˈɛs/", pos: "n.", meaning: "AWS", tip: "Amazon Web Services" }, { word: "ec2", phonetic: "/iːsiːtuː/", pos: "n.", meaning: "EC2", tip: "Elastic Compute Cloud" }, { word: "s3", phonetic: "/ɛsθriː/", pos: "n.", meaning: "S3", tip: "Simple Storage Service" }, { word: "lambda", phonetic: "/ˈlæmdə/", pos: "n.", meaning: "Lambda", tip: "无服务器计算" }] },
  { id: 622, root: "azure", phonetic: "/ˈæʒər/", pos: "名词", meaning: "微软云服务", phrases: ["azure vm Azure虚拟机", "azure storage Azure存储", "azure function Azure函数", "azure devops Azure DevOps"], mnemonic: "Azure是微软的云计算平台", words: [{ word: "azure", phonetic: "/ˈæʒər/", pos: "n.", meaning: "Azure", tip: "天蓝色，微软云" }, { word: "azure-app", phonetic: "/ˈæʒər æp/", pos: "n.", meaning: "Azure App", tip: "azure + app" }, { word: "azure-sql", phonetic: "/ˈæʒər ɛskjuːɛl/", pos: "n.", meaning: "Azure SQL", tip: "azure + sql" }, { word: "azure-cli", phonetic: "/ˈæʒər siːɛlaɪ/", pos: "n.", meaning: "Azure CLI", tip: "azure + cli" }] },
  { id: 623, root: "gcp", phonetic: "/dʒiːsiːpiː/", pos: "名词", meaning: "谷歌云平台", phrases: ["gcp compute GCP计算", "gcp storage GCP存储", "gcp cloud-run Cloud Run", "gcp bigquery BigQuery"], mnemonic: "GCP是Google的云计算平台", words: [{ word: "gcp", phonetic: "/dʒiːsiːpiː/", pos: "n.", meaning: "GCP", tip: "Google Cloud Platform" }, { word: "google-cloud", phonetic: "/ˈɡuːɡl klaʊd/", pos: "n.", meaning: "Google Cloud", tip: "google + cloud" }, { word: "bigquery", phonetic: "/bɪɡˈkwɪəri/", pos: "n.", meaning: "BigQuery", tip: "big + query" }, { word: "firebase", phonetic: "/ˈfaɪərbɛs/", pos: "n.", meaning: "Firebase", tip: "Google移动平台" }] },
  { id: 624, root: "heroku", phonetic: "/ˈhɛroʊkuː/", pos: "名词", meaning: "Heroku平台", phrases: ["heroku app Heroku应用", "heroku dyno Heroku容器", "heroku addon Heroku插件", "heroku cli Heroku CLI"], mnemonic: "Heroku是最早的PaaS平台之一", words: [{ word: "heroku", phonetic: "/ˈhɛroʊkuː/", pos: "n.", meaning: "Heroku", tip: "Hero英雄 + ku，PaaS" }, { word: "heroku-app", phonetic: "/ˈhɛroʊkuː æp/", pos: "n.", meaning: "Heroku App", tip: "heroku + app" }, { word: "dyno", phonetic: "/ˈdaɪnoʊ/", pos: "n.", meaning: "Dyno", tip: "Heroku容器单元" }, { word: "heroku-postgres", phonetic: "/ˈhɛroʊkuː poʊstɡrɛs/", pos: "n.", meaning: "Heroku Postgres", tip: "heroku + postgres" }] },
  { id: 625, root: "netlify", phonetic: "/ˈnɛtlɪfaɪ/", pos: "名词", meaning: "Netlify托管平台", phrases: ["netlify deploy Netlify部署", "netlify function Netlify函数", "netlify form Netlify表单", "netlify edge Netlify边缘"], mnemonic: "Netlify是静态网站托管和Serverless平台", words: [{ word: "netlify", phonetic: "/ˈnɛtlɪfaɪ/", pos: "n.", meaning: "Netlify", tip: "net + lify，托管平台" }, { word: "netlify-cdn", phonetic: "/ˈnɛtlɪfaɪ siːdiːɛn/", pos: "n.", meaning: "Netlify CDN", tip: "netlify + cdn" }, { word: "netlify-dev", phonetic: "/ˈnɛtlɪfaɪ dɛv/", pos: "n.", meaning: "Netlify Dev", tip: "netlify + dev" }, { word: "netlify-cli", phonetic: "/ˈnɛtlɪfaɪ siːɛlaɪ/", pos: "n.", meaning: "Netlify CLI", tip: "netlify + cli" }] },
  { id: 626, root: "vercel", phonetic: "/ˈvɜːrsəl/", pos: "名词", meaning: "Vercel部署平台", phrases: ["vercel deploy Vercel部署", "vercel edge Vercel边缘", "vercel function Vercel函数", "vercel next Vercel Next.js"], mnemonic: "Vercel是Next.js的创建者，专注于前端部署", words: [{ word: "vercel", phonetic: "/ˈvɜːrsəl/", pos: "n.", meaning: "Vercel", tip: "Vercel，前端部署" }, { word: "vercel-json", phonetic: "/ˈvɜːrsəl dʒeɪsən/", pos: "n.", meaning: "vercel.json", tip: "Vercel配置" }, { word: "vercel-cli", phonetic: "/ˈvɜːrsəl siːɛlaɪ/", pos: "n.", meaning: "Vercel CLI", tip: "vercel + cli" }, { word: "vercel-edge", phonetic: "/ˈvɜːrsəl ɛdʒ/", pos: "n.", meaning: "Vercel Edge", tip: "vercel + edge" }] },
  { id: 627, root: "cloudflare", phonetic: "/ˈklaʊdfler/", pos: "名词", meaning: "Cloudflare CDN", phrases: ["cloudflare cdn Cloudflare CDN", "cloudflare workers Cloudflare Workers", "cloudflare pages Cloudflare Pages", "cloudflare dns Cloudflare DNS"], mnemonic: "Cloudflare是领先的CDN和边缘计算平台", words: [{ word: "cloudflare", phonetic: "/ˈklaʊdfler/", pos: "n.", meaning: "Cloudflare", tip: "cloud + flare，CDN" }, { word: "cloudflare-worker", phonetic: "/ˈklaʊdfler ˈwɜːrkər/", pos: "n.", meaning: "Cloudflare Worker", tip: "cloudflare + worker" }, { word: "cloudflare-pages", phonetic: "/ˈklaʊdfler peɪdʒɪz/", pos: "n.", meaning: "Cloudflare Pages", tip: "cloudflare + pages" }, { word: "cloudflare-r2", phonetic: "/ˈklaʊdfler ɑːr tuː/", pos: "n.", meaning: "Cloudflare R2", tip: "cloudflare + r2" }] },
  { id: 628, root: "digitalocean", phonetic: "/ˈdɪdʒɪtl ˈoʊʃn/", pos: "名词", meaning: "DigitalOcean云", phrases: ["digitalocean droplet DO droplet", "digitalocean spaces DO Spaces", "digitalocean k8s DO K8s", "digitalocean db DO数据库"], mnemonic: "DigitalOcean是开发者友好的云服务商", words: [{ word: "digitalocean", phonetic: "/ˈdɪdʒɪtl ˈoʊʃn/", pos: "n.", meaning: "DigitalOcean", tip: "digital + ocean" }, { word: "droplet", phonetic: "/ˈdrɒplət/", pos: "n.", meaning: "Droplet", tip: "小水滴，DO虚拟机" }, { word: "doctl", phonetic: "/diːoʊsiːtiːɛl/", pos: "n.", meaning: "doctl", tip: "DO命令行" }, { word: "spaces", phonetic: "/ˈspeɪsɪz/", pos: "n.", meaning: "Spaces", tip: "DO对象存储" }] },
  { id: 629, root: "linode", phonetic: "/ˈlɪnoʊd/", pos: "名词", meaning: "Linode云服务器", phrases: ["linode instance Linode实例", "linode block Linode块存储", "linode k8s Linode K8s", "linode cli Linode CLI"], mnemonic: "Linode是老牌VPS和云服务商", words: [{ word: "linode", phonetic: "/ˈlɪnoʊd/", pos: "n.", meaning: "Linode", tip: "Linux + node，VPS" }, { word: "linode-cli", phonetic: "/ˈlɪnoʊd siːɛlaɪ/", pos: "n.", meaning: "Linode CLI", tip: "linode + cli" }, { word: "akamai", phonetic: "/ɑːˈkɑːmaɪ/", pos: "n.", meaning: "Akamai", tip: "收购Linode的公司" }, { word: "linode-api", phonetic: "/ˈlɪnoʊd eɪpiːaɪ/", pos: "n.", meaning: "Linode API", tip: "linode + api" }] },
  { id: 630, root: "serverless", phonetic: "/ˈsɜːrvərləs/", pos: "名词", meaning: "无服务器架构", phrases: ["serverless function 无服务器函数", "serverless framework Serverless框架", "serverless deploy 无服务器部署", "serverless lambda Lambda"], mnemonic: "Serverless让开发者无需管理服务器", words: [{ word: "serverless", phonetic: "/ˈsɜːrvərləs/", pos: "n.", meaning: "Serverless", tip: "server + less" }, { word: "serverless-framework", phonetic: "/ˈsɜːrvərləs ˈfreɪmwɜːrk/", pos: "n.", meaning: "Serverless Framework", tip: "serverless + framework" }, { word: "faas", phonetic: "/fɑːs/", pos: "n.", meaning: "FaaS", tip: "Function as a Service" }, { word: "baas", phonetic: "/bɑːs/", pos: "n.", meaning: "BaaS", tip: "Backend as a Service" }] },
  // 监控与日志 (631-650)
  { id: 631, root: "prometheus", phonetic: "/prəˈmiːθiəs/", pos: "名词", meaning: "Prometheus监控系统", phrases: ["prometheus metrics Prometheus指标", "prometheus alert Prometheus告警", "prometheus query Prometheus查询", "prometheus exporter Prometheus导出器"], mnemonic: "Prometheus是云原生监控和告警工具包", words: [{ word: "prometheus", phonetic: "/prəˈmiːθiəs/", pos: "n.", meaning: "Prometheus", tip: "普罗米修斯，监控" }, { word: "promql", phonetic: "/prɒmkuːɛl/", pos: "n.", meaning: "PromQL", tip: "Prometheus查询语言" }, { word: "prometheus-operator", phonetic: "/prəˈmiːθiəs ˈɒpəreɪtər/", pos: "n.", meaning: "Prometheus Operator", tip: "prometheus + operator" }, { word: "thanos", phonetic: "/ˈθænɒs/", pos: "n.", meaning: "Thanos", tip: "Prometheus长期存储" }] },
  { id: 632, root: "grafana", phonetic: "/ɡrəˈfɑːnə/", pos: "名词", meaning: "Grafana可视化", phrases: ["grafana dashboard Grafana仪表板", "grafana panel Grafana面板", "grafana alert Grafana告警", "grafana query Grafana查询"], mnemonic: "Grafana是开源的监控分析和可视化平台", words: [{ word: "grafana", phonetic: "/ɡrəˈfɑːnə/", pos: "n.", meaning: "Grafana", tip: "Grafana，可视化" }, { word: "grafana-cloud", phonetic: "/ɡrəˈfɑːnə klaʊd/", pos: "n.", meaning: "Grafana Cloud", tip: "grafana + cloud" }, { word: "loki", phonetic: "/ˈloʊki/", pos: "n.", meaning: "Loki", tip: "Grafana日志聚合" }, { word: "tempo", phonetic: "/ˈtɛmpoʊ/", pos: "n.", meaning: "Tempo", tip: "Grafana分布式追踪" }] },
  { id: 633, root: "datadog", phonetic: "/ˈdeɪtədɒɡ/", pos: "名词", meaning: "Datadog监控", phrases: ["datadog monitor Datadog监控", "datadog apm Datadog APM", "datadog log Datadog日志", "datadog dashboard Datadog仪表板"], mnemonic: "Datadog是云规模监控和分析平台", words: [{ word: "datadog", phonetic: "/ˈdeɪtədɒɡ/", pos: "n.", meaning: "Datadog", tip: "data + dog，监控" }, { word: "datadog-agent", phonetic: "/ˈdeɪtədɒɡ ˈeɪdʒənt/", pos: "n.", meaning: "Datadog Agent", tip: "datadog + agent" }, { word: "datadog-synthetics", phonetic: "/ˈdeɪtədɒɡ sɪnˈθɛtɪks/", pos: "n.", meaning: "Datadog Synthetics", tip: "datadog + synthetics" }, { word: "datadog-rum", phonetic: "/ˈdeɪtədɒɡ rʌm/", pos: "n.", meaning: "Datadog RUM", tip: "datadog + rum" }] },
  { id: 634, root: "newrelic", phonetic: "/njuː ˈrɛlɪk/", pos: "名词", meaning: "New Relic监控", phrases: ["newrelic apm New Relic APM", "newrelic browser New Relic浏览器", "newrelic infra New Relic基础设施", "newrelic insights New Relic洞察"], mnemonic: "New Relic是应用性能监控的先驱", words: [{ word: "newrelic", phonetic: "/njuː ˈrɛlɪk/", pos: "n.", meaning: "New Relic", tip: "new + relic，APM" }, { word: "newrelic-one", phonetic: "/njuː ˈrɛlɪk wʌn/", pos: "n.", meaning: "New Relic One", tip: "newrelic + one" }, { word: "newrelic-nrql", phonetic: "/njuː ˈrɛlɪk ˈnɜːrkuːɛl/", pos: "n.", meaning: "NRQL", tip: "New Relic查询语言" }, { word: "newrelic-agent", phonetic: "/njuː ˈrɛlɪk ˈeɪdʒənt/", pos: "n.", meaning: "New Relic Agent", tip: "newrelic + agent" }] },
  { id: 635, root: "sentry", phonetic: "/ˈsɛntri/", pos: "名词", meaning: "Sentry错误监控", phrases: ["sentry error Sentry错误", "sentry issue Sentry问题", "sentry release Sentry发布", "sentry performance Sentry性能"], mnemonic: "Sentry是实时错误追踪和监控平台", words: [{ word: "sentry", phonetic: "/ˈsɛntri/", pos: "n.", meaning: "Sentry", tip: "哨兵，错误监控" }, { word: "sentry-sdk", phonetic: "/ˈsɛntri ɛssiːdiː/", pos: "n.", meaning: "Sentry SDK", tip: "sentry + sdk" }, { word: "sentry-cli", phonetic: "/ˈsɛntri siːɛlaɪ/", pos: "n.", meaning: "Sentry CLI", tip: "sentry + cli" }, { word: "sentry-dsn", phonetic: "/ˈsɛntri diːɛsɛn/", pos: "n.", meaning: "Sentry DSN", tip: "sentry + dsn" }] },
  { id: 636, root: "elastic", phonetic: "/ɪˈlæstɪk/", pos: "形容词", meaning: "弹性的", phrases: ["elastic stack Elastic Stack", "elastic search Elasticsearch", "elastic cloud Elastic Cloud", "elastic apm Elastic APM"], mnemonic: "Elastic Stack是搜索、观察和保护数据的平台", words: [{ word: "elastic", phonetic: "/ɪˈlæstɪk/", pos: "adj.", meaning: "Elastic", tip: "弹性的" }, { word: "elk-stack", phonetic: "/ɛlk stæk/", pos: "n.", meaning: "ELK Stack", tip: "Elasticsearch Logstash Kibana" }, { word: "beats", phonetic: "/biːts/", pos: "n.", meaning: "Beats", tip: "Elastic数据采集器" }, { word: "elastic-agent", phonetic: "/ɪˈlæstɪk ˈeɪdʒənt/", pos: "n.", meaning: "Elastic Agent", tip: "elastic + agent" }] },
  { id: 637, root: "logstash", phonetic: "/ˈlɒɡstæʃ/", pos: "名词", meaning: "Logstash数据处理", phrases: ["logstash pipeline Logstash管道", "logstash filter Logstash过滤器", "logstash input Logstash输入", "logstash output Logstash输出"], mnemonic: "Logstash是开源的服务器端数据处理管道", words: [{ word: "logstash", phonetic: "/ˈlɒɡstæʃ/", pos: "n.", meaning: "Logstash", tip: "log + stash，日志处理" }, { word: "logstash-forwarder", phonetic: "/ˈlɒɡstæʃ ˈfɔːrwərdər/", pos: "n.", meaning: "Logstash Forwarder", tip: "logstash + forwarder" }, { word: "filebeat", phonetic: "/ˈfaɪlbiːt/", pos: "n.", meaning: "Filebeat", tip: "file + beat，日志收集" }, { word: "logstash-config", phonetic: "/ˈlɒɡstæʃ kənˈfɪɡ/", pos: "n.", meaning: "Logstash配置", tip: "logstash + config" }] },
  { id: 638, root: "fluentd", phonetic: "/ˈfluːəntd/", pos: "名词", meaning: "Fluentd日志收集", phrases: ["fluentd input Fluentd输入", "fluentd output Fluentd输出", "fluentd filter Fluentd过滤", "fluentd buffer Fluentd缓冲"], mnemonic: "Fluentd是统一日志记录层", words: [{ word: "fluentd", phonetic: "/ˈfluːəntd/", pos: "n.", meaning: "Fluentd", tip: "fluent + d，日志收集" }, { word: "fluent-bit", phonetic: "/ˈfluːənt bɪt/", pos: "n.", meaning: "Fluent Bit", tip: "fluent + bit" }, { word: "fluentd-conf", phonetic: "/ˈfluːəntd kɒnf/", pos: "n.", meaning: "fluentd.conf", tip: "fluentd配置" }, { word: "fluent-logger", phonetic: "/ˈfluːənt ˈlɒɡər/", pos: "n.", meaning: "Fluent Logger", tip: "fluent + logger" }] },
  { id: 639, root: "zipkin", phonetic: "/ˈzɪpkɪn/", pos: "名词", meaning: "Zipkin分布式追踪", phrases: ["zipkin trace Zipkin追踪", "zipkin span Zipkin跨度", "zipkin service Zipkin服务", "zipkin annotation Zipkin注解"], mnemonic: "Zipkin是Twitter开源的分布式追踪系统", words: [{ word: "zipkin", phonetic: "/ˈzɪpkɪn/", pos: "n.", meaning: "Zipkin", tip: "Zipkin，分布式追踪" }, { word: "zipkin-ui", phonetic: "/ˈzɪpkɪn juːaɪ/", pos: "n.", meaning: "Zipkin UI", tip: "zipkin + ui" }, { word: "zipkin-server", phonetic: "/ˈzɪpkɪn ˈsɜːrvər/", pos: "n.", meaning: "Zipkin Server", tip: "zipkin + server" }, { word: "zipkin-api", phonetic: "/ˈzɪpkɪn eɪpiːaɪ/", pos: "n.", meaning: "Zipkin API", tip: "zipkin + api" }] },
  { id: 640, root: "jaeger", phonetic: "/ˈjeɪɡər/", pos: "名词", meaning: "Jaeger分布式追踪", phrases: ["jaeger trace Jaeger追踪", "jaeger span Jaeger跨度", "jaeger agent Jaeger代理", "jaeger collector Jaeger收集器"], mnemonic: "Jaeger是Uber开源的分布式追踪系统", words: [{ word: "jaeger", phonetic: "/ˈjeɪɡər/", pos: "n.", meaning: "Jaeger", tip: "德语猎人，追踪系统" }, { word: "jaeger-ui", phonetic: "/ˈjeɪɡər juːaɪ/", pos: "n.", meaning: "Jaeger UI", tip: "jaeger + ui" }, { word: "jaeger-client", phonetic: "/ˈjeɪɡər ˈklaɪənt/", pos: "n.", meaning: "Jaeger Client", tip: "jaeger + client" }, { word: "jaeger-operator", phonetic: "/ˈjeɪɡər ˈɒpəreɪtər/", pos: "n.", meaning: "Jaeger Operator", tip: "jaeger + operator" }] }
];

console.log(`Adding ${allRoots.length} entries (621-640)`);

const newEntries = allRoots.map(r => createEntry(r.id, r.root, r.phonetic, r.pos, r.meaning, r.phrases, r.mnemonic, r.words));

const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
console.log(`Current: ${data.length}`);

const updatedData = [...data, ...newEntries];
console.log(`New total: ${updatedData.length}`);

fs.writeFileSync(filePath, JSON.stringify(updatedData, null, 2));
console.log('Batch 7 (part 1) done!');
