const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'src', 'data', 'internet-software.json');

function createEntry(id, root, phonetic, pos, meaning, phrases, mnemonic, words) {
  return {
    id, root, phonetic, partOfSpeech: pos, meaning, frequency: id, category: "互联网和软件",
    words: words.map(w => ({ word: w.word, phonetic: w.phonetic, partOfSpeech: w.pos, meaning: w.meaning, memoryTip: w.tip, root, rootPhonetic: phonetic, rootMeaning: meaning, rootPhrases: phrases, wordPhrases: w.phrases || phrases.slice(0, 2) })),
    phrases, mnemonic
  };
}

// 601-700: DevOps、云服务与部署
const allRoots = [
  // 容器与编排 (601-620)
  { id: 601, root: "docker", phonetic: "/ˈdɒkər/", pos: "名词", meaning: "Docker容器平台", phrases: ["docker container Docker容器", "docker image Docker镜像", "dockerfile Docker文件", "docker compose Docker组合"], mnemonic: "Docker让应用在任何地方都能一致运行", words: [{ word: "docker", phonetic: "/ˈdɒkər/", pos: "n.", meaning: "Docker", tip: "码头工人，容器平台" }, { word: "dockerfile", phonetic: "/ˈdɒkərfaɪl/", pos: "n.", meaning: "Dockerfile", tip: "docker + file" }, { word: "docker-compose", phonetic: "/ˈdɒkər kɒmpoʊz/", pos: "n.", meaning: "Docker Compose", tip: "docker + compose" }, { word: "dockerhub", phonetic: "/ˈdɒkərhʌb/", pos: "n.", meaning: "Docker Hub", tip: "docker + hub" }] },
  { id: 602, root: "kubernetes", phonetic: "/ˌkuːbərˈnetiːz/", pos: "名词", meaning: "Kubernetes容器编排", phrases: ["kubernetes pod K8s Pod", "kubernetes service K8s服务", "kubernetes deployment K8s部署", "kubernetes cluster K8s集群"], mnemonic: "Kubernetes是容器编排的行业标准", words: [{ word: "kubernetes", phonetic: "/ˌkuːbərˈnetiːz/", pos: "n.", meaning: "Kubernetes", tip: "舵手，K8s" }, { word: "k8s", phonetic: "/keɪteɪɛs/", pos: "n.", meaning: "K8s", tip: "Kubernetes简称" }, { word: "kubectl", phonetic: "/kuːbəsiːtiːɛl/", pos: "n.", meaning: "kubectl", tip: "K8s命令行工具" }, { word: "kubernetes-helm", phonetic: "/ˌkuːbərˈnetiːz helm/", pos: "n.", meaning: "Helm", tip: "K8s包管理器" }] },
  { id: 603, root: "container", phonetic: "/kənˈteɪnər/", pos: "名词", meaning: "容器", phrases: ["container runtime 容器运行时", "container image 容器镜像", "container registry 容器仓库", "container orchestration 容器编排"], mnemonic: "容器是轻量级的独立运行环境", words: [{ word: "container", phonetic: "/kənˈteɪnər/", pos: "n.", meaning: "容器", tip: "contain包含 + er" }, { word: "containerization", phonetic: "/kənˈteɪnəraɪˈzeɪʃn/", pos: "n.", meaning: "容器化", tip: "container + ization" }, { word: "containerd", phonetic: "/kənˈteɪnərd/", pos: "n.", meaning: "containerd", tip: "容器运行时" }, { word: "lxc", phonetic: "/ɛlɛksiːsiː/", pos: "n.", meaning: "LXC", tip: "Linux容器" }] },
  { id: 604, root: "podman", phonetic: "/ˈpɒdmæn/", pos: "名词", meaning: "Podman容器工具", phrases: ["podman container Podman容器", "podman pod Podman Pod", "podman build Podman构建", "podman compose Podman组合"], mnemonic: "Podman是无守护进程的Docker替代品", words: [{ word: "podman", phonetic: "/ˈpɒdmæn/", pos: "n.", meaning: "Podman", tip: "pod + man，容器工具" }, { word: "podman-machine", phonetic: "/ˈpɒdmæn məˈʃiːn/", pos: "n.", meaning: "Podman Machine", tip: "podman + machine" }, { word: "pod", phonetic: "/pɒd/", pos: "n.", meaning: "Pod", tip: "豆荚，容器组" }, { word: "rootless", phonetic: "/ˈruːtləs/", pos: "adj.", meaning: "无根", tip: "root + less，无需root权限" }] },
  { id: 605, root: "helm", phonetic: "/helm/", pos: "名词", meaning: "Helm K8s包管理器", phrases: ["helm chart Helm图表", "helm repository Helm仓库", "helm release Helm发布", "helm install Helm安装"], mnemonic: "Helm是Kubernetes的包管理器，像apt/yum一样", words: [{ word: "helm", phonetic: "/helm/", pos: "n.", meaning: "Helm", tip: "舵轮，K8s包管理器" }, { word: "helmfile", phonetic: "/helmfaɪl/", pos: "n.", meaning: "Helmfile", tip: "helm + file" }, { word: "helm-chart", phonetic: "/helm tʃɑːrt/", pos: "n.", meaning: "Helm Chart", tip: "helm + chart" }, { word: "helmsman", phonetic: "/ˈhelmzmən/", pos: "n.", meaning: "Helmsman", tip: "舵手，Helm用户" }] },
  { id: 606, root: "jenkins", phonetic: "/ˈdʒɛŋkɪnz/", pos: "名词", meaning: "Jenkins CI/CD工具", phrases: ["jenkins pipeline Jenkins流水线", "jenkins job Jenkins任务", "jenkins plugin Jenkins插件", "jenkins node Jenkins节点"], mnemonic: "Jenkins是最流行的开源CI/CD工具", words: [{ word: "jenkins", phonetic: "/ˈdʒɛŋkɪnz/", pos: "n.", meaning: "Jenkins", tip: "Jenkins，CI/CD工具" }, { word: "jenkinsfile", phonetic: "/ˈdʒɛŋkɪnzfaɪl/", pos: "n.", meaning: "Jenkinsfile", tip: "jenkins + file" }, { word: "blue-ocean", phonetic: "/bluː ˈoʊʃn/", pos: "n.", meaning: "Blue Ocean", tip: "Jenkins UI插件" }, { word: "jenkins-x", phonetic: "/ˈdʒɛŋkɪnz ɛks/", pos: "n.", meaning: "Jenkins X", tip: "云原生Jenkins" }] },
  { id: 607, root: "gitlab", phonetic: "/ˈɡɪtlæb/", pos: "名词", meaning: "GitLab代码托管平台", phrases: ["gitlab ci GitLab CI", "gitlab runner GitLab Runner", "gitlab registry GitLab仓库", "gitlab pages GitLab页面"], mnemonic: "GitLab是完整的DevOps平台", words: [{ word: "gitlab", phonetic: "/ˈɡɪtlæb/", pos: "n.", meaning: "GitLab", tip: "git + lab，代码托管" }, { word: "gitlab-ci", phonetic: "/ˈɡɪtlæb siːaɪ/", pos: "n.", meaning: "GitLab CI", tip: "gitlab + ci" }, { word: "gitlab-runner", phonetic: "/ˈɡɪtlæb ˈrʌnər/", pos: "n.", meaning: "GitLab Runner", tip: "gitlab + runner" }, { word: "gitlabyml", phonetic: "/ˈɡɪtlæb wɪml/", pos: "n.", meaning: ".gitlab-ci.yml", tip: "GitLab CI配置文件" }] },
  { id: 608, root: "github", phonetic: "/ˈɡɪthʌb/", pos: "名词", meaning: "GitHub代码托管平台", phrases: ["github repo GitHub仓库", "github actions GitHub Actions", "github pages GitHub Pages", "github gist GitHub Gist"], mnemonic: "GitHub是世界最大的代码托管平台", words: [{ word: "github", phonetic: "/ˈɡɪthʌb/", pos: "n.", meaning: "GitHub", tip: "git + hub，代码托管" }, { word: "github-actions", phonetic: "/ˈɡɪthʌb ˈækʃnz/", pos: "n.", meaning: "GitHub Actions", tip: "github + actions" }, { word: "github-pages", phonetic: "/ˈɡɪthʌb peɪdʒɪz/", pos: "n.", meaning: "GitHub Pages", tip: "github + pages" }, { word: "github-copilot", phonetic: "/ˈɡɪthʌb ˈkoʊpɪlət/", pos: "n.", meaning: "GitHub Copilot", tip: "github + copilot" }] },
  { id: 609, root: "bitbucket", phonetic: "/ˈbɪtbʌkɪt/", pos: "名词", meaning: "Bitbucket代码托管", phrases: ["bitbucket repo Bitbucket仓库", "bitbucket pipeline Bitbucket流水线", "bitbucket cloud Bitbucket云", "bitbucket server Bitbucket服务器"], mnemonic: "Bitbucket是Atlassian的Git代码托管服务", words: [{ word: "bitbucket", phonetic: "/ˈbɪtbʌkɪt/", pos: "n.", meaning: "Bitbucket", tip: "bit + bucket，代码托管" }, { word: "bitbucket-pipeline", phonetic: "/ˈbɪtbʌkɪt ˈpaɪplaɪn/", pos: "n.", meaning: "Bitbucket Pipeline", tip: "bitbucket + pipeline" }, { word: "atlassian", phonetic: "/ətˈlæsiən/", pos: "n.", meaning: "Atlassian", tip: "Atlassian公司" }, { word: "sourcetree", phonetic: "/ˈsɔːrstriː/", pos: "n.", meaning: "SourceTree", tip: "Git GUI客户端" }] },
  { id: 610, root: "travis", phonetic: "/ˈtrævɪs/", pos: "名词", meaning: "Travis CI工具", phrases: ["travis ci Travis CI", "travis build Travis构建", "travis yaml Travis配置", "travis deploy Travis部署"], mnemonic: "Travis CI是最早的托管CI服务之一", words: [{ word: "travis", phonetic: "/ˈtrævɪs/", pos: "n.", meaning: "Travis", tip: "Travis，CI服务" }, { word: "travisci", phonetic: "/ˈtrævɪssiːaɪ/", pos: "n.", meaning: "Travis CI", tip: "travis + ci" }, { word: "travis-yml", phonetic: "/ˈtrævɪs wɪml/", pos: "n.", meaning: ".travis.yml", tip: "Travis配置文件" }, { word: "travis-build", phonetic: "/ˈtrævɪs bɪld/", pos: "n.", meaning: "Travis构建", tip: "travis + build" }] },
  { id: 611, root: "circleci", phonetic: "/ˈsɜːrkl siːaɪ/", pos: "名词", meaning: "CircleCI工具", phrases: ["circleci pipeline CircleCI流水线", "circleci config CircleCI配置", "circleci orb CircleCI Orb", "circleci workflow CircleCI工作流"], mnemonic: "CircleCI是云原生CI/CD平台", words: [{ word: "circleci", phonetic: "/ˈsɜːrkl siːaɪ/", pos: "n.", meaning: "CircleCI", tip: "circle + ci，CI/CD" }, { word: "circleci-config", phonetic: "/ˈsɜːrkl siːaɪ kənˈfɪɡ/", pos: "n.", meaning: "CircleCI配置", tip: "circleci + config" }, { word: "circleci-orb", phonetic: "/ˈsɜːrkl siːaɪ ɔːrb/", pos: "n.", meaning: "CircleCI Orb", tip: "circleci + orb" }, { word: "circleci-workflow", phonetic: "/ˈsɜːrkl siːaɪ ˈwɜːrkfloʊ/", pos: "n.", meaning: "CircleCI工作流", tip: "circleci + workflow" }] },
  { id: 612, root: "ansible", phonetic: "/ˈænsɪbl/", pos: "名词", meaning: "Ansible自动化工具", phrases: ["ansible playbook Ansible剧本", "ansible role Ansible角色", "ansible inventory Ansible清单", "ansible module Ansible模块"], mnemonic: "Ansible是无代理的IT自动化工具", words: [{ word: "ansible", phonetic: "/ˈænsɪbl/", pos: "n.", meaning: "Ansible", tip: "Ansible，自动化工具" }, { word: "ansible-playbook", phonetic: "/ˈænsɪbl ˈpleɪbʊk/", pos: "n.", meaning: "Ansible Playbook", tip: "ansible + playbook" }, { word: "ansible-galaxy", phonetic: "/ˈænsɪbl ˈɡæləksi/", pos: "n.", meaning: "Ansible Galaxy", tip: "ansible + galaxy" }, { word: "ansible-tower", phonetic: "/ˈænsɪbl ˈtaʊər/", pos: "n.", meaning: "Ansible Tower", tip: "ansible + tower" }] },
  { id: 613, root: "terraform", phonetic: "/ˈtɛrəfɔːrm/", pos: "名词", meaning: "Terraform基础设施即代码", phrases: ["terraform provider Terraform提供者", "terraform resource Terraform资源", "terraform state Terraform状态", "terraform plan Terraform计划"], mnemonic: "Terraform是基础设施即代码工具", words: [{ word: "terraform", phonetic: "/ˈtɛrəfɔːrm/", pos: "n.", meaning: "Terraform", tip: "terra土地 + form形成" }, { word: "terraform-hcl", phonetic: "/ˈtɛrəfɔːrm eɪtʃsiːɛl/", pos: "n.", meaning: "Terraform HCL", tip: "terraform + hcl" }, { word: "terraform-cloud", phonetic: "/ˈtɛrəfɔːrm klaʊd/", pos: "n.", meaning: "Terraform Cloud", tip: "terraform + cloud" }, { word: "terraform-module", phonetic: "/ˈtɛrəfɔːrm ˈmɒdjuːl/", pos: "n.", meaning: "Terraform模块", tip: "terraform + module" }] },
  { id: 614, root: "pulumi", phonetic: "/ˈpjuːləmi/", pos: "名词", meaning: "Pulumi基础设施即代码", phrases: ["pulumi stack Pulumi栈", "pulumi resource Pulumi资源", "pulumi provider Pulumi提供者", "pulumi component Pulumi组件"], mnemonic: "Pulumi用编程语言定义基础设施", words: [{ word: "pulumi", phonetic: "/ˈpjuːləmi/", pos: "n.", meaning: "Pulumi", tip: "Pulumi，IaC工具" }, { word: "pulumi-stack", phonetic: "/ˈpjuːləmi stæk/", pos: "n.", meaning: "Pulumi Stack", tip: "pulumi + stack" }, { word: "pulumi-program", phonetic: "/ˈpjuːləmi ˈproʊɡræm/", pos: "n.", meaning: "Pulumi程序", tip: "pulumi + program" }, { word: "pulumi-cloud", phonetic: "/ˈpjuːləmi klaʊd/", pos: "n.", meaning: "Pulumi Cloud", tip: "pulumi + cloud" }] },
  { id: 615, root: "vagrant", phonetic: "/ˈveɪɡrənt/", pos: "名词", meaning: "Vagrant虚拟机工具", phrases: ["vagrant box Vagrant盒子", "vagrant file Vagrant文件", "vagrant provision Vagrant配置", "vagrant share Vagrant共享"], mnemonic: "Vagrant是构建虚拟开发环境的工具", words: [{ word: "vagrant", phonetic: "/ˈveɪɡrənt/", pos: "n.", meaning: "Vagrant", tip: "流浪者，虚拟机工具" }, { word: "vagrantfile", phonetic: "/ˈveɪɡrəntfaɪl/", pos: "n.", meaning: "Vagrantfile", tip: "vagrant + file" }, { word: "vagrant-box", phonetic: "/ˈveɪɡrənt bɒks/", pos: "n.", meaning: "Vagrant Box", tip: "vagrant + box" }, { word: "vagrant-cloud", phonetic: "/ˈveɪɡrənt klaʊd/", pos: "n.", meaning: "Vagrant Cloud", tip: "vagrant + cloud" }] },
  { id: 616, root: "puppet", phonetic: "/ˈpʌpɪt/", pos: "名词", meaning: "Puppet配置管理", phrases: ["puppet manifest Puppet清单", "puppet module Puppet模块", "puppet master Puppet主节点", "puppet agent Puppet代理"], mnemonic: "Puppet是IT基础设施自动化工具", words: [{ word: "puppet", phonetic: "/ˈpʌpɪt/", pos: "n.", meaning: "Puppet", tip: "木偶，配置管理工具" }, { word: "puppeteer", phonetic: "/ˈpʌpɪtɪər/", pos: "n.", meaning: "Puppeteer", tip: "木偶师，注意与puppet不同" }, { word: "puppet-labs", phonetic: "/ˈpʌpɪt læbz/", pos: "n.", meaning: "Puppet Labs", tip: "puppet + labs" }, { word: "puppet-forge", phonetic: "/ˈpʌpɪt fɔːrdʒ/", pos: "n.", meaning: "Puppet Forge", tip: "puppet + forge" }] },
  { id: 617, root: "chef", phonetic: "/ʃɛf/", pos: "名词", meaning: "Chef配置管理", phrases: ["chef cookbook Chef食谱", "chef recipe Chef配方", "chef knife Chef刀", "chef server Chef服务器"], mnemonic: "Chef将基础设施视为代码的自动化平台", words: [{ word: "chef", phonetic: "/ʃɛf/", pos: "n.", meaning: "Chef", tip: "厨师，配置管理" }, { word: "chef-cookbook", phonetic: "/ʃɛf ˈkʊkbʊk/", pos: "n.", meaning: "Chef Cookbook", tip: "chef + cookbook" }, { word: "chef-recipe", phonetic: "/ʃɛf ˈrɛsɪpi/", pos: "n.", meaning: "Chef Recipe", tip: "chef + recipe" }, { word: "chef-solo", phonetic: "/ʃɛf ˈsoʊloʊ/", pos: "n.", meaning: "Chef Solo", tip: "chef + solo" }] },
  { id: 618, root: "saltstack", phonetic: "/ˈsɔːltstæk/", pos: "名词", meaning: "SaltStack配置管理", phrases: ["salt state Salt状态", "salt pillar Salt柱", "salt grain Salt颗粒", "salt mine Salt矿"], mnemonic: "SaltStack是快速、可扩展的自动化平台", words: [{ word: "saltstack", phonetic: "/ˈsɔːltstæk/", pos: "n.", meaning: "SaltStack", tip: "salt + stack，配置管理" }, { word: "salt", phonetic: "/ˈsɔːlt/", pos: "n.", meaning: "Salt", tip: "盐，SaltStack简称" }, { word: "salt-minion", phonetic: "/ˈsɔːlt ˈmɪnjən/", pos: "n.", meaning: "Salt Minion", tip: "salt + minion" }, { word: "salt-master", phonetic: "/ˈsɔːlt ˈmɑːstər/", pos: "n.", meaning: "Salt Master", tip: "salt + master" }] },
  { id: 619, root: "consul", phonetic: "/ˈkɒnsl/", pos: "名词", meaning: "Consul服务网格", phrases: ["consul service Consul服务", "consul kv Consul键值", "consul health Consul健康", "consul mesh Consul网格"], mnemonic: "Consul是服务发现和服务网格解决方案", words: [{ word: "consul", phonetic: "/ˈkɒnsl/", pos: "n.", meaning: "Consul", tip: "领事，服务网格" }, { word: "consul-service", phonetic: "/ˈkɒnsl ˈsɜːrvɪs/", pos: "n.", meaning: "Consul服务", tip: "consul + service" }, { word: "consul-kv", phonetic: "/ˈkɒnsl keɪviː/", pos: "n.", meaning: "Consul KV", tip: "consul + kv" }, { word: "consul-connect", phonetic: "/ˈkɒnsl kəˈnɛkt/", pos: "n.", meaning: "Consul Connect", tip: "consul + connect" }] },
  { id: 620, root: "vault", phonetic: "/vɔːlt/", pos: "名词", meaning: "Vault密钥管理", phrases: ["vault secret Vault密钥", "vault policy Vault策略", "vault token Vault令牌", "vault kv Vault键值"], mnemonic: "Vault是HashiCorp的密钥和敏感数据管理工具", words: [{ word: "vault", phonetic: "/vɔːlt/", pos: "n.", meaning: "Vault", tip: "金库，密钥管理" }, { word: "vault-server", phonetic: "/vɔːlt ˈsɜːrvər/", pos: "n.", meaning: "Vault服务器", tip: "vault + server" }, { word: "vault-agent", phonetic: "/vɔːlt ˈeɪdʒənt/", pos: "n.", meaning: "Vault代理", tip: "vault + agent" }, { word: "vault-unseal", phonetic: "/vɔːlt ʌnˈsiːl/", pos: "n.", meaning: "Vault解封", tip: "vault + unseal" }] }
];

console.log(`Adding ${allRoots.length} entries (601-620)`);

const newEntries = allRoots.map(r => createEntry(r.id, r.root, r.phonetic, r.pos, r.meaning, r.phrases, r.mnemonic, r.words));

const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
console.log(`Current: ${data.length}`);

const updatedData = [...data, ...newEntries];
console.log(`New total: ${updatedData.length}`);

fs.writeFileSync(filePath, JSON.stringify(updatedData, null, 2));
console.log('Batch 6 (part 1) done!');
