const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'src', 'data', 'internet-software.json');

function createEntry(id, root, phonetic, pos, meaning, phrases, mnemonic, words) {
  return {
    id, root, phonetic, partOfSpeech: pos, meaning, frequency: id, category: "互联网和软件",
    words: words.map(w => ({ word: w.word, phonetic: w.phonetic, partOfSpeech: w.pos, meaning: w.meaning, memoryTip: w.tip, root, rootPhonetic: phonetic, rootMeaning: meaning, rootPhrases: phrases, wordPhrases: w.phrases || phrases.slice(0, 2) })),
    phrases, mnemonic
  };
}

const allRoots = [
  // 581-620: ORM与数据库工具
  { id: 581, root: "sequelize", phonetic: "/ˈsiːkwəlaɪz/", pos: "名词", meaning: "Sequelize ORM", phrases: ["sequelize model Sequelize模型", "sequelize migration Sequelize迁移", "sequelize association Sequelize关联", "sequelize query Sequelize查询"], mnemonic: "Sequelize是Node.js的Promise式ORM", words: [{ word: "sequelize", phonetic: "/ˈsiːkwəlaɪz/", pos: "n.", meaning: "Sequelize", tip: "sequel后续 + ize，ORM" }, { word: "sequel", phonetic: "/ˈsiːkwəl/", pos: "n.", meaning: "Sequel", tip: "续集，后续" }, { word: "sequelize-cli", phonetic: "/ˈsiːkwəlaɪz siːɛlaɪ/", pos: "n.", meaning: "Sequelize CLI", tip: "sequelize + cli" }, { word: "sequelize-typescript", phonetic: "/ˈsiːkwəlaɪz ˈtaɪpskript/", pos: "n.", meaning: "Sequelize TypeScript", tip: "sequelize + typescript" }] },
  { id: 582, root: "typeorm", phonetic: "/taɪp ɔːrm/", pos: "名词", meaning: "TypeORM框架", phrases: ["typeorm entity TypeORM实体", "typeorm repository TypeORM仓库", "typeorm migration TypeORM迁移", "typeorm decorator TypeORM装饰器"], mnemonic: "TypeORM是TypeScript的ORM框架", words: [{ word: "typeorm", phonetic: "/taɪp ɔːrm/", pos: "n.", meaning: "TypeORM", tip: "type + orm" }, { word: "typeorm-entity", phonetic: "/taɪp ɔːrm ˈɛntɪti/", pos: "n.", meaning: "TypeORM实体", tip: "typeorm + entity" }, { word: "typeorm-repository", phonetic: "/taɪp ɔːrm rɪˈpɒzɪtɔːri/", pos: "n.", meaning: "TypeORM仓库", tip: "typeorm + repository" }, { word: "typeorm-migration", phonetic: "/taɪp ɔːrm maɪˈɡreɪʃn/", pos: "n.", meaning: "TypeORM迁移", tip: "typeorm + migration" }] },
  { id: 583, root: "prisma", phonetic: "/ˈpriːzmə/", pos: "名词", meaning: "Prisma ORM", phrases: ["prisma client Prisma客户端", "prisma schema Prisma模式", "prisma migration Prisma迁移", "prisma studio Prisma工作室"], mnemonic: "Prisma是下一代Node.js和TypeScript ORM", words: [{ word: "prisma", phonetic: "/ˈpriːzmə/", pos: "n.", meaning: "Prisma", tip: "棱镜，ORM" }, { word: "prisma-client", phonetic: "/ˈpriːzmə ˈklaɪənt/", pos: "n.", meaning: "Prisma Client", tip: "prisma + client" }, { word: "prisma-schema", phonetic: "/ˈpriːzmə ˈskiːmə/", pos: "n.", meaning: "Prisma Schema", tip: "prisma + schema" }, { word: "prisma-migrate", phonetic: "/ˈpriːzmə maɪˈɡreɪt/", pos: "n.", meaning: "Prisma Migrate", tip: "prisma + migrate" }] },
  { id: 584, root: "mongoose", phonetic: "/ˈmɒŋɡuːs/", pos: "名词", meaning: "Mongoose ODM", phrases: ["mongoose schema Mongoose模式", "mongoose model Mongoose模型", "mongoose query Mongoose查询", "mongoose middleware Mongoose中间件"], mnemonic: "Mongoose是MongoDB的对象建模工具", words: [{ word: "mongoose", phonetic: "/ˈmɒŋɡuːs/", pos: "n.", meaning: "Mongoose", tip: "猫鼬，MongoDB ODM" }, { word: "mongoose-schema", phonetic: "/ˈmɒŋɡuːs ˈskiːmə/", pos: "n.", meaning: "Mongoose模式", tip: "mongoose + schema" }, { word: "mongoose-model", phonetic: "/ˈmɒŋɡuːs ˈmɒdl/", pos: "n.", meaning: "Mongoose模型", tip: "mongoose + model" }, { word: "mongoose-plugin", phonetic: "/ˈmɒŋɡuːs ˈplʌɡɪn/", pos: "n.", meaning: "Mongoose插件", tip: "mongoose + plugin" }] },
  { id: 585, root: "knex", phonetic: "/ˈkɛnɛks/", pos: "名词", meaning: "Knex.js查询构建器", phrases: ["knex query Knex查询", "knex migration Knex迁移", "knex seed Knex种子", "knex transaction Knex事务"], mnemonic: "Knex是SQL查询构建器，支持多种数据库", words: [{ word: "knex", phonetic: "/ˈkɛnɛks/", pos: "n.", meaning: "Knex", tip: "Kenex，查询构建器" }, { word: "knexjs", phonetic: "/ˈkɛnɛksdʒeɪɛs/", pos: "n.", meaning: "Knex.js", tip: "knex + js" }, { word: "knex-query", phonetic: "/ˈkɛnɛks kwɪəri/", pos: "n.", meaning: "Knex查询", tip: "knex + query" }, { word: "knex-migration", phonetic: "/ˈkɛnɛks maɪˈɡreɪʃn/", pos: "n.", meaning: "Knex迁移", tip: "knex + migration" }] },
  { id: 586, root: "bookshelf", phonetic: "/ˈbʊkʃelf/", pos: "名词", meaning: "Bookshelf ORM", phrases: ["bookshelf model Bookshelf模型", "bookshelf collection Bookshelf集合", "bookshelf relation Bookshelf关系", "bookshelf knex Bookshelf+Knex"], mnemonic: "Bookshelf是基于Knex的ORM", words: [{ word: "bookshelf", phonetic: "/ˈbʊkʃelf/", pos: "n.", meaning: "Bookshelf", tip: "书架，ORM" }, { word: "bookshelf-orm", phonetic: "/ˈbʊkʃelf ɔːrm/", pos: "n.", meaning: "Bookshelf ORM", tip: "bookshelf + orm" }, { word: "bookshelf-model", phonetic: "/ˈbʊkʃelf ˈmɒdl/", pos: "n.", meaning: "Bookshelf模型", tip: "bookshelf + model" }, { word: "bookshelf-collection", phonetic: "/ˈbʊkʃelf kəˈlɛkʃn/", pos: "n.", meaning: "Bookshelf集合", tip: "bookshelf + collection" }] },
  { id: 587, root: "objection", phonetic: "/əbˈdʒɛkʃn/", pos: "名词", meaning: "Objection.js ORM", phrases: ["objection model Objection模型", "objection query Objection查询", "objection relation Objection关系", "objection schema Objection模式"], mnemonic: "Objection是基于Knex的轻量级ORM", words: [{ word: "objection", phonetic: "/əbˈdʒɛkʃn/", pos: "n.", meaning: "Objection", tip: "反对，ORM" }, { word: "objectionjs", phonetic: "/əbˈdʒɛkʃndʒeɪɛs/", pos: "n.", meaning: "Objection.js", tip: "objection + js" }, { word: "objection-model", phonetic: "/əbˈdʒɛkʃn ˈmɒdl/", pos: "n.", meaning: "Objection模型", tip: "objection + model" }, { word: "objection-query", phonetic: "/əbˈdʒɛkʃn kwɪəri/", pos: "n.", meaning: "Objection查询", tip: "objection + query" }] },
  { id: 588, root: "waterline", phonetic: "/ˈwɔːtərlaɪn/", pos: "名词", meaning: "Waterline ORM", phrases: ["waterline model Waterline模型", "waterline adapter Waterline适配器", "waterline connection Waterline连接", "waterline query Waterline查询"], mnemonic: "Waterline是Sails.js的默认ORM", words: [{ word: "waterline", phonetic: "/ˈwɔːtərlaɪn/", pos: "n.", meaning: "Waterline", tip: "吃水线，ORM" }, { word: "waterline-orm", phonetic: "/ˈwɔːtərlaɪn ɔːrm/", pos: "n.", meaning: "Waterline ORM", tip: "waterline + orm" }, { word: "waterline-adapter", phonetic: "/ˈwɔːtərlaɪn əˈdæptər/", pos: "n.", meaning: "Waterline适配器", tip: "waterline + adapter" }, { word: "waterline-model", phonetic: "/ˈwɔːtərlaɪn ˈmɒdl/", pos: "n.", meaning: "Waterline模型", tip: "waterline + model" }] },
  { id: 589, root: "orm", phonetic: "/oʊ ɑːr ɛm/", pos: "名词", meaning: "对象关系映射", phrases: ["orm framework ORM框架", "orm mapping ORM映射", "orm model ORM模型", "orm query ORM查询"], mnemonic: "ORM是对象关系映射，连接对象和数据库", words: [{ word: "orm", phonetic: "/oʊ ɑːr ɛm/", pos: "n.", meaning: "ORM", tip: "Object-Relational Mapping" }, { word: "object-relational", phonetic: "/ˈɒbdʒɪkt rɪˈleɪʃənl/", pos: "adj.", meaning: "对象关系", tip: "object + relational" }, { word: "orm-mapper", phonetic: "/oʊ ɑːr ɛm ˈmæpər/", pos: "n.", meaning: "ORM映射器", tip: "orm + mapper" }, { word: "orm-tool", phonetic: "/oʊ ɑːr ɛm tuːl/", pos: "n.", meaning: "ORM工具", tip: "orm + tool" }] },
  { id: 590, root: "graphql", phonetic: "/ɡræf kjuːɛl/", pos: "名词", meaning: "GraphQL查询语言", phrases: ["graphql query GraphQL查询", "graphql mutation GraphQL变更", "graphql schema GraphQL模式", "graphql resolver GraphQL解析器"], mnemonic: "GraphQL是API查询语言", words: [{ word: "graphql", phonetic: "/ɡræf kjuːɛl/", pos: "n.", meaning: "GraphQL", tip: "Graph + Query Language" }, { word: "graphql-server", phonetic: "/ɡræf kjuːɛl ˈsɜːrvər/", pos: "n.", meaning: "GraphQL服务器", tip: "graphql + server" }, { word: "graphql-client", phonetic: "/ɡræf kjuːɛl ˈklaɪənt/", pos: "n.", meaning: "GraphQL客户端", tip: "graphql + client" }, { word: "graphql-playground", phonetic: "/ɡræf kjuːɛl ˈpleɪɡraʊnd/", pos: "n.", meaning: "GraphQL Playground", tip: "graphql + playground" }] },
  { id: 591, root: "apollo", phonetic: "/əˈpɒloʊ/", pos: "名词", meaning: "Apollo GraphQL平台", phrases: ["apollo client Apollo客户端", "apollo server Apollo服务器", "apollo studio Apollo工作室", "apollo federation Apollo联邦"], mnemonic: "Apollo是GraphQL的全栈平台", words: [{ word: "apollo", phonetic: "/əˈpɒloʊ/", pos: "n.", meaning: "Apollo", tip: "阿波罗，GraphQL平台" }, { word: "apollo-client", phonetic: "/əˈpɒloʊ ˈklaɪənt/", pos: "n.", meaning: "Apollo Client", tip: "apollo + client" }, { word: "apollo-server", phonetic: "/əˈpɒloʊ ˈsɜːrvər/", pos: "n.", meaning: "Apollo Server", tip: "apollo + server" }, { word: "apollo-federation", phonetic: "/əˈpɒloʊ fɛdəˈreɪʃn/", pos: "n.", meaning: "Apollo Federation", tip: "apollo + federation" }] },
  { id: 592, root: "relay", phonetic: "/ˈriːleɪ/", pos: "名词", meaning: "Relay GraphQL客户端", phrases: ["relay graphql Relay GraphQL", "relay fragment Relay片段", "relay mutation Relay变更", "relay connection Relay连接"], mnemonic: "Relay是React的GraphQL客户端框架", words: [{ word: "relay", phonetic: "/ˈriːleɪ/", pos: "n.", meaning: "Relay", tip: "接力，GraphQL客户端" }, { word: "relay-modern", phonetic: "/ˈriːleɪ ˈmɒdərn/", pos: "n.", meaning: "Relay Modern", tip: "relay + modern" }, { word: "relay-compiler", phonetic: "/ˈriːleɪ kəmˈpaɪlər/", pos: "n.", meaning: "Relay编译器", tip: "relay + compiler" }, { word: "relay-runtime", phonetic: "/ˈriːleɪ ˈrʌntaɪm/", pos: "n.", meaning: "Relay运行时", tip: "relay + runtime" }] },
  { id: 593, root: "urql", phonetic: "/ˈɜːrkwəl/", pos: "名词", meaning: "URQL GraphQL客户端", phrases: ["urql client URQL客户端", "urql exchange URQL交换器", "urql subscription URQL订阅", "urql cache URQL缓存"], mnemonic: "URQL是轻量级的GraphQL客户端", words: [{ word: "urql", phonetic: "/ˈɜːrkwəl/", pos: "n.", meaning: "URQL", tip: "Universal React Query Library" }, { word: "urql-react", phonetic: "/ˈɜːrkwəl riːækt/", pos: "n.", meaning: "URQL React", tip: "urql + react" }, { word: "urql-core", phonetic: "/ˈɜːrkwəl kɔːr/", pos: "n.", meaning: "URQL Core", tip: "urql + core" }, { word: "urql-exchange", phonetic: "/ˈɜːrkwəl ɪksˈtʃeɪndʒ/", pos: "n.", meaning: "URQL Exchange", tip: "urql + exchange" }] },
  { id: 594, root: "hasura", phonetic: "/həˈsʊərə/", pos: "名词", meaning: "Hasura GraphQL引擎", phrases: ["hasura graphql Hasura GraphQL", "hasura console Hasura控制台", "hasura migration Hasura迁移", "hasura auth Hasura认证"], mnemonic: "Hasura从数据库自动生成GraphQL API", words: [{ word: "hasura", phonetic: "/həˈsʊərə/", pos: "n.", meaning: "Hasura", tip: "Hasura，GraphQL引擎" }, { word: "hasura-engine", phonetic: "/həˈsʊərə ˈɛndʒɪn/", pos: "n.", meaning: "Hasura引擎", tip: "hasura + engine" }, { word: "hasura-cloud", phonetic: "/həˈsʊərə klaʊd/", pos: "n.", meaning: "Hasura Cloud", tip: "hasura + cloud" }, { word: "hasura-actions", phonetic: "/həˈsʊərə ˈækʃnz/", pos: "n.", meaning: "Hasura动作", tip: "hasura + actions" }] },
  { id: 595, root: "postgrest", phonetic: "/poʊstˈɡrɛst/", pos: "名词", meaning: "PostgREST API生成器", phrases: ["postgrest api PostgREST API", "postgrest postgresql PostgREST+PostgreSQL", "postgrest rest PostgREST REST", "postgrest auth PostgREST认证"], mnemonic: "PostgREST从PostgreSQL数据库自动生成RESTful API", words: [{ word: "postgrest", phonetic: "/poʊstˈɡrɛst/", pos: "n.", meaning: "PostgREST", tip: "Postgres + REST" }, { word: "postgrest-client", phonetic: "/poʊstˈɡrɛst ˈklaɪənt/", pos: "n.", meaning: "PostgREST客户端", tip: "postgrest + client" }, { word: "postgrest-js", phonetic: "/poʊstˈɡrɛst dʒeɪɛs/", pos: "n.", meaning: "PostgREST.js", tip: "postgrest + js" }, { word: "supabase", phonetic: "/ˈsuːpəbeɪs/", pos: "n.", meaning: "Supabase", tip: "超级基础，Postgres即服务" }] },
  { id: 596, root: "firebase", phonetic: "/ˈfaɪərbɛs/", pos: "名词", meaning: "Firebase后端平台", phrases: ["firebase auth Firebase认证", "firebase database Firebase数据库", "firebase storage Firebase存储", "firebase hosting Firebase托管"], mnemonic: "Firebase是Google的移动应用开发平台", words: [{ word: "firebase", phonetic: "/ˈfaɪərbɛs/", pos: "n.", meaning: "Firebase", tip: "火基地，Google后端" }, { word: "firebase-firestore", phonetic: "/ˈfaɪərbɛs ˈfaɪərstɔːr/", pos: "n.", meaning: "Firestore", tip: "firebase + firestore" }, { word: "firebase-functions", phonetic: "/ˈfaɪərbɛs ˈfʌŋkʃnz/", pos: "n.", meaning: "Firebase Functions", tip: "firebase + functions" }, { word: "firebase-analytics", phonetic: "/ˈfaɪərbɛs ˌænəˈlɪtɪks/", pos: "n.", meaning: "Firebase Analytics", tip: "firebase + analytics" }] },
  { id: 597, root: "supabase", phonetic: "/ˈsuːpəbeɪs/", pos: "名词", meaning: "Supabase开源Firebase替代", phrases: ["supabase postgres Supabase Postgres", "supabase auth Supabase认证", "supabase realtime Supabase实时", "supabase storage Supabase存储"], mnemonic: "Supabase是开源的Firebase替代品", words: [{ word: "supabase", phonetic: "/ˈsuːpəbeɪs/", pos: "n.", meaning: "Supabase", tip: "super + base，开源后端" }, { word: "supabase-js", phonetic: "/ˈsuːpəbeɪs dʒeɪɛs/", pos: "n.", meaning: "Supabase.js", tip: "supabase + js" }, { word: "supabase-client", phonetic: "/ˈsuːpəbeɪs ˈklaɪənt/", pos: "n.", meaning: "Supabase客户端", tip: "supabase + client" }, { word: "supabase-cli", phonetic: "/ˈsuːpəbeɪs siːɛlaɪ/", pos: "n.", meaning: "Supabase CLI", tip: "supabase + cli" }] },
  { id: 598, root: "appwrite", phonetic: "/ˈæpraɪt/", pos: "名词", meaning: "Appwrite后端平台", phrases: ["appwrite auth Appwrite认证", "appwrite database Appwrite数据库", "appwrite storage Appwrite存储", "appwrite functions Appwrite函数"], mnemonic: "Appwrite是开源的后端即服务平台", words: [{ word: "appwrite", phonetic: "/ˈæpraɪt/", pos: "n.", meaning: "Appwrite", tip: "app + write，后端平台" }, { word: "appwrite-js", phonetic: "/ˈæpraɪt dʒeɪɛs/", pos: "n.", meaning: "Appwrite.js", tip: "appwrite + js" }, { word: "appwrite-console", phonetic: "/ˈæpraɪt ˈkɒnsoʊl/", pos: "n.", meaning: "Appwrite控制台", tip: "appwrite + console" }, { word: "appwrite-sdk", phonetic: "/ˈæpraɪt ɛssiːdiː/", pos: "n.", meaning: "Appwrite SDK", tip: "appwrite + sdk" }] },
  { id: 599, root: "nhost", phonetic: "/ɛnoʊst/", pos: "名词", meaning: "Nhost后端平台", phrases: ["nhost graphql Nhost GraphQL", "nhost hasura Nhost Hasura", "nhost auth Nhost认证", "nhost storage Nhost存储"], mnemonic: "Nhost是基于Hasura的开源后端平台", words: [{ word: "nhost", phonetic: "/ɛnoʊst/", pos: "n.", meaning: "Nhost", tip: "Nhost，后端平台" }, { word: "nhost-js", phonetic: "/ɛnoʊst dʒeɪɛs/", pos: "n.", meaning: "Nhost.js", tip: "nhost + js" }, { word: "nhost-cli", phonetic: "/ɛnoʊst siːɛlaɪ/", pos: "n.", meaning: "Nhost CLI", tip: "nhost + cli" }, { word: "nhost-react", phonetic: "/ɛnoʊst riːækt/", pos: "n.", meaning: "Nhost React", tip: "nhost + react" }] },
  { id: 600, root: "directus", phonetic: "/dɪˈrɛktəs/", pos: "名词", meaning: "Directus无头CMS", phrases: ["directus cms Directus CMS", "directus api Directus API", "directus collection Directus集合", "directus admin Directus管理"], mnemonic: "Directus是开源的无头CMS和API平台", words: [{ word: "directus", phonetic: "/dɪˈrɛktəs/", pos: "n.", meaning: "Directus", tip: "Directus，无头CMS" }, { word: "directus-app", phonetic: "/dɪˈrɛktəs æp/", pos: "n.", meaning: "Directus应用", tip: "directus + app" }, { word: "directus-api", phonetic: "/dɪˈrɛktəs eɪpiːaɪ/", pos: "n.", meaning: "Directus API", tip: "directus + api" }, { word: "directus-sdk", phonetic: "/dɪˈrɛktəs ɛssiːdiː/", pos: "n.", meaning: "Directus SDK", tip: "directus + sdk" }] }
];

console.log(`Adding ${allRoots.length} entries (581-600)`);

const newEntries = allRoots.map(r => createEntry(r.id, r.root, r.phonetic, r.pos, r.meaning, r.phrases, r.mnemonic, r.words));

const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
console.log(`Current: ${data.length}`);

const updatedData = [...data, ...newEntries];
console.log(`New total: ${updatedData.length}`);

fs.writeFileSync(filePath, JSON.stringify(updatedData, null, 2));
console.log('Batch 5 done!');
