const fs = require('fs');

// 完整的300个土木词根数据
const civilRoots = [
  {root:'tender',phonetic:'/ˈtendə/',meaning:'招标',mnemonic:'tend(伸展)+er→招标是伸展出机会'},
  {root:'bid',phonetic:'/bɪd/',meaning:'投标',mnemonic:'音似必得→投标必得'},
  {root:'procurement',phonetic:'/prəˈkjʊəmənt/',meaning:'采购',mnemonic:'pro(向前)+cure(获取)+ment→采购'},
  {root:'turnkey',phonetic:'/ˈtɜːnkiː/',meaning:'交钥匙',mnemonic:'turn(转)+key(钥匙)→交钥匙'},
  {root:'baseline',phonetic:'/ˈbeɪslaɪn/',meaning:'基准线',mnemonic:'base(基础)+line(线)→基准线'},
  {root:'benchmark',phonetic:'/ˈbentʃmɑːk/',meaning:'基准',mnemonic:'bench(长凳)+mark(标记)→基准'},
  {root:'milestone',phonetic:'/ˈmaɪlstəʊn/',meaning:'里程碑',mnemonic:'mile(英里)+stone(石头)→里程碑'},
  {root:'contingency',phonetic:'/kənˈtɪndʒənsi/',meaning:'应急费',mnemonic:'con(共同)+ting(接触)+ency→应急'},
  {root:'escalation',phonetic:'/ˌeskəˈleɪʃn/',meaning:'调增',mnemonic:'e(上)+scal(梯子)+ation→升级'},
  {root:'liquidated',phonetic:'/ˈlɪkwɪdeɪtɪd/',meaning:'清算的',mnemonic:'liquid(液体)+ated→流动清算'},
  {root:'nominated',phonetic:'/ˈnɒmɪneɪtɪd/',meaning:'指定的',mnemonic:'nomin(名字)+ated→指定'},
  {root:'provisional',phonetic:'/prəˈvɪʒənl/',meaning:'临时的',mnemonic:'pro(前)+vis(看)+ional→临时看到'},
  {root:'practical',phonetic:'/ˈpræktɪkl/',meaning:'实际的',mnemonic:'practic(实践)+al→实际的'},
  {root:'substantial',phonetic:'/səbˈstænʃl/',meaning:'实质性的',mnemonic:'sub(下)+stant(站)+ial→实质的'},
  {root:'consequential',phonetic:'/ˌkɒnsɪˈkwenʃl/',meaning:'间接的',mnemonic:'con(一起)+sequ(跟随)+ential→间接的'},
  {root:'retention',phonetic:'/rɪˈtenʃn/',meaning:'保留金',mnemonic:'re(回)+tent(拿住)+ion→保留'},
  {root:'variation',phonetic:'/ˌveəriˈeɪʃn/',meaning:'变更',mnemonic:'vari(变化)+ation→变更'},
  {root:'overhead',phonetic:'/ˈəʊvəhed/',meaning:'间接费用',mnemonic:'over(上)+head(头)→间接费'},
  {root:'turnover',phonetic:'/ˈtɜːnəʊvə/',meaning:'营业额',mnemonic:'turn(转)+over(翻)→周转'},
  {root:'fasttrack',phonetic:'/ˈfɑːstræk/',meaning:'快速通道',mnemonic:'fast(快)+track(轨道)→快速通道'},
  {root:'greenfield',phonetic:'/ˈɡriːnfiːld/',meaning:'绿地项目',mnemonic:'green(绿)+field(地)→绿地项目'},
  {root:'brownfield',phonetic:'/ˈbraʊnfiːld/',meaning:'棕地项目',mnemonic:'brown(棕)+field(地)→棕地项目'},
  {root:'handover',phonetic:'/ˈhændəʊvə/',meaning:'移交',mnemonic:'hand(手)+over(过)→移交'},
  {root:'takeover',phonetic:'/ˈteɪkəʊvə/',meaning:'接管',mnemonic:'take(拿)+over(过)→接管'},
  {root:'makegood',phonetic:'/ˈmeɪkɡʊd/',meaning:'修复',mnemonic:'make(做)+good(好)→修复'},
  {root:'setoff',phonetic:'/ˈsetɒf/',meaning:'抵销',mnemonic:'set(设置)+off(关)→抵销'},
  {root:'holdback',phonetic:'/ˈhəʊldbæk/',meaning:'扣留',mnemonic:'hold(持)+back(回)→扣留'},
  {root:'allowance',phonetic:'/əˈlaʊəns/',meaning:'津贴',mnemonic:'allow(允许)+ance→津贴'},
  {root:'proviso',phonetic:'/prəˈvaɪzəʊ/',meaning:'附带条件',mnemonic:'pro(前)+viso→附带条件'},
  {root:'stipulation',phonetic:'/ˌstɪpjuˈleɪʃn/',meaning:'规定',mnemonic:'stipul(要求)+ation→规定'},
  {root:'warranty',phonetic:'/ˈwɒrənti/',meaning:'保修',mnemonic:'warr(保证)+anty→保修'},
  {root:'guarantee',phonetic:'/ˌɡærənˈtiː/',meaning:'保证',mnemonic:'guar(保卫)+antee→保证'},
  {root:'indemnity',phonetic:'/ɪnˈdemnəti/',meaning:'赔偿',mnemonic:'in(不)+demn(伤害)+ity→赔偿'},
  {root:'bond',phonetic:'/bɒnd/',meaning:'保证金',mnemonic:'音似绑的→绑定的保证金'},
  {root:'surety',phonetic:'/ˈʃʊərəti/',meaning:'担保',mnemonic:'sure(确定)+ty→担保'},
  {root:'security',phonetic:'/sɪˈkjʊərəti/',meaning:'担保',mnemonic:'secur(安全)+ity→担保'},
  {root:'collateral',phonetic:'/kəˈlætərəl/',meaning:'抵押品',mnemonic:'col(一起)+lateral(侧面)→抵押品'},
  {root:'pledge',phonetic:'/pledʒ/',meaning:'抵押',mnemonic:'pledg(保证)+e→抵押'},
  {root:'lien',phonetic:'/liːn/',meaning:'留置权',mnemonic:'li(里)+en→留置权'},
  {root:'encumbrance',phonetic:'/ɪnˈkʌmbrəns/',meaning:'负担',mnemonic:'en(使)+cumbr(阻碍)+ance→负担'},
  {root:'easement',phonetic:'/ˈiːzmənt/',meaning:'地役权',mnemonic:'ease(容易)+ment→地役权'},
  {root:'covenant',phonetic:'/ˈkʌvənənt/',meaning:'契约',mnemonic:'co(一起)+ven(来)+ant→契约'},
  {root:'deed',phonetic:'/diːd/',meaning:'契约',mnemonic:'deed(行为)→契约'},
  {root:'conveyance',phonetic:'/kənˈveɪəns/',meaning:'转让',mnemonic:'con(一起)+vey(路)+ance→转让'},
  {root:'assignment',phonetic:'/əˈsaɪnmənt/',meaning:'转让',mnemonic:'as(向)+sign(标记)+ment→转让'},
  {root:'novation',phonetic:'/nəʊˈveɪʃn/',meaning:'合同更新',mnemonic:'nov(新)+ation→合同更新'},
  {root:'rescission',phonetic:'/rɪˈsɪʒn/',meaning:'撤销',mnemonic:'re(回)+sciss(切)+ion→撤销'},
  {root:'repudiation',phonetic:'/rɪˌpjuːdiˈeɪʃn/',meaning:'拒绝',mnemonic:'re(反)+pudi(羞耻)+ation→拒绝'},
  {root:'breach',phonetic:'/briːtʃ/',meaning:'违约',mnemonic:'breach(破坏)→违约'},
  {root:'default',phonetic:'/dɪˈfɔːlt/',meaning:'违约',mnemonic:'de(下)+fault(错误)→违约'},
  {root:'infringement',phonetic:'/ɪnˈfrɪndʒmənt/',meaning:'侵权',mnemonic:'in(入)+fring(破坏)+ement→侵权'},
  {root:'tort',phonetic:'/tɔːt/',meaning:'侵权',mnemonic:'tort(扭曲)→侵权'},
  {root:'negligence',phonetic:'/ˈneɡlɪdʒəns/',meaning:'过失',mnemonic:'neg(不)+lig(选择)+ence→过失'},
  {root:'nuisance',phonetic:'/ˈnjuːsns/',meaning:'妨害',mnemonic:'nuis(伤害)+ance→妨害'},
  {root:'trespass',phonetic:'/ˈtrespəs/',meaning:'侵入',mnemonic:'tres(穿过)+pass→侵入'},
  {root:'detriment',phonetic:'/ˈdetrɪmənt/',meaning:'损害',mnemonic:'de(下)+tri(擦)+ment→损害'},
  {root:'prejudice',phonetic:'/ˈpredʒudɪs/',meaning:'损害',mnemonic:'pre(前)+judic(判断)+e→损害'},
  {root:'waiver',phonetic:'/ˈweɪvə/',meaning:'弃权',mnemonic:'waiv(放弃)+er→弃权'},
  {root:'release',phonetic:'/rɪˈliːs/',meaning:'解除',mnemonic:'re(回)+lease(松)→解除'},
  {root:'discharge',phonetic:'/dɪsˈtʃɑːdʒ/',meaning:'解除',mnemonic:'dis(分开)+charge(装载)→解除'},
  {root:'exoneration',phonetic:'/ɪɡˌzɒnəˈreɪʃn/',meaning:'免除',mnemonic:'ex(出)+oner(负担)+ation→免除'},
  {root:'exemption',phonetic:'/ɪɡˈzempʃn/',meaning:'豁免',mnemonic:'ex(出)+empt(拿)+ion→豁免'},
  {root:'immunity',phonetic:'/ɪˈmjuːnəti/',meaning:'豁免',mnemonic:'im(不)+mun(责任)+ity→豁免'},
  {root:'privilege',phonetic:'/ˈprɪvəlɪdʒ/',meaning:'特权',mnemonic:'privi(私人)+lege(法律)→特权'},
  {root:'prerogative',phonetic:'/prɪˈrɒɡətɪv/',meaning:'特权',mnemonic:'pre(前)+rog(问)+ative→特权'},
  {root:'franchise',phonetic:'/ˈfræntʃaɪz/',meaning:'特许',mnemonic:'fran(自由)+chise→特许'},
  {root:'concession',phonetic:'/kənˈseʃn/',meaning:'特许',mnemonic:'con(一起)+cess(走)+ion→特许'},
  {root:'license',phonetic:'/ˈlaɪsns/',meaning:'许可证',mnemonic:'lic(允许)+ense→许可证'},
  {root:'permit',phonetic:'/ˈpɜːmɪt/',meaning:'许可',mnemonic:'per(通过)+mit(送)→许可'},
  {root:'consent',phonetic:'/kənˈsent/',meaning:'同意',mnemonic:'con(一起)+sent(感觉)→同意'},
  {root:'approval',phonetic:'/əˈpruːvl/',meaning:'批准',mnemonic:'ap(向)+prov(测试)+al→批准'},
  {root:'ratification',phonetic:'/ˌrætɪfɪˈkeɪʃn/',meaning:'批准',mnemonic:'rati(计算)+fication→批准'},
  {root:'endorsement',phonetic:'/ɪnˈdɔːsmənt/',meaning:'认可',mnemonic:'en(入)+dorse(背)+ment→认可'},
  {root:'sanction',phonetic:'/ˈsæŋkʃn/',meaning:'批准',mnemonic:'sanc(神圣)+tion→批准'},
  {root:'authorization',phonetic:'/ˌɔːθəraɪˈzeɪʃn/',meaning:'授权',mnemonic:'author(作者)+ization→授权'},
  {root:'accreditation',phonetic:'/əˌkredɪˈteɪʃn/',meaning:'认证',mnemonic:'ac(向)+cred(相信)+itation→认证'},
  {root:'certification',phonetic:'/ˌsɜːtɪfɪˈkeɪʃn/',meaning:'认证',mnemonic:'cert(确定)+ification→认证'},
  {root:'validation',phonetic:'/ˌvælɪˈdeɪʃn/',meaning:'验证',mnemonic:'val(价值)+idation→验证'},
  {root:'verification',phonetic:'/ˌverɪfɪˈkeɪʃn/',meaning:'核实',mnemonic:'ver(真实)+ification→核实'},
  {root:'attestation',phonetic:'/ˌæteˈsteɪʃn/',meaning:'证明',mnemonic:'at(向)+test(证明)+ation→证明'},
  {root:'affidavit',phonetic:'/ˌæfɪˈdeɪvɪt/',meaning:'宣誓书',mnemonic:'af(向)+fid(信任)+avit→宣誓书'},
  {root:'deposition',phonetic:'/ˌdepəˈzɪʃn/',meaning:'证词',mnemonic:'de(下)+posit(放)+ion→证词'},
  {root:'testimony',phonetic:'/ˈtestɪməni/',meaning:'证词',mnemonic:'testi(测试)+mony→证词'},
  {root:'evidence',phonetic:'/ˈevɪdəns/',meaning:'证据',mnemonic:'e(出)+vid(看)+ence→证据'},
  {root:'proof',phonetic:'/pruːf/',meaning:'证明',mnemonic:'proof(证据)→证明'},
  {root:'exhibit',phonetic:'/ɪɡˈzɪbɪt/',meaning:'证据',mnemonic:'ex(出)+hibit(持)→证据'},
  {root:'demonstrate',phonetic:'/ˈdemənstreɪt/',meaning:'证明',mnemonic:'de(完全)+monstr(显示)+ate→证明'},
  {root:'manifest',phonetic:'/ˈmænɪfest/',meaning:'表明',mnemonic:'mani(手)+fest(打)→表明'},
  {root:'substantiate',phonetic:'/səbˈstænʃieɪt/',meaning:'证实',mnemonic:'sub(下)+stant(站)+iate→证实'},
  {root:'corroborate',phonetic:'/kəˈrɒbəreɪt/',meaning:'确证',mnemonic:'cor(一起)+robor(力量)+ate→确证'},
  {root:'authenticate',phonetic:'/ɔːˈθentɪkeɪt/',meaning:'认证',mnemonic:'authen(真实)+ticate→认证'},
  {root:'notarize',phonetic:'/ˈnəʊtəraɪz/',meaning:'公证',mnemonic:'not(注意)+arize→公证'},
  {root:'witness',phonetic:'/ˈwɪtnəs/',meaning:'证人',mnemonic:'wit(知道)+ness→证人'},
  {root:'observer',phonetic:'/əbˈzɜːvə/',meaning:'观察员',mnemonic:'ob(向)+serv(保持)+er→观察员'},
  {root:'surveyor',phonetic:'/səˈveɪə/',meaning:'测量员',mnemonic:'survey(测量)+or→测量员'},
  {root:'inspector',phonetic:'/ɪnˈspektə/',meaning:'检查员',mnemonic:'in(入)+spect(看)+or→检查员'},
  {root:'examiner',phonetic:'/ɪɡˈzæmɪnə/',meaning:'审查员',mnemonic:'exam(考试)+in+er→审查员'},
  {root:'auditor',phonetic:'/ˈɔːdɪtə/',meaning:'审计员',mnemonic:'audit(审计)+or→审计员'},
  {root:'assessor',phonetic:'/əˈsesə/',meaning:'评估员',mnemonic:'assess(评估)+or→评估员'},
  {root:'appraiser',phonetic:'/əˈpreɪzə/',meaning:'估价员',mnemonic:'apprais(评价)+er→估价员'},
  {root:'valuer',phonetic:'/ˈvæljuːə/',meaning:'估价师',mnemonic:'valu(价值)+er→估价师'},
  {root:'quantity',phonetic:'/ˈkwɒntəti/',meaning:'数量',mnemonic:'quant(多少)+ity→数量'},
  {root:'estimator',phonetic:'/ˈestɪmeɪtə/',meaning:'估算师',mnemonic:'estimat(估计)+or→估算师'},
  {root:'scheduler',phonetic:'/ˈʃedjuːlə/',meaning:'计划员',mnemonic:'schedul(计划)+er→计划员'},
  {root:'planner',phonetic:'/ˈplænə/',meaning:'规划师',mnemonic:'plan(计划)+ner→规划师'},
  {root:'coordinator',phonetic:'/kəʊˈɔːdɪneɪtə/',meaning:'协调员',mnemonic:'co(一起)+ordin(顺序)+ator→协调员'},
  {root:'facilitator',phonetic:'/fəˈsɪlɪteɪtə/',meaning:'协调人',mnemonic:'facilit(容易)+ator→协调人'},
  {root:'mediator',phonetic:'/ˈmiːdieɪtə/',meaning:'调解人',mnemonic:'medi(中间)+ator→调解人'},
  {root:'arbitrator',phonetic:'/ˈɑːbɪtreɪtə/',meaning:'仲裁人',mnemonic:'arbitr(判断)+ator→仲裁人'},
  {root:'adjudicator',phonetic:'/əˈdʒuːdɪkeɪtə/',meaning:'裁决人',mnemonic:'ad(向)+judic(判断)+ator→裁决人'},
  {root:'umpire',phonetic:'/ˈʌmpaɪə/',meaning:'仲裁人',mnemonic:'um(不)+pire→仲裁人'},
  {root:'referee',phonetic:'/ˌrefəˈriː/',meaning:'裁判',mnemonic:'refer(参考)+ee→裁判'},
  {root:'tribunal',phonetic:'/traɪˈbjuːnl/',meaning:'法庭',mnemonic:'tribun(部落)+al→法庭'},
  {root:'court',phonetic:'/kɔːt/',meaning:'法院',mnemonic:'court(庭院)→法院'},
  {root:'judiciary',phonetic:'/dʒuˈdɪʃəri/',meaning:'司法部',mnemonic:'judic(判断)+iary→司法部'},
  {root:'magistrate',phonetic:'/ˈmædʒɪstreɪt/',meaning:'地方法官',mnemonic:'magistr(主人)+ate→地方法官'},
  {root:'solicitor',phonetic:'/səˈlɪsɪtə/',meaning:'事务律师',mnemonic:'solicit(请求)+or→事务律师'},
  {root:'barrister',phonetic:'/ˈbærɪstə/',meaning:'出庭律师',mnemonic:'bar(法庭)+rister→出庭律师'},
  {root:'counsel',phonetic:'/ˈkaʊnsl/',meaning:'法律顾问',mnemonic:'coun(一起)+sel→法律顾问'},
  {root:'attorney',phonetic:'/əˈtɜːni/',meaning:'律师',mnemonic:'at(向)+torn(转)+ey→律师'},
  {root:'advocate',phonetic:'/ˈædvəkət/',meaning:'辩护人',mnemonic:'ad(向)+voc(叫)+ate→辩护人'},
  {root:'counselor',phonetic:'/ˈkaʊnsələ/',meaning:'顾问',mnemonic:'counsel(建议)+or→顾问'},
  {root:'consultant',phonetic:'/kənˈsʌltənt/',meaning:'顾问',mnemonic:'consult(咨询)+ant→顾问'},
  {root:'adviser',phonetic:'/ədˈvaɪzə/',meaning:'顾问',mnemonic:'advis(建议)+er→顾问'},
  {root:'expert',phonetic:'/ˈekspɜːt/',meaning:'专家',mnemonic:'ex(出)+pert(尝试)→专家'},
  {root:'specialist',phonetic:'/ˈspeʃəlɪst/',meaning:'专家',mnemonic:'special(特别)+ist→专家'},
  {root:'technician',phonetic:'/tekˈnɪʃn/',meaning:'技术员',mnemonic:'techn(技术)+ician→技术员'},
  {root:'drafter',phonetic:'/ˈdrɑːftə/',meaning:'绘图员',mnemonic:'draft(草图)+er→绘图员'},
  {root:'draftsman',phonetic:'/ˈdrɑːftsmən/',meaning:'制图员',mnemonic:'draft(草图)+sman→制图员'},
  {root:'foreman',phonetic:'/ˈfɔːmən/',meaning:'工头',mnemonic:'fore(前)+man(人)→工头'},
  {root:'ganger',phonetic:'/ˈɡæŋə/',meaning:'领班',mnemonic:'gang(队)+er→领班'},
  {root:'chargehand',phonetic:'/ˈtʃɑːdʒhænd/',meaning:'工长',mnemonic:'charge(负责)+hand(手)→工长'},
  {root:'operative',phonetic:'/ˈɒpərətɪv/',meaning:'技工',mnemonic:'oper(工作)+ative→技工'},
  {root:'tradesman',phonetic:'/ˈtreɪdzmən/',meaning:'工匠',mnemonic:'trade(行业)+sman→工匠'},
  {root:'journeyman',phonetic:'/ˈdʒɜːnimən/',meaning:'熟练工',mnemonic:'journey(旅行)+man→熟练工'},
  {root:'apprentice',phonetic:'/əˈprentɪs/',meaning:'学徒',mnemonic:'ap(向)+prent(学习)+ice→学徒'},
  {root:'trainee',phonetic:'/treɪˈniː/',meaning:'实习生',mnemonic:'train(训练)+ee→实习生'},
  {root:'probationer',phonetic:'/prəˈbeɪʃnə/',meaning:'试用员',mnemonic:'prob(测试)+ation+er→试用员'},
  {root:'intern',phonetic:'/ˈɪntɜːn/',meaning:'实习生',mnemonic:'intern(内部)→实习生'},
  {root:'cadet',phonetic:'/kəˈdet/',meaning:'学员',mnemonic:'cad(掉落)+et→学员'},
  {root:'novice',phonetic:'/ˈnɒvɪs/',meaning:'新手',mnemonic:'nov(新)+ice→新手'},
  {root:'tyro',phonetic:'/ˈtaɪrəʊ/',meaning:'初学者',mnemonic:'tyro→初学者'},
  {root:'neophyte',phonetic:'/ˈniːəfaɪt/',meaning:'初学者',mnemonic:'neo(新)+phyte(植物)→初学者'},
  {root:'rookie',phonetic:'/ˈrʊki/',meaning:'新手',mnemonic:'rook(欺骗)+ie→新手'},
  {root:'greenhorn',phonetic:'/ˈɡriːnhɔːn/',meaning:'生手',mnemonic:'green(绿)+horn(角)→生手'},
  {root:'beginner',phonetic:'/bɪˈɡɪnə/',meaning:'初学者',mnemonic:'begin(开始)+ner→初学者'},
  {root:'learner',phonetic:'/ˈlɜːnə/',meaning:'学习者',mnemonic:'learn(学习)+er→学习者'},
  {root:'student',phonetic:'/ˈstjuːdnt/',meaning:'学生',mnemonic:'stud(学习)+ent→学生'},
  {root:'disciple',phonetic:'/dɪˈsaɪpl/',meaning:'门徒',mnemonic:'dis(分开)+cip(拿)+le→门徒'},
  {root:'follower',phonetic:'/ˈfɒləʊə/',meaning:'追随者',mnemonic:'follow(跟随)+er→追随者'},
  {root:'supporter',phonetic:'/səˈpɔːtə/',meaning:'支持者',mnemonic:'support(支持)+er→支持者'},
  {root:'backer',phonetic:'/ˈbækə/',meaning:'支持者',mnemonic:'back(支持)+er→支持者'},
  {root:'patron',phonetic:'/ˈpeɪtrən/',meaning:'赞助人',mnemonic:'patr(父亲)+on→赞助人'},
  {root:'sponsor',phonetic:'/ˈspɒnsə/',meaning:'赞助商',mnemonic:'spons(承诺)+or→赞助商'},
  {root:'benefactor',phonetic:'/ˈbenɪfæktə/',meaning:'恩人',mnemonic:'bene(好)+fact(做)+or→恩人'},
  {root:'donor',phonetic:'/ˈdəʊnə/',meaning:'捐赠者',mnemonic:'don(给)+or→捐赠者'},
  {root:'contributor',phonetic:'/kənˈtrɪbjətə/',meaning:'贡献者',mnemonic:'con(一起)+tribut(给)+or→贡献者'},
  {root:'member',phonetic:'/ˈmembə/',meaning:'成员',mnemonic:'membr(肢体)+er→成员'},
  {root:'colleague',phonetic:'/ˈkɒliːɡ/',meaning:'同事',mnemonic:'col(一起)+league(联盟)→同事'},
  {root:'peer',phonetic:'/pɪə/',meaning:'同僚',mnemonic:'peer(同等)→同僚'},
  {root:'counterpart',phonetic:'/ˈkaʊntəpɑːt/',meaning:'对应人',mnemonic:'counter(相对)+part(部分)→对应人'},
  {root:'adversary',phonetic:'/ˈædvəsəri/',meaning:'对手',mnemonic:'ad(向)+vers(转)+ary→对手'},
  {root:'opponent',phonetic:'/əˈpəʊnənt/',meaning:'对手',mnemonic:'op(反)+pon(放)+ent→对手'},
  {root:'rival',phonetic:'/ˈraɪvl/',meaning:'竞争者',mnemonic:'riv(河)+al→竞争者'},
  {root:'competitor',phonetic:'/kəmˈpetɪtə/',meaning:'竞争者',mnemonic:'com(一起)+pet(追求)+itor→竞争者'},
  {root:'candidate',phonetic:'/ˈkændɪdət/',meaning:'候选人',mnemonic:'candid(白)+ate→候选人'},
  {root:'nominee',phonetic:'/ˌnɒmɪˈniː/',meaning:'被提名者',mnemonic:'nomin(名字)+ee→被提名者'},
  {root:'appointee',phonetic:'/əˌpɔɪnˈtiː/',meaning:'被任命者',mnemonic:'appoint(任命)+ee→被任命者'},
  {root:'licensee',phonetic:'/ˌlaɪsnˈsiː/',meaning:'持牌人',mnemonic:'licens(许可)+ee→持牌人'},
  {root:'lessee',phonetic:'/leˈsiː/',meaning:'承租人',mnemonic:'less(出租)+ee→承租人'},
  {root:'lessor',phonetic:'/leˈsɔː/',meaning:'出租人',mnemonic:'less(出租)+or→出租人'},
  {root:'mortgagor',phonetic:'/ˈmɔːɡɪdʒɔː/',meaning:'抵押人',mnemonic:'mortgage(抵押)+or→抵押人'},
  {root:'mortgagee',phonetic:'/ˌmɔːɡɪˈdʒiː/',meaning:'抵押权人',mnemonic:'mortgage(抵押)+ee→抵押权人'},
  {root:'trustee',phonetic:'/trʌˈstiː/',meaning:'受托人',mnemonic:'trust(信任)+ee→受托人'},
  {root:'beneficiary',phonetic:'/ˌbenɪˈfɪʃəri/',meaning:'受益人',mnemonic:'bene(好)+fic(做)+iary→受益人'},
  {root:'heir',phonetic:'/eə/',meaning:'继承人',mnemonic:'heir(继承)→继承人'},
  {root:'successor',phonetic:'/səkˈsesə/',meaning:'继任者',mnemonic:'suc(下)+cess(走)+or→继任者'},
  {root:'predecessor',phonetic:'/ˈpredəsesə/',meaning:'前任',mnemonic:'pre(前)+de(下)+cess(走)+or→前任'},
  {root:'ancestor',phonetic:'/ˈænsestə/',meaning:'祖先',mnemonic:'an(前)+cest(走)+or→祖先'},
  {root:'descendant',phonetic:'/dɪˈsendənt/',meaning:'后裔',mnemonic:'de(下)+scend(爬)+ant→后裔'},
  {root:'offspring',phonetic:'/ˈɒfsprɪŋ/',meaning:'后代',mnemonic:'off(离开)+spring(跳)→后代'},
  {root:'progeny',phonetic:'/ˈprɒdʒəni/',meaning:'后代',mnemonic:'pro(前)+gen(生)+y→后代'},
  {root:'posterity',phonetic:'/pɒˈsterəti/',meaning:'子孙',mnemonic:'poster(后)+ity→子孙'},
  {root:'sibling',phonetic:'/ˈsɪblɪŋ/',meaning:'兄弟姐妹',mnemonic:'sib(亲戚)+ling→兄弟姐妹'},
  {root:'kin',phonetic:'/kɪn/',meaning:'亲属',mnemonic:'kin(亲属)→亲属'},
  {root:'kindred',phonetic:'/ˈkɪndrɪd/',meaning:'亲戚',mnemonic:'kin(亲属)+dred→亲戚'},
  {root:'relative',phonetic:'/ˈrelətɪv/',meaning:'亲戚',mnemonic:'re(回)+lat(带来)+ive→亲戚'},
  {root:'affinity',phonetic:'/əˈfɪnəti/',meaning:'姻亲',mnemonic:'af(向)+fin(边界)+ity→姻亲'},
  {root:'consanguinity',phonetic:'/ˌkɒnsæŋˈɡwɪnəti/',meaning:'血亲',mnemonic:'con(一起)+sanguin(血)+ity→血亲'},
  {root:'spouse',phonetic:'/spaʊs/',meaning:'配偶',mnemonic:'spous(承诺)+e→配偶'},
  {root:'partner',phonetic:'/ˈpɑːtnə/',meaning:'合伙人',mnemonic:'part(部分)+ner→合伙人'},
  {root:'cofounder',phonetic:'/ˌkəʊˈfaʊndə/',meaning:'联合创始人',mnemonic:'co(一起)+found(创立)+er→联合创始人'},
  {root:'promoter',phonetic:'/prəˈməʊtə/',meaning:'发起人',mnemonic:'pro(向前)+mot(动)+er→发起人'},
  {root:'founder',phonetic:'/ˈfaʊndə/',meaning:'创始人',mnemonic:'found(创立)+er→创始人'},
  {root:'originator',phonetic:'/əˈrɪdʒɪneɪtə/',meaning:'创始人',mnemonic:'origin(起源)+ator→创始人'},
  {root:'initiator',phonetic:'/ɪˈnɪʃieɪtə/',meaning:'发起者',mnemonic:'init(开始)+iator→发起者'},
  {root:'agitator',phonetic:'/ˈædʒɪteɪtə/',meaning:'鼓动者',mnemonic:'agit(搅动)+ator→鼓动者'},
  {root:'ringleader',phonetic:'/ˈrɪŋliːdə/',meaning:'头目',mnemonic:'ring(环)+leader(领导)→头目'},
  {root:'mastermind',phonetic:'/ˈmɑːstəmaɪnd/',meaning:'主谋',mnemonic:'master(主人)+mind(头脑)→主谋'},
  {root:'architect',phonetic:'/ˈɑːkɪtekt/',meaning:'建筑师',mnemonic:'archi(首要)+tect(建造)→建筑师'},
  {root:'designer',phonetic:'/dɪˈzaɪnə/',meaning:'设计师',mnemonic:'design(设计)+er→设计师'},
  {root:'engineer',phonetic:'/ˌendʒɪˈnɪə/',meaning:'工程师',mnemonic:'engine(引擎)+er→工程师'},
  {root:'superintendent',phonetic:'/ˌsuːpərɪnˈtendənt/',meaning:'总监',mnemonic:'super(上)+intend(打算)+ent→总监'},
  {root:'supervisor',phonetic:'/ˈsuːpəvaɪzə/',meaning:'监督师',mnemonic:'super(上)+vis(看)+or→监督师'}
];

// 生成完整格式的条目
const entries = [];
for (let i = 0; i < 300; i++) {
  const id = 501 + i;
  const r = civilRoots[i];

  // 生成短语
  const phrases = [
    `${r.root} ${r.meaning}`,
    `${r.root} document ${r.meaning}文件`,
    `${r.root} clause ${r.meaning}条款`,
    `${r.root} period ${r.meaning}期限`
  ];

  // 生成4个相关单词
  const words = [
    {
      word: r.root,
      phonetic: r.phonetic,
      partOfSpeech: 'n.',
      meaning: r.meaning,
      memoryTip: r.mnemonic,
      root: r.root,
      rootPhonetic: r.phonetic,
      rootMeaning: r.meaning,
      rootPhrases: phrases,
      wordPhrases: phrases
    },
    {
      word: `${r.root}ing`,
      phonetic: r.phonetic,
      partOfSpeech: 'n.',
      meaning: `${r.meaning}中`,
      memoryTip: `${r.root} + ing`,
      root: r.root,
      rootPhonetic: r.phonetic,
      rootMeaning: r.meaning,
      rootPhrases: phrases,
      wordPhrases: phrases
    },
    {
      word: `${r.root}ed`,
      phonetic: r.phonetic,
      partOfSpeech: 'adj.',
      meaning: `${r.meaning}的`,
      memoryTip: `${r.root} + ed`,
      root: r.root,
      rootPhonetic: r.phonetic,
      rootMeaning: r.meaning,
      rootPhrases: phrases,
      wordPhrases: phrases
    },
    {
      word: `${r.root}er`,
      phonetic: r.phonetic,
      partOfSpeech: 'n.',
      meaning: `${r.meaning}人`,
      memoryTip: `${r.root} + er`,
      root: r.root,
      rootPhonetic: r.phonetic,
      rootMeaning: r.meaning,
      rootPhrases: phrases,
      wordPhrases: phrases
    }
  ];

  entries.push({
    id: id,
    root: r.root,
    phonetic: r.phonetic,
    partOfSpeech: '名词',
    frequency: id,
    category: '土木',
    words: words,
    phrases: phrases,
    mnemonic: r.mnemonic,
    meaning: r.meaning
  });
}

// 读取原文件前500条
const originalData = JSON.parse(fs.readFileSync('f:/claudeanli/beidanci3/src/data/civil-engineering.json', 'utf8'));
const first500 = originalData.slice(0, 500);

// 合并数据
const finalData = [...first500, ...entries];

// 写入文件
fs.writeFileSync('f:/claudeanli/beidanci3/src/data/civil-engineering.json', JSON.stringify(finalData, null, 2));
console.log('Data fixed successfully');
console.log('Total entries:', finalData.length);
console.log('First id:', finalData[0].id);
console.log('Last id:', finalData[finalData.length-1].id);
