const fs = require('fs');

// 定义300个词根数据（简化版）
const rootData = [
  // 201-250 高频
  {r:"packet",p:"/ˈpækɪt/",m:"数据包；分组",pos:"名词"},
  {r:"router",p:"/ˈruːtər/",m:"路由器",pos:"名词"},
  {r:"encrypt",p:"/ɪnˈkrɪpt/",m:"加密",pos:"动词"},
  {r:"decrypt",p:"/diːˈkrɪpt/",m:"解密",pos:"动词"},
  {r:"schema",p:"/ˈskiːmə/",m:"模式；架构",pos:"名词"},
  {r:"query",p:"/ˈkwɪəri/",m:"查询",pos:"名词"},
  {r:"index",p:"/ˈɪndeks/",m:"索引",pos:"名词"},
  {r:"compile",p:"/kəmˈpaɪl/",m:"编译",pos:"动词"},
  {r:"debug",p:"/diːˈbʌɡ/",m:"调试",pos:"动词"},
  {r:"deploy",p:"/dɪˈplɔɪ/",m:"部署",pos:"动词"},
  {r:"render",p:"/ˈrendər/",m:"渲染",pos:"动词"},
  {r:"event",p:"/ɪˈvent/",m:"事件",pos:"名词"},
  {r:"state",p:"/steɪt/",m:"状态",pos:"名词"},
  {r:"props",p:"/prɒps/",m:"属性；道具",pos:"名词"},
  {r:"hook",p:"/hʊk/",m:"钩子",pos:"名词"},
  {r:"endpoint",p:"/ˈendpɔɪnt/",m:"端点",pos:"名词"},
  {r:"middleware",p:"/ˈmɪdlwer/",m:"中间件",pos:"名词"},
  {r:"handler",p:"/ˈhændlər/",m:"处理器",pos:"名词"},
  {r:"container",p:"/kənˈteɪnər/",m:"容器",pos:"名词"},
  {r:"image",p:"/ˈɪmɪdʒ/",m:"镜像",pos:"名词"},
  {r:"pod",p:"/pɒd/",m:"容器组",pos:"名词"},
  {r:"cluster",p:"/ˈklʌstər/",m:"集群",pos:"名词"},
  {r:"node",p:"/nəʊd/",m:"节点",pos:"名词"},
  {r:"gateway",p:"/ˈɡeɪtweɪ/",m:"网关",pos:"名词"},
  {r:"subnet",p:"/ˈsʌbnet/",m:"子网",pos:"名词"},
  {r:"bandwidth",p:"/ˈbændwɪdθ/",m:"带宽",pos:"名词"},
  {r:"latency",p:"/ˈleɪtnsi/",m:"延迟",pos:"名词"},
  {r:"throughput",p:"/ˈθruːpʊt/",m:"吞吐量",pos:"名词"},
  {r:"cipher",p:"/ˈsaɪfər/",m:"密码",pos:"名词"},
  {r:"firewall",p:"/ˈfaɪərwɔːl/",m:"防火墙",pos:"名词"},
  {r:"virus",p:"/ˈvaɪrəs/",m:"病毒",pos:"名词"},
  {r:"malware",p:"/ˈmælwer/",m:"恶意软件",pos:"名词"},
  {r:"phishing",p:"/ˈfɪʃɪŋ/",m:"钓鱼攻击",pos:"名词"},
  {r:"auth",p:"/ɔːθ/",m:"认证",pos:"名词"},
  {r:"join",p:"/dʒɔɪn/",m:"连接",pos:"动词"},
  {r:"backup",p:"/ˈbækʌp/",m:"备份",pos:"名词"},
  {r:"restore",p:"/rɪˈstɔːr/",m:"恢复",pos:"动词"},
  {r:"migrate",p:"/ˈmaɪɡreɪt/",m:"迁移",pos:"动词"},
  {r:"sync",p:"/sɪŋk/",m:"同步",pos:"动词"},
  {r:"build",p:"/bɪld/",m:"构建",pos:"动词"},
  {r:"release",p:"/rɪˈliːs/",m:"发布",pos:"动词"},
  {r:"version",p:"/ˈvɜːrʒn/",m:"版本",pos:"名词"},
  {r:"branch",p:"/brɑːntʃ/",m:"分支",pos:"名词"},
  {r:"merge",p:"/mɜːrdʒ/",m:"合并",pos:"动词"},
  {r:"commit",p:"/kəˈmɪt/",m:"提交",pos:"动词"},
  {r:"repository",p:"/rɪˈpɒzətri/",m:"仓库",pos:"名词"},
  {r:"clone",p:"/kləʊn/",m:"克隆",pos:"动词"},
  {r:"fork",p:"/fɔːrk/",m:"复刻",pos:"动词"},
  {r:"pull",p:"/pʊl/",m:"拉取",pos:"动词"},
  {r:"push",p:"/pʊʃ/",m:"推送",pos:"动词"},
  // 251-300
  {r:"DOM",p:"/diː əʊ ˈem/",m:"文档对象模型",pos:"名词"},
  {r:"component",p:"/kəmˈpəʊnənt/",m:"组件",pos:"名词"},
  {r:"service",p:"/ˈsɜːrvɪs/",m:"服务",pos:"名词"},
  {r:"model",p:"/ˈmɒdl/",m:"模型",pos:"名词"},
  {r:"controller",p:"/kənˈtrəʊlər/",m:"控制器",pos:"名词"},
  {r:"view",p:"/vjuː/",m:"视图",pos:"名词"},
  {r:"template",p:"/ˈtempleɪt/",m:"模板",pos:"名词"},
  {r:"binding",p:"/ˈbaɪndɪŋ/",m:"绑定",pos:"名词"},
  {r:"directive",p:"/dəˈrektɪv/",m:"指令",pos:"名词"},
  {r:"pipeline",p:"/ˈpaɪplaɪn/",m:"管道",pos:"名词"},
  {r:"stage",p:"/steɪdʒ/",m:"阶段",pos:"名词"},
  {r:"artifact",p:"/ˈɑːrtɪfækt/",m:"构建产物",pos:"名词"},
  {r:"trigger",p:"/ˈtrɪɡər/",m:"触发器",pos:"名词"},
  {r:"schedule",p:"/ˈʃedjuːl/",m:"调度",pos:"名词"},
  {r:"cron",p:"/krɒn/",m:"定时任务",pos:"名词"},
  {r:"job",p:"/dʒɒb/",m:"任务",pos:"名词"},
  {r:"worker",p:"/ˈwɜːrkər/",m:"工作进程",pos:"名词"},
  {r:"queue",p:"/kjuː/",m:"队列",pos:"名词"},
  {r:"stack",p:"/stæk/",m:"栈",pos:"名词"},
  {r:"heap",p:"/hiːp/",m:"堆",pos:"名词"},
  {r:"cache",p:"/kæʃ/",m:"缓存",pos:"名词"},
  {r:"buffer",p:"/ˈbʌfər/",m:"缓冲区",pos:"名词"},
  {r:"stream",p:"/striːm/",m:"流",pos:"名词"},
  {r:"pipe",p:"/paɪp/",m:"管道",pos:"名词"},
  {r:"socket",p:"/ˈsɒkɪt/",m:"套接字",pos:"名词"},
  {r:"port",p:"/pɔːrt/",m:"端口",pos:"名词"},
  {r:"protocol",p:"/ˈprəʊtəkɒl/",m:"协议",pos:"名词"},
  {r:"session",p:"/ˈseʃn/",m:"会话",pos:"名词"},
  {r:"cookie",p:"/ˈkʊki/",m:"Cookie",pos:"名词"},
  {r:"token",p:"/ˈtəʊkən/",m:"令牌",pos:"名词"},
  {r:"header",p:"/ˈhedər/",m:"头部",pos:"名词"},
  {r:"payload",p:"/ˈpeɪləʊd/",m:"载荷",pos:"名词"},
  {r:"frame",p:"/freɪm/",m:"帧",pos:"名词"},
  {r:"segment",p:"/ˈseɡmənt/",m:"段",pos:"名词"},
  {r:"datagram",p:"/ˈdeɪtəɡræm/",m:"数据报",pos:"名词"},
  {r:"broadcast",p:"/ˈbrɔːdkɑːst/",m:"广播",pos:"动词"},
  {r:"multicast",p:"/ˈmʌltikɑːst/",m:"组播",pos:"动词"},
  {r:"unicast",p:"/ˈjuːnikɑːst/",m:"单播",pos:"动词"},
  {r:"anycast",p:"/ˈenikɑːst/",m:"任播",pos:"动词"},
  {r:"topology",p:"/təˈpɒlədʒi/",m:"拓扑",pos:"名词"},
  {r:"mesh",p:"/meʃ/",m:"网状",pos:"名词"},
  {r:"proxy",p:"/ˈprɒksi/",m:"代理",pos:"名词"},
  {r:"tunnel",p:"/ˈtʌnl/",m:"隧道",pos:"名词"},
  {r:"VPN",p:"/ˌviː piː ˈen/",m:"虚拟专用网络",pos:"名词"},
  {r:"NAT",p:"/en eɪ tiː/",m:"网络地址转换",pos:"名词"},
  {r:"DNS",p:"/diː en ˈes/",m:"域名系统",pos:"名词"},
  {r:"DHCP",p:"/diː eɪtʃ siː piː/",m:"动态主机配置",pos:"名词"},
  {r:"ARP",p:"/eɪ ɑːr piː/",m:"地址解析",pos:"名词"},
  {r:"MAC",p:"/em eɪ siː/",m:"媒体访问控制",pos:"名词"},
  {r:"WIFI",p:"/ˈwaɪfaɪ/",m:"无线网络",pos:"名词"},
  {r:"SSL",p:"/es es el/",m:"安全套接层",pos:"名词"},
  // 301-350
  {r:"TLS",p:"/tiː el es/",m:"传输层安全",pos:"名词"},
  {r:"HTTPS",p:"/eɪtʃ tiː tiː piː es/",m:"安全HTTP",pos:"名词"},
  {r:"SSH",p:"/es es eɪtʃ/",m:"安全外壳",pos:"名词"},
  {r:"FTP",p:"/ef tiː piː/",m:"文件传输",pos:"名词"},
  {r:"SFTP",p:"/es ef tiː piː/",m:"安全FTP",pos:"名词"},
  {r:"SMTP",p:"/es em tiː piː/",m:"邮件传输",pos:"名词"},
  {r:"IMAP",p:"/aɪ mæp/",m:"邮件访问",pos:"名词"},
  {r:"POP3",p:"/piː əʊ piː θriː/",m:"邮局协议",pos:"名词"},
  {r:"HTTP",p:"/eɪtʃ tiː tiː piː/",m:"超文本传输",pos:"名词"},
  {r:"TCP",p:"/tiː siː piː/",m:"传输控制",pos:"名词"},
  {r:"UDP",p:"/juː diː piː/",m:"用户数据报",pos:"名词"},
  {r:"IP",p:"/aɪ piː/",m:"互联网协议",pos:"名词"},
  {r:"ICMP",p:"/aɪ siː em piː/",m:"控制报文",pos:"名词"},
  {r:"IGMP",p:"/aɪ dʒiː em piː/",m:"组管理",pos:"名词"},
  {r:"OSPF",p:"/əʊ es piː ef/",m:"开放最短路径",pos:"名词"},
  {r:"BGP",p:"/biː dʒiː piː/",m:"边界网关",pos:"名词"},
  {r:"VLAN",p:"/viː læn/",m:"虚拟局域网",pos:"名词"},
  {r:"WAN",p:"/wæn/",m:"广域网",pos:"名词"},
  {r:"LAN",p:"/læn/",m:"局域网",pos:"名词"},
  {r:"MAN",p:"/mæn/",m:"城域网",pos:"名词"},
  {r:"PAN",p:"/pæn/",m:"个域网",pos:"名词"},
  {r:"SAN",p:"/sæn/",m:"存储区域网",pos:"名词"},
  {r:"NAS",p:"/næs/",m:"网络存储",pos:"名词"},
  {r:"DAS",p:"/dæs/",m:"直连存储",pos:"名词"},
  {r:"RAID",p:"/reɪd/",m:"磁盘阵列",pos:"名词"},
  {r:"SSD",p:"/es es diː/",m:"固态硬盘",pos:"名词"},
  {r:"HDD",p:"/eɪtʃ diː diː/",m:"机械硬盘",pos:"名词"},
  {r:"RAM",p:"/ræm/",m:"随机存取",pos:"名词"},
  {r:"ROM",p:"/rɒm/",m:"只读存储",pos:"名词"},
  {r:"CPU",p:"/siː piː juː/",m:"中央处理器",pos:"名词"},
  {r:"GPU",p:"/dʒiː piː juː/",m:"图形处理器",pos:"名词"},
  {r:"TPU",p:"/tiː piː juː/",m:"张量处理器",pos:"名词"},
  {r:"NPU",p:"/en piː juː/",m:"神经网络",pos:"名词"},
  {r:"ALU",p:"/eɪ el juː/",m:"算术逻辑",pos:"名词"},
  {r:"FPU",p:"/ef piː juː/",m:"浮点单元",pos:"名词"},
  {r:"MMU",p:"/em em juː/",m:"内存管理",pos:"名词"},
  {r:"DMA",p:"/diː em eɪ/",m:"直接存储",pos:"名词"},
  {r:"IRQ",p:"/aɪ ɑːr kjuː/",m:"中断请求",pos:"名词"},
  {r:"ISR",p:"/aɪ es ɑːr/",m:"中断服务",pos:"名词"},
  {r:"BIOS",p:"/ˈbaɪɒs/",m:"基本输入输出",pos:"名词"},
  {r:"UEFI",p:"/juːˈfiː/",m:"统一可扩展",pos:"名词"},
  {r:"MBR",p:"/em biː ɑːr/",m:"主引导记录",pos:"名词"},
  {r:"GPT",p:"/dʒiː piː tiː/",m:"GUID分区",pos:"名词"},
  {r:"LVM",p:"/el viː em/",m:"逻辑卷管理",pos:"名词"},
  {r:"ZFS",p:"/zed ef es/",m:"Z文件系统",pos:"名词"},
  {r:"BTRFS",p:"/biː tiː ɑːr ef es/",m:"B树文件系统",pos:"名词"},
  {r:"EXT",p:"/iː eks tiː/",m:"扩展文件系统",pos:"名词"},
  {r:"NTFS",p:"/en tiː ef es/",m:"新技术",pos:"名词"},
  {r:"FAT",p:"/ef eɪ tiː/",m:"文件分配表",pos:"名词"},
  {r:"APFS",p:"/eɪ piː ef es/",m:"苹果文件系统",pos:"名词"},
  // 351-400
  {r:"HFS",p:"/eɪtʃ ef es/",m:"分层文件系统",pos:"名词"},
  {r:"NFS",p:"/en ef es/",m:"网络文件系统",pos:"名词"},
  {r:"SMB",p:"/es em biː/",m:"服务器消息块",pos:"名词"},
  {r:"CIFS",p:"/siː aɪ ef es/",m:"通用互联网",pos:"名词"},
  {r:"AFP",p:"/eɪ ef piː/",m:"Apple归档",pos:"名词"},
  {r:"WebDAV",p:"/web dæv/",m:"Web分布式",pos:"名词"},
  {r:"S3",p:"/es θriː/",m:"简单存储",pos:"名词"},
  {r:"EBS",p:"/iː biː es/",m:"弹性块存储",pos:"名词"},
  {r:"EFS",p:"/iː ef es/",m:"弹性文件系统",pos:"名词"},
  {r:" Glacier",p:"/ˈɡlæsiər/",m:"冰川存储",pos:"名词"},
  {r:"OSS",p:"/əʊ es es/",m:"对象存储",pos:"名词"},
  {r:"COS",p:"/siː əʊ es/",m:"云对象存储",pos:"名词"},
  {r:"BOS",p:"/biː əʊ es/",m:"百度对象存储",pos:"名词"},
  {r:"KMS",p:"/keɪ em es/",m:"密钥管理",pos:"名词"},
  {r:"HSM",p:"/eɪtʃ es em/",m:"硬件安全",pos:"名词"},
  {r:"TPM",p:"/tiː piː em/",m:"可信平台",pos:"名词"},
  {r:"SGX",p:"/es dʒiː eks/",m:"软件防护",pos:"名词"},
  {r:"SEV",p:"/es iː viː/",m:"安全加密",pos:"名词"},
  {r:"AMD",p:"/eɪ em diː/",m:"AMD处理器",pos:"名词"},
  {r:"Intel",p:"/ˈɪntel/",m:"英特尔",pos:"名词"},
  {r:"ARM",p:"/ɑːrm/",m:"ARM架构",pos:"名词"},
  {r:"RISC",p:"/rɪsk/",m:"精简指令",pos:"名词"},
  {r:"CISC",p:"/sɪsk/",m:"复杂指令",pos:"名词"},
  {r:"X86",p:"/eks eɪtiː siːks/",m:"X86架构",pos:"名词"},
  {r:"X64",p:"/eks sɪkstiː fɔːr/",m:"64位架构",pos:"名词"},
  {r:"AArch64",p:"/eɪ ɑːrk sɪkstiː fɔːr/",m:"ARM64",pos:"名词"},
  {r:"MIPS",p:"/mɪps/",m:"微处理器",pos:"名词"},
  {r:"SPARC",p:"/spɑːrk/",m:"可扩展",pos:"名词"},
  {r:"POWER",p:"/ˈpaʊər/",m:"POWER架构",pos:"名词"},
  {r:"RISCV",p:"/raɪsk faɪv/",m:"开源指令集",pos:"名词"},
  {r:"LLVM",p:"/el viː em/",m:"低级虚拟机",pos:"名词"},
  {r:"GCC",p:"/dʒiː siː siː/",m:"GNU编译器",pos:"名词"},
  {r:"MSVC",p:"/em es viː siː/",m:"微软编译器",pos:"名词"},
  {r:"CLang",p:"/siː læŋ/",m:"C语言",pos:"名词"},
  {r:"JIT",p:"/dʒeɪ aɪ tiː/",m:"即时编译",pos:"名词"},
  {r:"AOT",p:"/eɪ əʊ tiː/",m:"提前编译",pos:"名词"},
  {r:"VM",p:"/viː em/",m:"虚拟机",pos:"名词"},
  {r:"JVM",p:"/dʒeɪ viː em/",m:"Java虚拟机",pos:"名词"},
  {r:"WASM",p:"/ˈwɒzəm/",m:"WebAssembly",pos:"名词"},
  {r:"CLR",p:"/siː el ɑːr/",m:"公共语言",pos:"名词"},
  {r:"IL",p:"/aɪ el/",m:"中间语言",pos:"名词"},
  {r:"Bytecode",p:"/ˈbaɪtkəʊd/",m:"字节码",pos:"名词"},
  {r:"Opcode",p:"/ˈɒpkəʊd/",m:"操作码",pos:"名词"},
  {r:"Mnemonic",p:"/nɪˈmɒnɪk/",m:"助记符",pos:"名词"},
  {r:"Assembler",p:"/əˈsemblər/",m:"汇编器",pos:"名词"},
  {r:"Disassembler",p:"/dɪsəˈsemblər/",m:"反汇编",pos:"名词"},
  {r:"Decompiler",p:"/diːkəmˈpaɪlər/",m:"反编译器",pos:"名词"},
  {r:"Obfuscator",p:"/ˈɒbfəskeɪtər/",m:"混淆器",pos:"名词"},
  // 401-450
  {r:"Proguard",p:"/ˈprəʊɡɑːrd/",m:"Proguard",pos:"名词"},
  {r:"R8",p:"/ɑːr eɪt/",m:"R8编译器",pos:"名词"},
  {r:"DX",p:"/diː eks/",m:"Dalvik转换",pos:"名词"},
  {r:"D8",p:"/diː eɪt/",m:"D8编译器",pos:"名词"},
  {r:"ART",p:"/ɑːrt/",m:"Android运行时",pos:"名词"},
  {r:"Dalvik",p:"/ˈdælvɪk/",m:"Dalvik虚拟机",pos:"名词"},
  {r:"Zygote",p:"/ˈzaɪɡəʊt/",m:"受精卵进程",pos:"名词"},
  {r:"SystemServer",p:"/ˈsɪstəm ˈsɜːrvər/",m:"系统服务",pos:"名词"},
  {r:"ServiceManager",p:"/ˈsɜːrvɪs ˈmænɪdʒər/",m:"服务管理",pos:"名词"},
  {r:"Binder",p:"/ˈbaɪndər/",m:"Binder驱动",pos:"名词"},
  {r:"AIDL",p:"/eɪ aɪ diː el/",m:"接口定义",pos:"名词"},
  {r:"HIDL",p:"/eɪtʃ aɪ diː el/",m:"硬件接口",pos:"名词"},
  {r:"HAL",p:"/heɪl/",m:"硬件抽象",pos:"名词"},
  {r:"NDK",p:"/en diː keɪ/",m:"原生开发",pos:"名词"},
  {r:"JNI",p:"/dʒeɪ en aɪ/",m:"Java本地",pos:"名词"},
  {r:"JNA",p:"/dʒeɪ en eɪ/",m:"Java访问",pos:"名词"},
  {r:"FFI",p:"/ef ef aɪ/",m:"外部函数",pos:"名词"},
  {r:"ABI",p:"/eɪ biː aɪ/",m:"应用二进制",pos:"名词"},
  {r:"API",p:"/eɪ piː aɪ/",m:"应用接口",pos:"名词"},
  {r:"SPI",p:"/es piː aɪ/",m:"服务提供",pos:"名词"},
  {r:"SDK",p:"/es diː keɪ/",m:"开发工具包",pos:"名词"},
  {r:"JDK",p:"/dʒeɪ diː keɪ/",m:"Java开发",pos:"名词"},
  {r:"JRE",p:"/dʒeɪ ɑːr iː/",m:"Java运行",pos:"名词"},
  {r:"JAR",p:"/dʒɑːr/",m:"Java归档",pos:"名词"},
  {r:"WAR",p:"/wɔːr/",m:"Web归档",pos:"名词"},
  {r:"EAR",p:"/ɪər/",m:"企业归档",pos:"名词"},
  {r:"APK",p:"/eɪ piː keɪ/",m:"Android包",pos:"名词"},
  {r:"AAB",p:"/eɪ eɪ biː/",m:"AppBundle",pos:"名词"},
  {r:"IPA",p:"/aɪ piː eɪ/",m:"iOS包",pos:"名词"},
  {r:"DMG",p:"/diː em dʒiː/",m:"磁盘镜像",pos:"名词"},
  {r:"PKG",p:"/piː keɪ dʒiː/",m:"安装包",pos:"名词"},
  {r:"MSI",p:"/em es aɪ/",m:"安装程序",pos:"名词"},
  {r:"EXE",p:"/eks iː/",m:"可执行",pos:"名词"},
  {r:"DLL",p:"/diː el el/",m:"动态链接库",pos:"名词"},
  {r:"SO",p:"/es əʊ/",m:"共享对象",pos:"名词"},
  {r:"DYLIB",p:"/diː waɪ lɪb/",m:"动态库",pos:"名词"},
  {r:"AAR",p:"/eɪ eɪ ɑːr/",m:"Android库",pos:"名词"},
  {r:"Framework",p:"/ˈfreɪmwɜːrk/",m:"框架",pos:"名词"},
  {r:"Library",p:"/ˈlaɪbreri/",m:"库",pos:"名词"},
  {r:"Module",p:"/ˈmɒdjuːl/",m:"模块",pos:"名词"},
  {r:"Package",p:"/ˈpækɪdʒ/",m:"包",pos:"名词"},
  {r:"Plugin",p:"/ˈplʌɡɪn/",m:"插件",pos:"名词"},
  {r:"Addon",p:"/ˈædɒn/",m:"扩展",pos:"名词"},
  {r:"Extension",p:"/ɪkˈstenʃn/",m:"扩展",pos:"名词"},
  // 451-500
  {r:"Middleware",p:"/ˈmɪdlwer/",m:"中间件",pos:"名词"},
  {r:"Firmware",p:"/ˈfɜːrmwer/",m:"固件",pos:"名词"},
  {r:"Driver",p:"/ˈdraɪvər/",m:"驱动",pos:"名词"},
  {r:"Kernel",p:"/ˈkɜːrnl/",m:"内核",pos:"名词"},
  {r:"Shell",p:"/ʃel/",m:"壳",pos:"名词"},
  {r:"Daemon",p:"/ˈdiːmən/",m:"守护进程",pos:"名词"},
  {r:"Cronjob",p:"/ˈkrɒn dʒɒb/",m:"定时任务",pos:"名词"},
  {r:"Systemd",p:"/ˈsɪstəm diː/",m:"系统守护",pos:"名词"},
  {r:"Init",p:"/ˈɪnɪt/",m:"初始化",pos:"名词"},
  {r:"SysV",p:"/es waɪ viː/",m:"SystemV",pos:"名词"},
  {r:"Upstart",p:"/ˈʌpstɑːrt/",m:"启动管理",pos:"名词"},
  {r:"Runlevel",p:"/ˈrʌnˌlevl/",m:"运行级别",pos:"名词"},
  {r:"Target",p:"/ˈtɑːrɡɪt/",m:"目标",pos:"名词"},
  {r:"Unit",p:"/ˈjuːnɪt/",m:"单元",pos:"名词"},
  {r:"Service",p:"/ˈsɜːrvɪs/",m:"服务",pos:"名词"},
  {r:"Timer",p:"/ˈtaɪmər/",m:"定时器",pos:"名词"},
  {r:"Mount",p:"/maʊnt/",m:"挂载",pos:"动词"},
  {r:"Unmount",p:"/ʌnˈmaʊnt/",m:"卸载",pos:"动词"},
  {r:"FSCK",p:"/ef es siː keɪ/",m:"文件检查",pos:"名词"},
  {r:"MKFS",p:"/em keɪ ef es/",m:"创建文件系统",pos:"名词"},
  {r:"Parted",p:"/ˈpɑːrtɪd/",m:"分区",pos:"名词"},
  {r:"Fdisk",p:"/ef dɪsk/",m:"磁盘分区",pos:"名词"},
  {r:"Gdisk",p:"/dʒiː dɪsk/",m:"GPT分区",pos:"名词"},
  {r:"Sfdisk",p:"/es ef dɪsk/",m:"脚本分区",pos:"名词"},
  {r:"Cfdisk",p:"/siː ef dɪsk/",m:"图形分区",pos:"名词"},
  {r:"Lsblk",p:"/el es biː el keɪ/",m:"块设备",pos:"名词"},
  {r:"Blkid",p:"/biː el keɪ aɪ diː/",m:"块ID",pos:"名词"},
  {r:"Udev",p:"/juː dev/",m:"设备管理",pos:"名词"},
  {r:"Eudev",p:"/iː juː dev/",m:"Eudev",pos:"名词"},
  {r:"Devfs",p:"/dev ef es/",m:"设备文件",pos:"名词"},
  {r:"Procfs",p:"/prɒk ef es/",m:"进程文件",pos:"名词"},
  {r:"Sysfs",p:"/sɪs ef es/",m:"系统文件",pos:"名词"},
  {r:"Tmpfs",p:"/tmp ef es/",m:"临时文件",pos:"名词"},
  {r:"Cgroup",p:"/siː ɡruːp/",m:"控制组",pos:"名词"},
  {r:"Namespace",p:"/ˈneɪmspeɪs/",m:"命名空间",pos:"名词"},
  {r:"Chroot",p:"/tʃuːt/",m:"切换根目录",pos:"动词"},
  {r:"Pivot",p:"/ˈpɪvət/",m:"切换根",pos:"动词"},
  {r:"Prlimit",p:"/piː ɑːr ˈlɪmɪt/",m:"进程限制",pos:"名词"},
  {r:"Ulimit",p:"/juː ˈlɪmɪt/",m:"用户限制",pos:"名词"},
  {r:"Nice",p:"/naɪs/",m:"优先级",pos:"名词"},
  {r:"Renice",p:"/riːˈnaɪs/",m:"重设优先",pos:"动词"},
  {r:"Nohup",p:"/nəʊ hʌp/",m:"挂起保护",pos:"名词"},
  {r:"Screen",p:"/skriːn/",m:"屏幕会话",pos:"名词"},
  {r:"Tmux",p:"/tiː emʌks/",m:"终端复用",pos:"名词"},
  {r:"Tty",p:"/tiː tiː waɪ/",m:"终端",pos:"名词"},
  {r:"Pts",p:"/piː tiː es/",m:"伪终端",pos:"名词"},
  {r:"Ptmx",p:"/piː tiː em eks/",m:"主伪终端",pos:"名词"},
  {r:"Stty",p:"/es tiː tiː waɪ/",m:"终端设置",pos:"名词"},
  {r:"Getty",p:"/ɡet tiː waɪ/",m:"终端获取",pos:"名词"},
  {r:"Agetty",p:"/eɪ ɡet tiː waɪ/",m:"自动终端",pos:"名词"},
  {r:"Mingetty",p:"/mɪn ɡet tiː waɪ/",m:"最小终端",pos:"名词"}
];

function generateEntry(data, id) {
  const r = data.r.toLowerCase();
  const words = [];

  // 4个单词
  words.push({
    word: r,
    phonetic: data.p,
    partOfSpeech: "n.",
    meaning: data.m,
    memoryTip: `词根${r}表示${data.m}`,
    root: r,
    rootPhonetic: data.p,
    rootMeaning: data.m,
    rootPhrases: [`${r} protocol ${r}协议`],
    wordPhrases: [`${r} example ${r}示例`]
  });

  words.push({
    word: r + "ing",
    phonetic: data.p.slice(0,-1) + "ɪŋ/",
    partOfSpeech: "n.",
    meaning: data.m + "进行中",
    memoryTip: `${r} + ing表示进行`,
    root: r,
    rootPhonetic: data.p,
    rootMeaning: data.m,
    rootPhrases: [`${r} protocol ${r}协议`],
    wordPhrases: [`${r}ing process ${r}过程`]
  });

  words.push({
    word: r + "ed",
    phonetic: data.p.slice(0,-1) + "d/",
    partOfSpeech: "adj.",
    meaning: "已" + data.m,
    memoryTip: `${r} + ed表示完成`,
    root: r,
    rootPhonetic: data.p,
    rootMeaning: data.m,
    rootPhrases: [`${r} protocol ${r}协议`],
    wordPhrases: [`${r}ed data ${r}后的数据`]
  });

  words.push({
    word: "re" + r,
    phonetic: "/riː" + data.p.slice(1),
    partOfSpeech: "v.",
    meaning: "重新" + data.m,
    memoryTip: `re + ${r}表示重新`,
    root: r,
    rootPhonetic: data.p,
    rootMeaning: data.m,
    rootPhrases: [`${r} protocol ${r}协议`],
    wordPhrases: [`re${r} operation 重新${data.m}操作`]
  });

  return {
    id: id,
    root: r,
    phonetic: data.p,
    partOfSpeech: data.pos,
    meaning: data.m,
    frequency: id,
    category: "互联网和软件",
    words: words,
    phrases: [
      `${r} protocol ${r}协议`,
      `${r} service ${r}服务`,
      `${r} configuration ${r}配置`,
      `${r} management ${r}管理`
    ],
    mnemonic: `${r}表示${data.m}，re${r}表示重新${data.m}，${r}ing表示${data.m}进行中`
  };
}

const result = rootData.map((d, i) => generateEntry(d, 201 + i));

// 读取原文件
let content = fs.readFileSync('f:/claudeanli/beidanci3/src/data/internet-software.json', 'utf8');

// 移除最后的 ] 和换行
content = content.replace(/\s*\]\s*$/, '');

// 添加逗号和新数据
const newData = ',\n' + JSON.stringify(result, null, 2).slice(1, -1) + '\n]';

// 写入文件
fs.writeFileSync('f:/claudeanli/beidanci3/src/data/internet-software.json', content + newData);
console.log(`已添加 ${result.length} 个新词根，当前总数: ${200 + result.length}`);
