const fs = require('fs');

// 300个旅游词根数据
const roots = [
  // 501-550: 基础旅游概念
  [6501, "itinerary", "/aɪˈtɪnəreri/", "行程，路线", ["travel itinerary 旅行行程", "detailed itinerary 详细行程", "itinerary planning 行程规划", "flexible itinerary 灵活行程"], "itin→走→行程路线"],
  [6502, "excursion", "/ɪkˈskɜːrʒn/", "短途旅行", ["day excursion 一日游", "guided excursion 有导游的短途旅行", "boat excursion 乘船游览", "shore excursion 岸上观光"], "ex-curs→跑出去→短途旅行"],
  [6503, "cruise", "/kruːz/", "游轮", ["cruise ship 游轮", "cruise line 邮轮公司", "river cruise 河轮", "cruise vacation 游轮度假"], "cruise→巡航→游轮"],
  [6504, "resort", "/rɪˈzɔːrt/", "度假村", ["beach resort 海滨度假村", "ski resort 滑雪度假村", "luxury resort 豪华度假村", "all-inclusive resort 全包度假村"], "re-sort→再去的地方→度假胜地"],
  [6505, "expedition", "/ˌekspəˈdɪʃn/", "探险", ["scientific expedition 科学考察", "Arctic expedition 北极探险", "mountain expedition 登山探险", "expedition team 探险队"], "ex-ped→走出去→探险远征"],
  [6506, "safari", "/səˈfɑːri/", "野生动物观察游", ["African safari 非洲野生动物游", "safari park 野生动物园", "photo safari 摄影游猎", "safari guide 导游"], "safari→非洲旅行→野生动物游"],
  [6507, "adventure", "/ədˈventʃər/", "冒险", ["adventure travel 探险旅行", "adventure story 冒险故事", "spirit of adventure 冒险精神", "adventure sports 极限运动"], "ad-vent→向未知走来→冒险"],
  [6508, "sightseeing", "/ˈsaɪtsiːɪŋ/", "观光", ["sightseeing tour 观光游", "go sightseeing 去观光", "sightseeing bus 观光巴士", "city sightseeing 城市观光"], "sight+seeing→看景色→观光"],
  [6509, "destination", "/ˌdestɪˈneɪʃn/", "目的地", ["popular destination 热门目的地", "final destination 最终目的地", "tourist destination 旅游目的地", "dream destination 梦想目的地"], "destin→注定→目的地"],
  [6510, "attraction", "/əˈtrækʃn/", "景点", ["tourist attraction 旅游景点", "main attraction 主要景点", "popular attraction 热门景点", "local attraction 当地景点"], "at-tract→拉过来→吸引力→景点"],
  [6511, "landmark", "/ˈlændmɑːrk/", "地标", ["famous landmark 著名地标", "historical landmark 历史地标", "city landmark 城市地标", "national landmark 国家地标"], "land+mark→土地标记→地标"],
  [6512, "monument", "/ˈmɑːnjumənt/", "纪念碑", ["historical monument 历史纪念碑", "national monument 国家纪念碑", "ancient monument 古代遗迹", "visit monument 参观纪念碑"], "monu→提醒→纪念碑"],
  [6513, "heritage", "/ˈherɪtɪdʒ/", "遗产", ["cultural heritage 文化遗产", "world heritage 世界遗产", "natural heritage 自然遗产", "heritage site 遗产地"], "herit→继承→遗产"],
  [6514, "scenery", "/ˈsiːnəri/", "风景", ["beautiful scenery 美丽风景", "natural scenery 自然风光", "mountain scenery 山景", "enjoy scenery 欣赏风景"], "scene→场景→风景"],
  [6515, "panorama", "/ˌpænəˈræmə/", "全景", ["panorama view 全景视野", "stunning panorama 壮丽全景", "360 panorama 360度全景", "city panorama 城市全景"], "pan→全+orama→视野→全景"],
  [6516, "vista", "/ˈvɪstə/", "远景", ["scenic vista 优美远景", "beautiful vista 美丽远景", "mountain vista 山景", "ocean vista 海景"], "vis→看→远景"],
  [6517, "oasis", "/oʊˈeɪsɪs/", "绿洲", ["desert oasis 沙漠绿洲", "tropical oasis 热带绿洲", "urban oasis 城市绿洲", "oasis resort 绿洲度假村"], "oasis→绿洲"],
  [6518, "waterfall", "/ˈwɔːtərfɔːl/", "瀑布", ["magnificent waterfall 壮丽瀑布", "tall waterfall 高瀑布", "waterfall hike 瀑布徒步", "under waterfall 瀑布下"], "water+fall→水落下→瀑布"],
  [6519, "volcano", "/vɑːlˈkeɪnoʊ/", "火山", ["active volcano 活火山", "dormant volcano 休眠火山", "volcano eruption 火山爆发", "volcano tour 火山游"], "volcan→火山"],
  [6520, "glacier", "/ˈɡleɪʃər/", "冰川", ["melting glacier 融化的冰川", "glacier hiking 冰川徒步", "glacier tour 冰川游", "visit glacier 参观冰川"], "glaci→冰→冰川"],
  [6521, "canyon", "/ˈkænjən/", "峡谷", ["grand canyon 大峡谷", "deep canyon 深峡谷", "canyon trail 峡谷步道", "canyon view 峡谷景观"], "canyon→峡谷"],
  [6522, "cave", "/keɪv/", "洞穴", ["underground cave 地下洞穴", "limestone cave 石灰岩洞", "cave exploring 洞穴探险", "cave painting 洞穴壁画"], "cave→洞穴"],
  [6523, "reef", "/riːf/", "礁石", ["coral reef 珊瑚礁", "reef diving 礁潜", "great barrier reef 大堡礁", "reef ecosystem 礁生态系统"], "reef→礁石"],
  [6524, "wetland", "/ˈwetlænd/", "湿地", ["coastal wetland 沿海湿地", "wetland park 湿地公园", "wetland reserve 湿地保护区", "wetland tour 湿地游"], "wet+land→湿地"],
  [6525, "waterfront", "/ˈwɔːtərfrʌnt/", "滨水区", ["waterfront area 滨水区", "waterfront promenade 滨水步道", "waterfront hotel 滨水酒店", "waterfront restaurant 滨水餐厅"], "water+front→水边→滨水区"],
  [6526, "boardwalk", "/ˈbɔːrdwɔːk/", "木板路", ["beach boardwalk 海滩木板路", "boardwalk shops 木板路商店", "stroll boardwalk 漫步木板路", "ocean boardwalk 海边木板路"], "board+walk→木板路"],
  [6527, "promenade", "/ˌprɑːməˈnɑːd/", "散步道", ["seaside promenade 海滨散步道", "evening promenade 晚间散步", "promenade deck 散步甲板", "take a promenade 散步"], "promen→散步→散步道"],
  [6528, "plaza", "/ˈplɑːzə/", "广场", ["city plaza 城市广场", "town plaza 城镇广场", "central plaza 中央广场", "plaza square 广场"], "plaza→广场"],
  [6529, "boulevard", "/ˈbʊləvɑːrd/", "林荫大道", ["main boulevard 主林荫道", "famous boulevard 著名林荫道", "sunset boulevard 日落大道", "wide boulevard 宽阔林荫道"], "boulevard→林荫大道"],
  [6530, "alley", "/ˈæli/", "小巷", ["narrow alley 窄巷", "old alley 老巷子", "alley way 小巷", "historic alley 历史小巷"], "alley→小巷"],
  [6531, "pathway", "/ˈpæθweɪ/", "小径", ["garden pathway 花园小径", "nature pathway 自然小径", "walking pathway 步行小径", "scenic pathway 风景小径"], "path+way→小路→小径"],
  [6532, "trailhead", "/ˈtreɪlhed/", "步道起点", ["trailhead parking 步道起点停车场", "trailhead sign 步道起点标志", "main trailhead 主要步道起点", "trailhead map 步道起点地图"], "trail+head→步道头→步道起点"],
  [6533, "lookout", "/ˈlʊkaʊt/", "观景台", ["scenic lookout 风景观景台", "mountain lookout 山顶观景台", "coastal lookout 海岸观景台", "lookout point 观景点"], "look+out→向外看→观景台"],
  [6534, "viewpoint", "/ˈvjuːpɔɪnt/", "观景点", ["panoramic viewpoint 全景观景点", "stunning viewpoint 壮观观景点", "viewpoint terrace 观景平台", "best viewpoint 最佳观景点"], "view+point→观点→观景点"],
  [6535, "overlook", "/ˌoʊvərˈlʊk/", "俯瞰处", ["scenic overlook 风景俯瞰处", "cliff overlook 悬崖俯瞰处", "overlook trail 俯瞰步道", "overlook deck 观景平台"], "over+look→俯视→俯瞰处"],
  [6536, "terrace", "/ˈterəs/", "露台", ["roof terrace 屋顶露台", "ocean terrace 海景露台", "terraced garden 梯田花园", "outdoor terrace 户外露台"], "terr→土地→露台"],
  [6537, "pavilion", "/pəˈvɪliən/", "亭子", ["garden pavilion 花园亭子", "exhibition pavilion 展览馆", "Chinese pavilion 中式亭子", "band pavilion 音乐亭"], "pavilion→亭子"],
  [6538, "gazebo", "/ɡəˈziːboʊ/", "凉亭", ["garden gazebo 花园凉亭", "wooden gazebo 木凉亭", "gazebo shade 凉亭遮阳", "outdoor gazebo 户外凉亭"], "gazebo→凉亭"],
  [6539, "pagoda", "/pəˈɡoʊdə/", "宝塔", ["ancient pagoda 古塔", "Buddhist pagoda 佛塔", "pagoda tower 宝塔", "five-story pagoda 五层塔"], "pagoda→宝塔"],
  [6540, "shrine", "/ʃraɪn/", "神龛，圣地", ["holy shrine 圣坛", "ancient shrine 古神社", "shrine visit 参拜", "memorial shrine 纪念神龛"], "shrine→圣地→神龛"],
  [6541, "temple", "/ˈtempl/", "寺庙", ["Buddhist temple 佛教寺庙", "ancient temple 古寺", "temple complex 寺庙群", "temple visit 寺庙参观"], "templ→庙宇→寺庙"],
  [6542, "cathedral", "/kəˈθiːdrəl/", "大教堂", ["gothic cathedral 哥特式大教堂", "famous cathedral 著名大教堂", "cathedral square 大教堂广场", "cathedral tower 大教堂塔"], "cathedra→主教座→大教堂"],
  [6543, "chapel", "/ˈtʃæpl/", "小教堂", ["wedding chapel 婚礼小教堂", "private chapel 私人小教堂", "chapel service 礼拜", "chapel bell 教堂钟声"], "chapel→小教堂"],
  [6544, "mosque", "/mɑːsk/", "清真寺", ["grand mosque 大清真寺", "historic mosque 历史清真寺", "mosque visit 清真寺参观", "mosque architecture 清真寺建筑"], "mosque→清真寺"],
  [6545, "synagogue", "/ˈsɪnəɡɒɡ/", "犹太教堂", ["Jewish synagogue 犹太教堂", "historic synagogue 历史犹太教堂", "synagogue service 礼拜", "synagogue visit 参观犹太教堂"], "syna+go→聚集→犹太教堂"],
  [6546, "basilica", "/bəˈzɪlɪkə/", "大殿", ["ancient basilica 古代大殿", "basilica church 大殿教堂", "basilica architecture 大殿建筑", "visit basilica 参观大殿"], "basilica→王座→大殿"],
  [6547, "minaret", "/ˌmɪnəˈret/", "宣礼塔", ["tall minaret 高宣礼塔", "mosque minaret 清真寺宣礼塔", "minaret tower 宣礼塔", "minaret call 宣礼"], "minaret→灯塔→宣礼塔"],
  [6548, "dome", "/doʊm/", "圆顶", ["golden dome 金色圆顶", "dome structure 圆顶结构", "under the dome 圆顶下", "glass dome 玻璃穹顶"], "dome→圆顶"],
  [6549, "spire", "/ˈspaɪər/", "尖塔", ["church spire 教堂尖塔", "tall spire 高尖塔", "spire top 尖塔顶", "spire view 尖塔景观"], "spir→呼吸→尖塔"],
  [6550, "belfry", "/ˈbelfri/", "钟楼", ["church belfry 教堂钟楼", "belfry tower 钟楼塔", "belfry bell 钟楼钟", "climb belfry 爬钟楼"], "belfry→钟楼"],
  // 551-600: 住宿相关
  [6551, "suite", "/swiːt/", "套房", ["presidential suite 总统套房", "junior suite 小套房", "deluxe suite 豪华套房", "suite room 套房"], "suite→跟随→套房"],
  [6552, "penthouse", "/ˈpenthaʊs/", "顶层公寓", ["luxury penthouse 豪华顶层公寓", "penthouse suite 顶层套房", "rooftop penthouse 屋顶顶层公寓", "penthouse view 顶层景观"], "pent+house→顶层公寓"],
  [6553, "loft", "/lɔːft/", "阁楼", ["industrial loft 工业风阁楼", "loft apartment 阁楼公寓", "spacious loft 宽敞阁楼", "loft conversion 阁楼改造"], "loft→阁楼"],
  [6554, "villa", "/ˈvɪlə/", "别墅", ["luxury villa 豪华别墅", "beach villa 海滨别墅", "private villa 私人别墅", "villa rental 别墅租赁"], "villa→别墅"],
  [6555, "cottage", "/ˈkɑːtɪdʒ/", "小屋", ["cozy cottage 温馨小屋", "country cottage 乡村小屋", "cottage rental 小屋租赁", "seaside cottage 海边小屋"], "cottage→小屋"],
  [6556, "cabin", "/ˈkæbɪn/", "木屋", ["log cabin 木屋", "mountain cabin 山间木屋", "cabin rental 木屋租赁", "rustic cabin 乡村木屋"], "cabin→木屋"],
  [6557, "bungalow", "/ˈbʌŋɡəloʊ/", "平房", ["beach bungalow 海滩平房", "private bungalow 私人平房", "bungalow resort 平房度假村", "luxury bungalow 豪华平房"], "bungalow→平房"],
  [6558, "chalet", "/ˈʃæleɪ/", "山间小屋", ["ski chalet 滑雪小屋", "mountain chalet 山间木屋", "alpine chalet 阿尔卑斯小屋", "chalet rental 小木屋租赁"], "chalet→山间小屋"],
  [6559, "motel", "/moʊˈtel/", "汽车旅馆", ["highway motel 公路汽车旅馆", "budget motel 经济型汽车旅馆", "motel room 汽车旅馆房间", "motel chain 汽车旅馆连锁"], "motor+hotel→汽车旅馆"],
  [6560, "hostel", "/ˈhɑːstl/", "青年旅舍", ["youth hostel 青年旅舍", "backpacker hostel 背包客旅舍", "hostel dormitory 旅舍宿舍", "budget hostel 经济型旅舍"], "hostel→旅舍"],
  [6561, "inn", "/ɪn/", "小旅馆", ["country inn 乡村小旅馆", "historic inn 历史小旅馆", "roadside inn 路边客栈", "cozy inn 温馨小旅馆"], "inn→小旅馆"],
  [6562, "lodge", "/lɑːdʒ/", "旅馆", ["ski lodge 滑雪旅馆", "hunting lodge 狩猎旅馆", "mountain lodge 山间旅馆", "lodge accommodation 旅馆住宿"], "lodge→旅馆"],
  [6563, "condo", "/ˈkɑːndoʊ/", "公寓", ["beach condo 海滨公寓", "condo rental 公寓租赁", "luxury condo 豪华公寓", "condo building 公寓楼"], "condominium→公寓"],
  [6564, "guesthouse", "/ˈɡesthaʊs/", "民宿", ["family guesthouse 家庭民宿", "guesthouse stay 民宿住宿", "budget guesthouse 经济民宿", "cozy guesthouse 温馨民宿"], "guest+house→民宿"],
  [6565, "homestay", "/ˈhoʊmsteɪ/", "家庭寄宿", ["local homestay 当地家庭寄宿", "homestay experience 寄宿体验", "homestay family 寄宿家庭", "authentic homestay 正宗寄宿"], "home+stay→家庭寄宿"],
  [6566, "caravan", "/ˈkærəvæn/", "房车", ["caravan park 房车营地", "caravan rental 房车租赁", "touring caravan 旅行房车", "caravan trip 房车旅行"], "caravan→房车"],
  [6567, "campground", "/ˈkæmpɡraʊnd/", "露营地", ["national park campground 国家公园露营地", "campground reservation 露营地预订", "RV campground 房车营地", "campground facilities 营地设施"], "camp+ground→露营地"],
  [6568, "RV", "/ˌɑːrˈviː/", "房车", ["RV park 房车公园", "RV rental 房车租赁", "RV trip 房车旅行", "drive RV 开房车"], "Recreational Vehicle→房车"],
  [6569, "yurt", "/jɜːrt/", "蒙古包", ["traditional yurt 传统蒙古包", "yurt camping 蒙古包露营", "yurt stay 蒙古包住宿", "modern yurt 现代蒙古包"], "yurt→蒙古包"],
  [6570, "igloo", "/ˈɪɡluː/", "冰屋", ["snow igloo 冰雪屋", "igloo hotel 冰屋酒店", "sleep in igloo 睡在冰屋", "Arctic igloo 北极冰屋"], "igloo→冰屋"],
  [6571, "treehouse", "/ˈtriːhaʊs/", "树屋", ["luxury treehouse 豪华树屋", "treehouse hotel 树屋酒店", "sleep in treehouse 睡在树屋", "treehouse resort 树屋度假村"], "tree+house→树屋"],
  [6572, "houseboat", "/ˈhaʊsboʊt/", "船屋", ["houseboat rental 船屋租赁", "houseboat vacation 船屋度假", "stay on houseboat 住在船屋", "houseboat cruise 船屋巡游"], "house+boat→船屋"],
  [6573, "amenity", "/əˈmenəti/", "设施", ["hotel amenities 酒店设施", "room amenities 房间设施", "resort amenities 度假村设施", "modern amenities 现代设施"], "amen→舒适→设施"],
  [6574, "concierge", "/ˌkɑːnsiˈerʒ/", "礼宾服务", ["concierge service 礼宾服务", "hotel concierge 酒店礼宾", "concierge desk 礼宾台", "virtual concierge 虚拟礼宾"], "concierge→礼宾"],
  [6575, "housekeeping", "/ˈhaʊskiːpɪŋ/", "客房服务", ["housekeeping service 客房服务", "daily housekeeping 每日清洁", "housekeeping staff 客房部员工", "light housekeeping 轻度清洁"], "house+keeping→客房服务"],
  [6576, "turn-down", "/ˈtɜːrndaʊn/", "开夜床服务", ["turn-down service 开夜床服务", "evening turn-down 晚间开床", "turn-down bed 已铺好的床", "complimentary turn-down 免费开床服务"], "turn+down→开夜床服务"],
  [6577, "checkout", "/ˈtʃekaʊt/", "退房", ["checkout time 退房时间", "late checkout 延迟退房", "express checkout 快速退房", "checkout procedure 退房手续"], "check+out→退房"],
  [6578, "check-in", "/ˈtʃekɪn/", "入住", ["check-in time 入住时间", "early check-in 提前入住", "check-in desk 入住柜台", "online check-in 在线入住"], "check+in→入住"],
  [6579, "lobby", "/ˈlɑːbi/", "大堂", ["hotel lobby 酒店大堂", "lobby bar 大堂吧", "lobby lounge 大堂休息区", "main lobby 主大堂"], "lobby→大堂"],
  [6580, "reception", "/rɪˈsepʃn/", "前台", ["reception desk 前台", "24-hour reception 24小时前台", "reception area 接待区", "receptionist 前台接待员"], "re-cept→接收→前台"],
  [6581, "bellhop", "/ˈbelhɑːp/", "行李员", ["hotel bellhop 酒店行李员", "bellhop service 行李服务", "call bellhop 叫行李员", "tip bellhop 给行李员小费"], "bell+hop→行李员"],
  [6582, "doorman", "/ˈdɔːrmən/", "门童", ["hotel doorman 酒店门童", "doorman service 门童服务", "friendly doorman 友好的门童", "uniformed doorman 制服门童"], "door+man→门童"],
  [6583, "valet", "/ˈvæleɪ/", "代客泊车", ["valet parking 代客泊车", "valet service 代客服务", "hotel valet 酒店代客", "valet attendant 泊车服务员"], "valet→代客泊车"],
  [6584, "minibar", "/ˈmɪnibɑːr/", "迷你吧", ["stocked minibar 备有饮品的迷你吧", "minibar charge 迷你吧收费", "empty minibar 空迷你吧", "minibar items 迷你吧物品"], "mini+bar→迷你吧"],
  [6585, "roomservice", "/ˈruːmsɜːrvɪs/", "客房送餐", ["24-hour room service 24小时客房送餐", "room service menu 客房送餐菜单", "order room service 点客房送餐", "room service charge 客房送餐费"], "room+service→客房送餐"],
  [6586, "wake-up", "/ˈweɪkʌp/", "叫醒服务", ["wake-up call 叫醒电话", "morning wake-up 早晨叫醒", "request wake-up 要求叫醒服务", "wake-up time 叫醒时间"], "wake+up→叫醒服务"],
  [6587, "linen", "/ˈlɪnɪn/", "床单", ["fresh linen 干净床单", "bed linen 床上用品", "linen change 换床单", "clean linen 清洁床单"], "linen→亚麻→床单"],
  [6588, "pillow", "/ˈpɪloʊ/", "枕头", ["soft pillow 软枕头", "firm pillow 硬枕头", "pillow menu 枕头菜单", "extra pillow 额外枕头"], "pillow→枕头"],
  [6589, "mattress", "/ˈmætrəs/", "床垫", ["comfortable mattress 舒适床垫", "memory foam mattress 记忆海绵床垫", "mattress quality 床垫质量", "soft mattress 软床垫"], "mattress→床垫"],
  [6590, "quilt", "/kwɪlt/", "被子", ["warm quilt 暖和的被子", "patchwork quilt 拼布被子", "quilt cover 被套", "down quilt 羽绒被"], "quilt→被子"],
  [6591, "blanket", "/ˈblæŋkɪt/", "毯子", ["warm blanket 暖和的毯子", "electric blanket 电热毯", "extra blanket 额外毯子", "wool blanket 羊毛毯"], "blanket→毯子"],
  [6592, "towel", "/ˈtaʊəl/", "毛巾", ["bath towel 浴巾", "hand towel 手巾", "beach towel 沙滩巾", "fresh towel 干净毛巾"], "towel→毛巾"],
  [6593, "robe", "/roʊb/", "浴袍", ["bath robe 浴袍", "plush robe 毛绒浴袍", "hotel robe 酒店浴袍", "white robe 白色浴袍"], "robe→浴袍"],
  [6594, "slipper", "/ˈslɪpər/", "拖鞋", ["disposable slipper 一次性拖鞋", "bathroom slipper 浴室拖鞋", "hotel slipper 酒店拖鞋", "soft slipper 软拖鞋"], "slip→滑→拖鞋"],
  [6595, "toiletries", "/ˈtɔɪlətriz/", "洗漱用品", ["complimentary toiletries 免费洗漱用品", "toiletries bag 洗漱包", "travel toiletries 旅行洗漱用品", "toiletries set 洗漱套装"], "toilet→洗漱用品"],
  [6596, "shampoo", "/ʃæmˈpuː/", "洗发水", ["hotel shampoo 酒店洗发水", "shampoo bottle 洗发水瓶", "conditioning shampoo 护发洗发水", "complimentary shampoo 免费洗发水"], "shampoo→洗发水"],
  [6597, "conditioner", "/kənˈdɪʃənər/", "护发素", ["hair conditioner 护发素", "conditioner bottle 护发素瓶", "complimentary conditioner 免费护发素", "deep conditioner 深层护发素"], "condition→护发素"],
  [6598, "sauna", "/ˈsɔːnə/", "桑拿", ["hotel sauna 酒店桑拿", "sauna room 桑拿房", " Finnish sauna 芬兰桑拿", "sauna session 桑拿疗程"], "sauna→桑拿"],
  [6599, "jacuzzi", "/dʒəˈkuːzi/", "按摩浴缸", ["private jacuzzi 私人按摩浴缸", "outdoor jacuzzi 户外按摩浴缸", "jacuzzi tub 按摩浴缸", "hotel jacuzzi 酒店按摩浴缸"], "jacuzzi→按摩浴缸"],
  [6600, "spa", "/spɑː/", "水疗", ["hotel spa 酒店水疗", "day spa 日间水疗", "spa treatment 水疗护理", "spa package 水疗套餐"], "spa→水疗"],
];

function generateEntry(item) {
  const [id, root, phonetic, meaning, phrases, mnemonic] = item;
  const freq = id - 6000;
  return {
    id: id,
    root: root,
    phonetic: phonetic,
    partOfSpeech: "词根",
    meaning: meaning,
    frequency: freq,
    category: "旅游",
    words: [{
      word: root,
      phonetic: phonetic,
      partOfSpeech: "n.",
      meaning: meaning,
      memoryTip: `词根 ${root} 表示 ${meaning}`,
      root: root,
      rootPhonetic: phonetic,
      rootMeaning: meaning,
      rootPhrases: phrases,
      wordPhrases: phrases
    }],
    phrases: phrases,
    mnemonic: mnemonic
  };
}

const entries = roots.map(generateEntry);
const output = entries.map(e => "," + JSON.stringify(e, null, 2)).join("\n");

console.log(output);
