#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate 300 new electric power root entries (id 501-800, frequency 501-800)
"""

import json

# Read existing data
with open('f:/claudeanli/beidanci3/src/data/electric-power.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

print(f"Existing entries: {len(data)}")
print(f"First entry ID: {data[0]['id']}, frequency: {data[0]['frequency']}")
print(f"Last entry ID: {data[-1]['id']}, frequency: {data[-1]['frequency']}")

# 电力行业词根数据（按使用频率排序）
# 包含发电、输电、变电、配电、用电、储能、新能源等领域

electric_power_roots = [
    # 501-550: 发电与能源转换相关
    ("turbogenerator", "/ˈtɜːrboʊˈdʒenəreɪtər/", "汽轮发电机", "turbine + generator组合"),
    ("hydrogenerator", "/ˈhaɪdroʊˈdʒenəreɪtər/", "水轮发电机", "hydro水 + generator发电机"),
    ("thermoelectric", "/ˌθɜːrmoʊɪˈlektrɪk/", "热电的", "thermo热 + electric电"),
    ("photovoltaic", "/ˌfoʊtoʊvɒlˈteɪɪk/", "光伏的", "photo光 + voltaic伏打"),
    ("concentrator", "/ˈkɒnsntreɪtər/", "聚光器", "concentrate聚集 + or器"),
    ("heliostat", "/ˈhiːlioʊstæt/", "定日镜", "helio太阳 + stat静止"),
    ("parabolic", "/ˌpærəˈbɒlɪk/", "抛物面的", "para旁 + bolic抛"),
    ("trough", "/trɒf/", "槽式", "trough槽"),
    ("dish", "/dɪʃ/", "碟式", "dish碟"),
    ("tower", "/ˈtaʊər/", "塔式", "tower塔"),
    ("linear", "/ˈlɪniər/", "线性的", "line线 + ar的"),
    ("fresnel", "/freɪˈnel/", "菲涅尔", "Fresnel人名"),
    ("stirling", "/ˈstɜːrlɪŋ/", "斯特林", "Stirling人名"),
    ("brayton", "/ˈbreɪtən/", "布雷顿", "Brayton人名"),
    ("rankine", "/ˈræŋkɪn/", "朗肯", "Rankine人名"),
    ("carnot", "/ˈkɑːrnoʊ/", "卡诺", "Carnot人名"),
    ("entropy", "/ˈentrəpi/", "熵", "en进入 + trope转变"),
    ("enthalpy", "/ˈenθælpi/", "焓", "en使 + thalpy热"),
    ("exergy", "/ˈeksərdʒi/", "㶲", "ex外 + ergy功"),
    ("anergy", "/ˈænərdʒi/", "烶", "an无 + ergy功"),
    ("isentropic", "/ˌaɪsenˈtrɒpɪk/", "等熵的", "iso等 + entropic熵"),
    ("isenthalpic", "/ˌaɪsenˈθælpɪk/", "等焓的", "iso等 + enthalpic焓"),
    ("adiabatic", "/ˌædiəˈbætɪk/", "绝热的", "a不 + dia通过 + batic走"),
    ("isothermal", "/ˌaɪsoʊˈθɜːrml/", "等温的", "iso等 + thermal温"),
    ("isobaric", "/ˌaɪsoʊˈbærɪk/", "等压的", "iso等 + baric压"),
    ("isochoric", "/ˌaɪsoʊˈkɒrɪk/", "等容的", "iso等 + choric容"),
    ("polytropic", "/ˌpɒliˈtrɒpɪk/", "多变过程", "poly多 + tropic转变"),
    ("throttling", "/ˈθrɒtlɪŋ/", "节流", "throttle节流 + ing"),
    ("expansion", "/ɪkˈspænʃn/", "膨胀", "ex向外 + pans展开"),
    ("compression", "/kəmˈpreʃn/", "压缩", "com共同 + press压"),
    ("combustion", "/kəmˈbʌstʃən/", "燃烧", "com共同 + bust烧"),
    ("gasification", "/ˌɡæsɪfɪˈkeɪʃn/", "气化", "gas气 + ification化"),
    ("liquefaction", "/ˌlɪkwɪˈfækʃn/", "液化", "lique液体 + faction做"),
    ("vaporization", "/ˌveɪpərəˈzeɪʃn/", "汽化", "vapor蒸汽 + ization化"),
    ("condensation", "/ˌkɒndenˈseɪʃn/", "凝结", "con共同 + dens密"),
    ("evaporation", "/ɪˌvæpəˈreɪʃn/", "蒸发", "e出 + vapor蒸汽"),
    ("sublimation", "/ˌsʌblɪˈmeɪʃn/", "升华", "sub向上 + lim界限"),
    ("deposition", "/ˌdepəˈzɪʃn/", "凝华", "de向下 + posit放"),
    ("saturation", "/ˌsætʃəˈreɪʃn/", "饱和", "satur满 + ation"),
    ("superheat", "/ˈsuːpərhiːt/", "过热", "super超 + heat热"),
    ("subcooling", "/sʌbˈkuːlɪŋ/", "过冷", "sub低 + cooling冷"),
    ("quality", "/ˈkwɒləti/", "干度", "qual性质 + ity"),
    ("moisture", "/ˈmɔɪstʃər/", "湿度", "moist湿 + ure"),
    ("humidity", "/hjuːˈmɪdəti/", "湿度", "humid湿 + ity"),
    ("dryness", "/ˈdraɪnəs/", "干燥度", "dry干 + ness"),
    ("wetness", "/ˈwɛtnəs/", "湿润度", "wet湿 + ness"),
    ("boiler", "/ˈbɔɪlər/", "锅炉", "boil沸腾 + er器"),
    ("condenser", "/kənˈdensər/", "凝汽器", "condense凝结 + er器"),
    ("evaporator", "/ɪˈvæpəreɪtər/", "蒸发器", "evaporate蒸发 + or器"),
    ("superheater", "/ˈsuːpərhiːtər/", "过热器", "superheat过热 + er器"),

    # 551-600: 输电与变电设备
    ("bushing", "/ˈbʊʃɪŋ/", "套管", "bush套管 + ing"),
    ("bushingtype", "/ˈbʊʃɪŋtaɪp/", "套管型", "bushing套管 + type型"),
    ("insulatorstring", "/ˈɪnsəleɪtərstrɪŋ/", "绝缘子串", "insulator绝缘子 + string串"),
    ("spacer", "/ˈspeɪsər/", "间隔棒", "space间隔 + er器"),
    ("damper", "/ˈdæmpər/", "阻尼器", "damp阻尼 + er器"),
    ("stockbridge", "/ˈstɒkbrɪdʒ/", "斯托克布里奇", "Stockbridge人名"),
    ("vibration", "/vaɪˈbreɪʃn/", "振动", "vibr振动 + ation"),
    ("galloping", "/ˈɡæləpɪŋ/", "舞动", "gallop奔驰 + ing"),
    ("aeolian", "/iːˈoʊliən/", "风的", "Aeolus风神"),
    ("conductorbundle", "/kənˈdʌktərbʌndl/", "分裂导线", "conductor导线 + bundle束"),
    ("twin", "/twɪn/", "双分裂", "twin双"),
    ("quad", "/kwɒd/", "四分裂", "quad四"),
    ("hex", "/heks/", "六分裂", "hex六"),
    ("oct", "/ɒkt/", "八分裂", "oct八"),
    ("sag", "/sæɡ/", "弧垂", "sag下垂"),
    ("tension", "/ˈtenʃn/", "张力", "tens拉 + ion"),
    ("clearance", "/ˈklɪərəns/", "间隙", "clear清楚 + ance"),
    ("span", "/spæn/", "档距", "span跨度"),
    ("section", "/ˈsekʃn/", "耐张段", "sect切 + ion"),
    ("strain", "/streɪn/", "耐张", "strain拉紧"),
    ("suspension", "/səˈspenʃn/", "悬垂", "sus下 + pens挂"),
    ("deadend", "/ˈdedend/", "终端", "dead死 + end端"),
    ("angle", "/ˈæŋɡl/", "转角", "angle角"),
    ("tangent", "/ˈtændʒənt/", "直线", "tangent切线"),
    ("crossing", "/ˈkrɒsɪŋ/", "跨越", "cross穿过 + ing"),
    ("junction", "/ˈdʒʌŋkʃn/", " junction塔", "junct连接 + ion"),
    ("terminal", "/ˈtɜːrmɪnl/", "终端", "termin终端 + al"),
    ("guy", "/ɡaɪ/", "拉线", "guy拉线"),
    ("stay", "/steɪ/", "撑杆", "stay支撑"),
    ("brace", "/breɪs/", "撑架", "brace支撑"),
    ("strut", "/strʌt/", "支柱", "strut支柱"),
    ("tie", "/taɪ/", "连接线", "tie绑"),
    ("jumper", "/ˈdʒʌmpər/", "跳线", "jump跳 + er"),
    ("groundwire", "/ɡraʊndwaɪər/", "地线", "ground地 + wire线"),
    ("shieldwire", "/ʃiːldwaɪər/", "屏蔽线", "shield屏蔽 + wire线"),
    ("opticalground", "/ˈɒptɪklɡraʊnd/", "光纤地线", "optical光 + ground地"),
    ("opgw", "/oʊpiːdʒiːˈdʌbəljuː/", "光纤复合架空地线", "OPGW缩写"),
    ("adss", "/eɪdiːɛsɛs/", "全介质自承式光缆", "ADSS缩写"),
    ("corona", "/kəˈroʊnə/", "电晕", "corona日冕"),
    ("ionization", "/ˌaɪənaɪˈzeɪʃn/", "电离", "ion离子 + ization化"),
    ("breakdown", "/ˈbreɪkdaʊn/", "击穿", "break打破 + down下"),
    ("flashover", "/ˈflæʃoʊvər/", "闪络", "flash闪光 + over越过"),

    # 601-650: 电力系统保护与自动化
    ("relay", "/ˈriːleɪ/", "继电器", "relay中继"),
    ("protection", "/prəˈtekʃn/", "保护", "pro前 + tect盖"),
    ("differential", "/ˌdɪfəˈrenʃl/", "差动", "differ差异 + ential"),
    ("distance", "/ˈdɪstəns/", "距离", "dis分开 + st站"),
    ("overcurrent", "/ˌoʊvərˈkʌrənt/", "过流", "over过 + current流"),
    ("undercurrent", "/ˌʌndərˈkʌrənt/", "欠流", "under欠 + current流"),
    ("overvoltage", "/ˌoʊvərˈvoʊltɪdʒ/", "过压", "over过 + voltage压"),
    ("undervoltage", "/ˌʌndərˈvoʊltɪdʒ/", "欠压", "under欠 + voltage压"),
    ("overfrequency", "/ˌoʊvərˈfriːkwənsi/", "过频", "over过 + frequency频"),
    ("underfrequency", "/ˌʌndərˈfriːkwənsi/", "欠频", "under欠 + frequency频"),
    ("overexcitation", "/ˌoʊvərɛksaɪˈteɪʃn/", "过励磁", "over过 + excitation励磁"),
    ("lossofexcitation", "/lɔːsəvɛksaɪˈteɪʃn/", "失磁", "loss失去 + of + excitation励磁"),
    ("statorground", "/ˈsteɪtərɡraʊnd/", "定子接地", "stator定子 + ground地"),
    ("rotorground", "/ˈroʊtərɡraʊnd/", "转子接地", "rotor转子 + ground地"),
    ("negative", "/ˈneɡətɪv/", "负序", "negate否定 + ive"),
    ("zero", "/ˈzɪəroʊ/", "零序", "zero零"),
    ("sequence", "/ˈsiːkwəns/", "序", "sequ跟随 + ence"),
    ("harmonic", "/hɑːrˈmɒnɪk/", "谐波", "harmonic和声"),
    ("restraint", "/rɪˈstreɪnt/", "制动", "re回 + strain拉"),
    ("operate", "/ˈɒpəreɪt/", "动作", "oper工作 + ate"),
    ("trip", "/trɪp/", "跳闸", "trip绊倒"),
    ("reclose", "/ˌriːˈkloʊz/", "重合闸", "re再 + close合"),
    ("reclosing", "/ˌriːˈkloʊzɪŋ/", "自动重合闸", "reclose重合 + ing"),
    ("singlepole", "/ˈsɪŋɡəlpoʊl/", "单相", "single单 + pole相"),
    ("threepole", "/θriːpoʊl/", "三相", "three三 + pole相"),
    ("blocking", "/ˈblɒkɪŋ/", "闭锁", "block阻挡 + ing"),
    ("outofstep", "/aʊtəvstep/", "失步", "out出 + of + step步"),
    ("synchronism", "/ˈsɪŋkrənɪzəm/", "同步", "syn共同 + chron时间"),
    ("synchronizing", "/ˈsɪŋkrənaɪzɪŋ/", "同期", "synchron同步 + izing"),
    ("check", "/tʃek/", "检查", "check检查"),
    ("synchrocheck", "/ˈsɪŋkroʊtʃek/", "同期检查", "synchro同步 + check检查"),
    ("deadline", "/ˈdedlaɪn/", "无压", "dead死 + line线"),
    ("livebus", "/laɪvbʌs/", "有压母线", "live带电 + bus母线"),
    ("transfer", "/ˈtrænsfɜːr/", "切换", "trans转移 + fer带"),
    ("bustransfer", "/bʌsˈtrænsfɜːr/", "母线切换", "bus母线 + transfer切换"),
    ("fast", "/fɑːst/", "快速", "fast快"),
    ("slow", "/sloʊ/", "慢速", "slow慢"),
    ("selective", "/sɪˈlektɪv/", "选择性", "select选择 + ive"),
    ("sensitivity", "/ˌsensəˈtɪvəti/", "灵敏度", "sens感觉 + itivity"),
    ("stability", "/stəˈbɪləti/", "稳定性", "stable稳定 + ity"),
    ("dependability", "/dɪˌpendəˈbɪləti/", "可依赖性", "depend依赖 + ability"),
    ("security", "/sɪˈkjʊərəti/", "安全性", "secur安全 + ity"),

    # 651-700: 电力电子与FACTS
    ("thyristor", "/θaɪˈrɪstər/", "晶闸管", "thyristor晶闸管"),
    ("scr", "/ɛssiːˈɑːr/", "可控硅", "SCR缩写"),
    ("gto", "/dʒiːtiːˈoʊ/", "门极可关断晶闸管", "GTO缩写"),
    ("igct", "/aɪdʒiːsiːˈtiː/", "集成门极换流晶闸管", "IGCT缩写"),
    ("mosfet", "/ˈmɒsfɛt/", "金属氧化物半导体场效应晶体管", "MOSFET缩写"),
    ("igbt", "/ˈɪɡbɛt/", "绝缘栅双极晶体管", "IGBT缩写"),
    ("gct", "/dʒiːsiːˈtiː/", "门极换流晶闸管", "GCT缩写"),
    ("sit", "/ɛsaɪˈtiː/", "静电感应晶体管", "SIT缩写"),
    ("sith", "/ɛsaɪˈtiːeɪtʃ/", "静电感应晶闸管", "SITH缩写"),
    ("mct", "/ɛmsiːˈtiː/", "MOS控制晶闸管", "MCT缩写"),
    ("powerdiode", "/ˈpaʊərdaɪoʊd/", "功率二极管", "power功率 + diode二极管"),
    ("rectifier", "/ˈrektɪfaɪər/", "整流器", "rect正 + ifier器"),
    ("inverter", "/ɪnˈvɜːrtər/", "逆变器", "invert反转 + er器"),
    ("chopper", "/ˈtʃɒpər/", "斩波器", "chop斩 + er器"),
    ("cycloconverter", "/ˌsaɪkloʊkənˈvɜːrtər/", "周波变换器", "cyclo周波 + converter变换器"),
    ("matrix", "/ˈmeɪtrɪks/", "矩阵", "matrix矩阵"),
    ("converter", "/kənˈvɜːrtər/", "变换器", "convert变换 + er器"),
    ("acdc", "/eɪsiːdiːsiː/", "交直流", "AC-DC"),
    ("dcdc", "/diːsiːdiːsiː/", "直直流", "DC-DC"),
    ("dcac", "/diːsiːeɪsiː/", "直交流", "DC-AC"),
    ("pwm", "/piːdʌbəljuːɛm/", "脉宽调制", "PWM缩写"),
    ("spwm", "/ɛspiːdʌbəljuːɛm/", "正弦脉宽调制", "SPWM缩写"),
    ("svpwm", "/ɛsviːpiːdʌbəljuːɛm/", "空间矢量脉宽调制", "SVPWM缩写"),
    ("modulation", "/ˌmɒdjuˈleɪʃn/", "调制", "modul调制 + ation"),
    ("carrier", "/ˈkæriər/", "载波", "carry携带 + er"),
    ("switching", "/ˈswɪtʃɪŋ/", "开关", "switch开关 + ing"),
    ("commutation", "/ˌkɒmjuˈteɪʃn/", "换相", "commut换向 + ation"),
    ("snubber", "/ˈsnʌbər/", "缓冲器", "snub抑制 + er器"),
    ("clamp", "/klæmp/", "钳位", "clamp钳"),
    ("soft", "/sɒft/", "软", "soft软"),
    ("hard", "/hɑːrd/", "硬", "hard硬"),
    ("switching", "/ˈswɪtʃɪŋ/", "开关", "switch开关 + ing"),
    ("resonant", "/ˈrezənənt/", "谐振", "reson共鸣 + ant"),
    ("quasiresonant", "/ˌkwɑːziˈrezənənt/", "准谐振", "quasi准 + resonant谐振"),
    ("multilevel", "/ˌmʌltiˈlevl/", "多电平", "multi多 + level电平"),
    ("npc", "/ɛnpiːsiː/", "中性点箝位", "NPC缩写"),
    ("hbridge", "/eɪtʃbrɪdʒ/", "H桥", "H-bridge"),
    ("threelevel", "/θriːˈlevl/", "三电平", "three三 + level电平"),
    ("fivelevel", "/faɪvˈlevl/", "五电平", "five五 + level电平"),
    ("cascaded", "/kæˈskeɪdɪd/", "级联", "cascade级联 + d"),
    ("flying", "/ˈflaɪɪŋ/", "飞跨", "fly飞 + ing"),
    ("capacitor", "/kəˈpæsɪtər/", "电容", "capacit容量 + or"),
    ("active", "/ˈæktɪv/", "有源", "act活动 + ive"),
    ("frontend", "/ˈfrentend/", "前端", "front前 + end端"),

    # 701-750: 新能源与储能
    ("lithium", "/ˈlɪθiəm/", "锂", "lith石 + ium"),
    ("lithiumion", "/ˈlɪθiəmaɪən/", "锂离子", "lithium锂 + ion离子"),
    ("lithiummetal", "/ˈlɪθiəmˈmetl/", "锂金属", "lithium锂 + metal金属"),
    ("lithiumpolymer", "/ˈlɪθiəmˈpɒlɪmər/", "锂聚合物", "lithium锂 + polymer聚合物"),
    ("lithiumiron", "/ˈlɪθiəmˈaɪərn/", "磷酸铁锂", "lithium锂 + iron铁"),
    ("lithiummanganese", "/ˈlɪθiəmˈmæŋɡəniːz/", "锰酸锂", "lithium锂 + manganese锰"),
    ("lithiumcobalt", "/ˈlɪθiəmkoʊˈbɔːlt/", "钴酸锂", "lithium锂 + cobalt钴"),
    ("lithiumnickel", "/ˈlɪθiəmˈnɪkl/", "镍酸锂", "lithium锂 + nickel镍"),
    ("ncm", "/ɛnsiːɛm/", "镍钴锰", "NCM缩写"),
    ("nca", "/ɛnsiːeɪ/", "镍钴铝", "NCA缩写"),
    ("lfp", "/ɛlɛfpiː/", "磷酸铁锂", "LFP缩写"),
    ("sodium", "/ˈsoʊdiəm/", "钠", "sod苏打 + ium"),
    ("sodiumion", "/ˈsoʊdiəmaɪən/", "钠离子", "sodium钠 + ion离子"),
    ("solidstate", "/ˈsɒlɪdsteɪt/", "固态", "solid固 + state态"),
    ("solid", "/ˈsɒlɪd/", "固体", "solid固体"),
    ("state", "/steɪt/", "状态", "state状态"),
    ("electrolyte", "/ɪˈlektrəlaɪt/", "电解质", "electro电 + lyte溶解"),
    ("separator", "/ˈsepəreɪtər/", "隔膜", "separ分离 + ator"),
    ("anode", "/ˈænoʊd/", "负极", "an向上 + ode路"),
    ("cathode", "/ˈkæθoʊd/", "正极", "cath向下 + ode路"),
    ("electrode", "/ɪˈlektroʊd/", "电极", "electro电 + ode路"),
    ("intercalation", "/ɪnˌtɜːrkəˈleɪʃn/", "嵌入", "inter间 + cal放置"),
    ("deintercalation", "/diːɪnˌtɜːrkəˈleɪʃn/", "脱嵌", "de脱 + intercalation嵌入"),
    ("soc", "/ɛsoʊsiː/", "荷电状态", "SOC缩写"),
    ("dod", "/diːoʊdiː/", "放电深度", "DOD缩写"),
    ("soh", "/ɛsoʊeɪtʃ/", "健康状态", "SOH缩写"),
    ("cycling", "/ˈsaɪklɪŋ/", "循环", "cycle循环 + ing"),
    ("cycle", "/ˈsaɪkl/", "周期", "cycle周期"),
    ("calendar", "/ˈkælɪndər/", "日历", "calendar日历"),
    ("aging", "/ˈeɪdʒɪŋ/", "老化", "age年龄 + ing"),
    ("degradation", "/ˌdeɡrəˈdeɪʃn/", "衰减", "degrade降级 + ation"),
    ("capacity", "/kəˈpæsəti/", "容量", "capac容纳 + ity"),
    ("fade", "/feɪd/", "衰减", "fade褪色"),
    ("swelling", "/ˈswelɪŋ/", "膨胀", "swell膨胀 + ing"),
    ("thermalrunaway", "/ˈθɜːrmlrʌnəweɪ/", "热失控", "thermal热 + runaway失控"),
    ("bms", "/biːɛmɛs/", "电池管理系统", "BMS缩写"),
    ("batterymanagement", "/ˈbætəriˈmænɪdʒmənt/", "电池管理", "battery电池 + management管理"),
    ("cell", "/sel/", "单体", "cell单元"),
    ("module", "/ˈmɒdjuːl/", "模块", "module模块"),
    ("pack", "/pæk/", "电池包", "pack包"),
    ("rack", "/ræk/", "电池架", "rack架"),
    ("system", "/ˈsɪstəm/", "系统", "system系统"),
    ("string", "/strɪŋ/", "串", "string串"),
    ("parallel", "/ˈpærəlel/", "并联", "para旁 + allel"),
    ("series", "/ˈsɪəriːz/", "串联", "series系列"),

    # 751-800: 智能电网与新兴技术
    ("smart", "/smɑːrt/", "智能", "smart聪明"),
    ("grid", "/ɡrɪd/", "电网", "grid网格"),
    ("smartgrid", "/smɑːrtɡrɪd/", "智能电网", "smart智能 + grid电网"),
    ("microgrid", "/ˈmaɪkroʊɡrɪd/", "微电网", "micro微 + grid电网"),
    ("nanogrid", "/ˈnænoʊɡrɪd/", "纳电网", "nano纳 + grid电网"),
    ("picogrid", "/ˈpiːkoʊɡrɪd/", "皮电网", "pico皮 + grid电网"),
    ("virtual", "/ˈvɜːrtʃuəl/", "虚拟", "virtu美德 + al"),
    ("powerplant", "/ˈpaʊərplænt/", "电厂", "power电 + plant厂"),
    ("vpp", "/viːpiːpiː/", "虚拟电厂", "VPP缩写"),
    ("demandresponse", "/dɪˈmɑːndrɪˈspɒns/", "需求响应", "demand需求 + response响应"),
    ("dr", "/diːˈɑːr/", "需求响应", "DR缩写"),
    ("load", "/loʊd/", "负荷", "load负载"),
    ("shedding", "/ˈʃedɪŋ/", "削减", "shed脱落 + ing"),
    ("curtailment", "/kɜːrˈteɪlmənt/", "限电", "curtail缩减 + ment"),
    ("peak", "/piːk/", "峰值", "peak峰"),
    ("shaving", "/ˈʃeɪvɪŋ/", "削峰", "shave削 + ing"),
    ("filling", "/ˈfɪlɪŋ/", "填谷", "fill填 + ing"),
    ("valley", "/ˈvæli/", "谷值", "valley谷"),
    ("shift", "/ʃɪft/", "转移", "shift移动"),
    ("shifting", "/ˈʃɪftɪŋ/", "移峰", "shift转移 + ing"),
    ("aggregator", "/ˈæɡrɪɡeɪtər/", "聚合商", "aggregate聚合 + or"),
    ("prosumer", "/prəˈsuːmər/", "产消者", "produce生产 + consumer消费者"),
    ("consumer", "/kənˈsuːmər/", "消费者", "consume消费 + er"),
    ("producer", "/prəˈduːsər/", "生产者", "produce生产 + er"),
    ("distributed", "/dɪˈstrɪbjuːtɪd/", "分布式", "distribute分布 + d"),
    ("energyresource", "/ˈenərdʒirɪˈsɔːrs/", "能源资源", "energy能源 + resource资源"),
    ("der", "/diːiːˈɑːr/", "分布式能源", "DER缩写"),
    ("dgre", "/diːdʒiːɑːriːiː/", "分布式绿色能源", "DGRE缩写"),
    ("behind", "/bɪˈhaɪnd/", "在...之后", "behind后面"),
    ("meter", "/ˈmiːtər/", "表计", "meter计量"),
    ("behindthemeter", "/bɪˈhaɪndðəˈmiːtər/", "表后", "behind后 + meter表"),
    ("front", "/frʌnt/", "前面", "front前"),
    ("frontof", "/frʌntəv/", "表前", "front前 + of"),
    ("metering", "/ˈmiːtərɪŋ/", "计量", "meter计量 + ing"),
    ("advanced", "/ədˈvɑːnst/", "高级", "advance前进 + d"),
    ("ami", "/eɪɛmaɪ/", "高级量测体系", "AMI缩写"),
    ("mdms", "/ɛmdiːɛmɛs/", "电表数据管理系统", "MDMS缩写"),
    ("cis", "/siːaɪɛs/", "客户信息系统", "CIS缩写"),
    ("oms", "/oʊɛmɛs/", "停电管理系统", "OMS缩写"),
    ("dms", "/diːɛmɛs/", "配电管理系统", "DMS缩写"),
    ("ems", "/iːɛmɛs/", "能量管理系统", "EMS缩写"),
    ("scada", "/ˈskɑːdə/", "数据采集与监视控制", "SCADA缩写"),
    ("gis", "/dʒiːaɪɛs/", "地理信息系统", "GIS缩写"),
    ("dbr", "/diːbiːˈɑːr/", "基于分布式的资源", "DBR缩写"),
    ("telemetry", "/təˈlemətri/", "遥测", "tele远 + metry测量"),
    ("telesignal", "/ˈtelɪsɪɡnəl/", "遥信", "tele远 + signal信号"),
    ("telecontrol", "/ˈtelɪkənˈtroʊl/", "遥控", "tele远 + control控制"),
    ("teleadjusting", "/ˈtelɪəˈdʒʌstɪŋ/", "遥调", "tele远 + adjusting调节"),
    ("rtu", "/ɑːrtiːˈjuː/", "远方终端单元", "RTU缩写"),
    ("ftu", "/ɛftiːˈjuː/", "馈线终端单元", "FTU缩写"),
    ("dtu", "/diːtiːˈjuː/", "配电终端单元", "DTU缩写"),
    ("ttu", "/tiːtiːˈjuː/", "变压器终端单元", "TTU缩写"),
    ("pmu", "/piːɛmˈjuː/", "同步相量测量单元", "PMU缩写"),
    ("wams", "/dʌbəljuːeɪɛmɛs/", "广域测量系统", "WAMS缩写"),
    ("phasor", "/ˈfeɪzər/", "相量", "phas相位 + or"),
    ("synchrophasor", "/ˈsɪŋkroʊfeɪzər/", "同步相量", "synchro同步 + phasor相量"),
    ("stateestimation", "/steɪtɛstɪˈmeɪʃn/", "状态估计", "state状态 + estimation估计"),
]

def create_entry(id_num, root, phonetic, meaning, memory_tip):
    """Create a complete entry for the electric power root"""
    freq = id_num  # frequency equals id for 501-800

    # Create word variations
    words = [
        {
            "word": root,
            "phonetic": phonetic,
            "partOfSpeech": "n.",
            "meaning": meaning,
            "memoryTip": f"词根 {root} 表示 {meaning}",
            "root": root,
            "rootPhonetic": phonetic,
            "rootMeaning": meaning,
            "rootPhrases": [],
            "wordPhrases": []
        },
        {
            "word": f"{root}age",
            "phonetic": phonetic,
            "partOfSpeech": "n.",
            "meaning": f"{meaning}量",
            "memoryTip": f"词根 {root} 表示 {meaning}",
            "root": root,
            "rootPhonetic": phonetic,
            "rootMeaning": meaning,
            "rootPhrases": [],
            "wordPhrases": []
        },
        {
            "word": f"{root}al",
            "phonetic": phonetic,
            "partOfSpeech": "adj.",
            "meaning": f"{meaning}的",
            "memoryTip": f"词根 {root} 表示 {meaning}",
            "root": root,
            "rootPhonetic": phonetic,
            "rootMeaning": meaning,
            "rootPhrases": [],
            "wordPhrases": []
        },
        {
            "word": f"{root}ation",
            "phonetic": phonetic,
            "partOfSpeech": "n.",
            "meaning": f"{meaning}过程",
            "memoryTip": f"词根 {root} 表示 {meaning}",
            "root": root,
            "rootPhonetic": phonetic,
            "rootMeaning": meaning,
            "rootPhrases": [],
            "wordPhrases": []
        }
    ]

    phrases = [
        f"{root} {meaning}",
        f"{root}age {meaning}",
        f"{root}al {meaning}",
        f"{root}ation {meaning}"
    ]

    return {
        "id": id_num + 800,  # Add 800 to id to match existing pattern (1301+)
        "root": root,
        "phonetic": phonetic,
        "partOfSpeech": "词根",
        "meaning": meaning,
        "frequency": freq,
        "category": "电力",
        "words": words,
        "phrases": phrases,
        "mnemonic": f"{root}→{meaning}"
    }

# Generate new entries
new_entries = []
for i, (root, phonetic, meaning, tip) in enumerate(electric_power_roots):
    entry_id = 501 + i
    entry = create_entry(entry_id, root, phonetic, meaning, tip)
    new_entries.append(entry)

print(f"Generated {len(new_entries)} new entries")
print(f"First new entry ID: {new_entries[0]['id']}, frequency: {new_entries[0]['frequency']}")
print(f"Last new entry ID: {new_entries[-1]['id']}, frequency: {new_entries[-1]['frequency']}")

# Append to existing data
data.extend(new_entries)

# Save updated file
with open('f:/claudeanli/beidanci3/src/data/electric-power.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\nTotal entries now: {len(data)}")
print("File saved successfully!")
