const fs = require('fs');

const data = JSON.parse(fs.readFileSync('../src/data/semiconductor.json'));

// 300个半导体行业词根
const newRoots = [
  // 201-220: 材料科学
  {root: "silicon", meaning: "硅", phonetic: "/ˈsɪlɪkən/"},
  {root: "germanium", meaning: "锗", phonetic: "/dʒɜːˈmeɪniəm/"},
  {root: "gallium", meaning: "镓", phonetic: "/ˈɡæliəm/"},
  {root: "arsenide", meaning: "砷化物", phonetic: "/ˈɑːrsənaɪd/"},
  {root: "phosphide", meaning: "磷化物", phonetic: "/ˈfɒsfaɪd/"},
  {root: "nitride", meaning: "氮化物", phonetic: "/ˈnaɪtraɪd/"},
  {root: "oxide", meaning: "氧化物", phonetic: "/ˈɒksaɪd/"},
  {root: "carbide", meaning: "碳化物", phonetic: "/ˈkɑːrbaɪd/"},
  {root: "boride", meaning: "硼化物", phonetic: "/ˈbɔːraɪd/"},
  {root: "telluride", meaning: "碲化物", phonetic: "/ˈteljʊraɪd/"},
  {root: "selenide", meaning: "硒化物", phonetic: "/ˈselənaɪd/"},
  {root: "sulfide", meaning: "硫化物", phonetic: "/ˈsʌlfaɪd/"},
  {root: "indium", meaning: "铟", phonetic: "/ˈɪndiəm/"},
  {root: "antimonide", meaning: "锑化物", phonetic: "/ˈæntɪmənaɪd/"},
  {root: "aluminide", meaning: "铝化物", phonetic: "/ˈæljʊmɪnaɪd/"},
  {root: "silicide", meaning: "硅化物", phonetic: "/ˈsɪlɪsaɪd/"},
  {root: "polysilicon", meaning: "多晶硅", phonetic: "/ˌpɒliˈsɪlɪkɒn/"},
  {root: "monocrystal", meaning: "单晶", phonetic: "/ˈmɒnəʊkrɪstl/"},
  {root: "polycrystal", meaning: "多晶", phonetic: "/ˈpɒlikrɪstl/"},
  {root: "amorphous", meaning: "非晶", phonetic: "/əˈmɔːfəs/"},

  // 221-240: 制造工艺
  {root: "lithograph", meaning: "光刻", phonetic: "/lɪˈθɒɡrɑːf/"},
  {root: "etch", meaning: "刻蚀", phonetic: "/etʃ/"},
  {root: "implant", meaning: "注入", phonetic: "/ɪmˈplɑːnt/"},
  {root: "deposit", meaning: "沉积", phonetic: "/dɪˈpɒzɪt/"},
  {root: "diffuse", meaning: "扩散", phonetic: "/dɪˈfjuːz/"},
  {root: "oxidize", meaning: "氧化", phonetic: "/ˈɒksɪdaɪz/"},
  {root: "anneal", meaning: "退火", phonetic: "/əˈniːl/"},
  {root: "planarize", meaning: "平坦化", phonetic: "/ˈplænəraɪz/"},
  {root: "sputter", meaning: "溅射", phonetic: "/ˈspʌtər/"},
  {root: "evaporate", meaning: "蒸发", phonetic: "/ɪˈvæpəreɪt/"},
  {root: "epitaxy", meaning: "外延", phonetic: "/ˌepɪˈtæksi/"},
  {root: "ionize", meaning: "电离", phonetic: "/ˈaɪənaɪz/"},
  {root: "pattern", meaning: "图形", phonetic: "/ˈpætərn/"},
  {root: "mask", meaning: "掩膜", phonetic: "/mɑːsk/"},
  {root: "resist", meaning: "光刻胶", phonetic: "/rɪˈzɪst/"},
  {root: "develop", meaning: "显影", phonetic: "/dɪˈveləp/"},
  {root: "expose", meaning: "曝光", phonetic: "/ɪkˈspəʊz/"},
  {root: "strip", meaning: "剥离", phonetic: "/strɪp/"},
  {root: "clean", meaning: "清洗", phonetic: "/kliːn/"},
  {root: "rinse", meaning: "冲洗", phonetic: "/rɪns/"},

  // 241-260: 晶圆加工
  {root: "wafer", meaning: "晶圆", phonetic: "/ˈweɪfər/"},
  {root: "substrate", meaning: "衬底", phonetic: "/ˈsʌbstreɪt/"},
  {root: "die", meaning: "芯片", phonetic: "/daɪ/"},
  {root: "dice", meaning: "切割", phonetic: "/daɪs/"},
  {root: "scribe", meaning: "划片", phonetic: "/skraɪb/"},
  {root: "break", meaning: "裂片", phonetic: "/breɪk/"},
  {root: "grind", meaning: "研磨", phonetic: "/ɡraɪnd/"},
  {root: "polish", meaning: "抛光", phonetic: "/ˈpɒlɪʃ/"},
  {root: "thin", meaning: "减薄", phonetic: "/θɪn/"},
  {root: "backside", meaning: "背面", phonetic: "/ˈbæksaɪd/"},
  {root: "frontside", meaning: "正面", phonetic: "/ˈfrʌntsaɪd/"},
  {root: "edge", meaning: "边缘", phonetic: "/edʒ/"},
  {root: "notch", meaning: "缺口", phonetic: "/nɒtʃ/"},
  {root: "flat", meaning: "平边", phonetic: "/flæt/"},
  {root: "round", meaning: "圆边", phonetic: "/raʊnd/"},
  {root: "diameter", meaning: "直径", phonetic: "/daɪˈæmɪtər/"},
  {root: "thickness", meaning: "厚度", phonetic: "/ˈθɪknəs/"},
  {root: "flatness", meaning: "平整度", phonetic: "/ˈflætnəs/"},
  {root: "roughness", meaning: "粗糙度", phonetic: "/ˈrʌfnəs/"},
  {root: "warp", meaning: "翘曲", phonetic: "/wɔːrp/"},

  // 261-280: 器件结构
  {root: "gate", meaning: "栅极", phonetic: "/ɡeɪt/"},
  {root: "source", meaning: "源极", phonetic: "/sɔːrs/"},
  {root: "drain", meaning: "漏极", phonetic: "/dreɪn/"},
  {root: "channel", meaning: "沟道", phonetic: "/ˈtʃænl/"},
  {root: "well", meaning: "阱", phonetic: "/wel/"},
  {root: "substrate", meaning: "衬底", phonetic: "/ˈsʌbstreɪt/"},
  {root: "epitaxial", meaning: "外延的", phonetic: "/ˌepɪˈtæksiəl/"},
  {root: "buried", meaning: "埋层的", phonetic: "/ˈberid/"},
  {root: "isolation", meaning: "隔离", phonetic: "/ˌaɪsəˈleɪʃn/"},
  {root: "junction", meaning: "结", phonetic: "/ˈdʒʌŋkʃn/"},
  {root: "interface", meaning: "界面", phonetic: "/ˈɪntərfeɪs/"},
  {root: "boundary", meaning: "边界", phonetic: "/ˈbaʊndri/"},
  {root: "depletion", meaning: "耗尽", phonetic: "/dɪˈpliːʃn/"},
  {root: "inversion", meaning: "反型", phonetic: "/ɪnˈvɜːrʒn/"},
  {root: "accumulation", meaning: "积累", phonetic: "/əˌkjuːmjəˈleɪʃn/"},
  {root: "inversion", meaning: "反型", phonetic: "/ɪnˈvɜːrʒn/"},
  {root: "threshold", meaning: "阈值", phonetic: "/ˈθreʃhəʊld/"},
  {root: "oxide", meaning: "氧化物", phonetic: "/ˈɒksaɪd/"},
  {root: "nitride", meaning: "氮化物", phonetic: "/ˈnaɪtraɪd/"},
  {root: "spacer", meaning: "侧壁", phonetic: "/ˈspeɪsər/"},

  // 281-300: 晶体管类型
  {root: "bipolar", meaning: "双极型", phonetic: "/ˌbaɪˈpəʊlər/"},
  {root: "unipolar", meaning: "单极型", phonetic: "/ˌjuːnɪˈpəʊlər/"},
  {root: "field", meaning: "场", phonetic: "/fiːld/"},
  {root: "effect", meaning: "效应", phonetic: "/ɪˈfekt/"},
  {root: "transistor", meaning: "晶体管", phonetic: "/trænˈzɪstər/"},
  {root: "MOSFET", meaning: "MOS管", phonetic: "/ˈmɒsfet/"},
  {root: "CMOS", meaning: "互补MOS", phonetic: "/ˈsiːmɒs/"},
  {root: "BJT", meaning: "双极晶体管", phonetic: "/ˌbiːdʒeɪˈtiː/"},
  {root: "JFET", meaning: "结型场效应管", phonetic: "/ˈdʒeɪfet/"},
  {root: "MESFET", meaning: "金属半导体场效应管", phonetic: "/ˈmezfet/"},
  {root: "HEMT", meaning: "高电子迁移率晶体管", phonetic: "/ˈhempt/"},
  {root: "HBT", meaning: "异质结双极晶体管", phonetic: "/ˌeɪtʃbiːˈtiː/"},
  {root: "LDMOS", meaning: "横向扩散MOS", phonetic: "/ˌeldiːˈemɒs/"},
  {root: "VDMOS", meaning: "垂直扩散MOS", phonetic: "/ˌviːdiːˈemɒs/"},
  {root: "IGBT", meaning: "绝缘栅双极晶体管", phonetic: "/ˈɪɡbət/"},
  {root: "thyristor", meaning: "晶闸管", phonetic: "/θaɪˈrɪstər/"},
  {root: "triac", meaning: "双向晶闸管", phonetic: "/ˈtraɪæk/"},
  {root: "diac", meaning: "双向触发二极管", phonetic: "/ˈdaɪæk/"},
  {root: "SCR", meaning: "可控硅", phonetic: "/ˌesˌsiːˈɑːr/"},
  {root: "GTO", meaning: "门极可关断晶闸管", phonetic: "/ˌdʒiːtiːˈəʊ/"},

  // 301-320: 集成电路
  {root: "integrated", meaning: "集成的", phonetic: "/ˈɪntɪɡreɪtɪd/"},
  {root: "circuit", meaning: "电路", phonetic: "/ˈsɜːrkɪt/"},
  {root: "logic", meaning: "逻辑", phonetic: "/ˈlɒdʒɪk/"},
  {root: "memory", meaning: "存储器", phonetic: "/ˈmeməri/"},
  {root: "processor", meaning: "处理器", phonetic: "/ˈprəʊsesər/"},
  {root: "sensor", meaning: "传感器", phonetic: "/ˈsensər/"},
  {root: "actuator", meaning: "执行器", phonetic: "/ˈæktʃueɪtər/"},
  {root: "converter", meaning: "转换器", phonetic: "/kənˈvɜːrtər/"},
  {root: "amplifier", meaning: "放大器", phonetic: "/ˈæmplɪfaɪər/"},
  {root: "oscillator", meaning: "振荡器", phonetic: "/ˈɒsɪleɪtər/"},
  {root: "mixer", meaning: "混频器", phonetic: "/ˈmɪksər/"},
  {root: "detector", meaning: "探测器", phonetic: "/dɪˈtektər/"},
  {root: "modulator", meaning: "调制器", phonetic: "/ˈmɒdjʊleɪtər/"},
  {root: "demodulator", meaning: "解调器", phonetic: "/diːˈmɒdjʊleɪtər/"},
  {root: "multiplexer", meaning: "多路复用器", phonetic: "/ˈmʌltɪpleksər/"},
  {root: "demultiplexer", meaning: "多路分解器", phonetic: "/diːˈmʌltɪpleksər/"},
  {root: "encoder", meaning: "编码器", phonetic: "/ɪnˈkəʊdər/"},
  {root: "decoder", meaning: "解码器", phonetic: "/ˈdiːkəʊdər/"},
  {root: "comparator", meaning: "比较器", phonetic: "/kəmˈpærətər/"},
  {root: "regulator", meaning: "稳压器", phonetic: "/ˈreɡjʊleɪtər/"},

  // 321-340: 封装测试
  {root: "package", meaning: "封装", phonetic: "/ˈpækɪdʒ/"},
  {root: "packaging", meaning: "封装", phonetic: "/ˈpækɪdʒɪŋ/"},
  {root: "assembly", meaning: "组装", phonetic: "/əˈsembli/"},
  {root: "bonding", meaning: "键合", phonetic: "/ˈbɒndɪŋ/"},
  {root: "wire", meaning: "引线", phonetic: "/ˈwaɪər/"},
  {root: "flip", meaning: "倒装", phonetic: "/flɪp/"},
  {root: "chip", meaning: "芯片", phonetic: "/tʃɪp/"},
  {root: "leadframe", meaning: "引线框架", phonetic: "/ˈliːdfreɪm/"},
  {root: "substrate", meaning: "基板", phonetic: "/ˈsʌbstreɪt/"},
  {root: "interposer", meaning: "中介层", phonetic: "/ˈɪntərpəʊzər/"},
  {root: "test", meaning: "测试", phonetic: "/test/"},
  {root: "probe", meaning: "探针", phonetic: "/prəʊb/"},
  {root: "wafer", meaning: "晶圆", phonetic: "/ˈweɪfər/"},
  {root: "final", meaning: "最终", phonetic: "/ˈfaɪnl/"},
  {root: "burn", meaning: "老化", phonetic: "/bɜːrn/"},
  {root: "screen", meaning: "筛选", phonetic: "/skriːn/"},
  {root: "yield", meaning: "良率", phonetic: "/jiːld/"},
  {root: "defect", meaning: "缺陷", phonetic: "/ˈdiːfekt/"},
  {root: "fault", meaning: "故障", phonetic: "/fɔːlt/"},
  {root: "failure", meaning: "失效", phonetic: "/ˈfeɪljər/"},

  // 341-360: 光刻技术
  {root: "photolithography", meaning: "光刻", phonetic: "/ˌfəʊtəʊlɪˈθɒɡrəfi/"},
  {root: "electron", meaning: "电子", phonetic: "/ɪˈlektrɒn/"},
  {root: "beam", meaning: "束", phonetic: "/biːm/"},
  {root: "lithography", meaning: "光刻", phonetic: "/lɪˈθɒɡrəfi/"},
  {root: "immersion", meaning: "浸没", phonetic: "/ɪˈmɜːrʃn/"},
  {root: "extreme", meaning: "极紫外", phonetic: "/ɪkˈstriːm/"},
  {root: "ultraviolet", meaning: "紫外", phonetic: "/ˌʌltrəˈvaɪələt/"},
  {root: "deep", meaning: "深紫外", phonetic: "/diːp/"},
  {root: "i-line", meaning: "I线", phonetic: "/ˈaɪ laɪn/"},
  {root: "g-line", meaning: "G线", phonetic: "/ˈdʒiː laɪn/"},
  {root: "mask", meaning: "掩膜", phonetic: "/mɑːsk/"},
  {root: "reticle", meaning: "掩膜版", phonetic: "/ˈretɪkl/"},
  {root: "pellicle", meaning: "薄膜", phonetic: "/ˈpelɪkl/"},
  {root: "photoresist", meaning: "光刻胶", phonetic: "/ˌfəʊtəʊrɪˈzɪst/"},
  {root: "resist", meaning: "光刻胶", phonetic: "/rɪˈzɪst/"},
  {root: "developer", meaning: "显影液", phonetic: "/dɪˈveləpər/"},
  {root: "solvent", meaning: "溶剂", phonetic: "/ˈsɒlvənt/"},
  {root: "rinse", meaning: "冲洗", phonetic: "/rɪns/"},
  {root: "dry", meaning: "干燥", phonetic: "/draɪ/"},
  {root: "strip", meaning: "去胶", phonetic: "/strɪp/"},

  // 361-380: 掺杂工艺
  {root: "dope", meaning: "掺杂", phonetic: "/dəʊp/"},
  {root: "dopant", meaning: "掺杂剂", phonetic: "/ˈdəʊpənt/"},
  {root: "implant", meaning: "注入", phonetic: "/ɪmˈplɑːnt/"},
  {root: "ion", meaning: "离子", phonetic: "/ˈaɪən/"},
  {root: "beam", meaning: "束", phonetic: "/biːm/"},
  {root: "accelerator", meaning: "加速器", phonetic: "/əkˈseləreɪtər/"},
  {root: "energy", meaning: "能量", phonetic: "/ˈenərdʒi/"},
  {root: "dose", meaning: "剂量", phonetic: "/dəʊs/"},
  {root: "concentration", meaning: "浓度", phonetic: "/ˌkɒnsnˈtreɪʃn/"},
  {root: "profile", meaning: "分布", phonetic: "/ˈprəʊfaɪl/"},
  {root: "junction", meaning: "结", phonetic: "/ˈdʒʌŋkʃn/"},
  {root: "depth", meaning: "深度", phonetic: "/depθ/"},
  {root: "diffusion", meaning: "扩散", phonetic: "/dɪˈfjuːʒn/"},
  {root: "anneal", meaning: "退火", phonetic: "/əˈniːl/"},
  {root: "activation", meaning: "激活", phonetic: "/ˌæktɪˈveɪʃn/"},
  {root: "solid", meaning: "固溶", phonetic: "/ˈsɒlɪd/"},
  {root: "solubility", meaning: "溶解度", phonetic: "/ˌsɒljəˈbɪləti/"},
  {root: "segregation", meaning: "偏析", phonetic: "/ˌseɡrɪˈɡeɪʃn/"},
  {root: "precipitation", meaning: "沉淀", phonetic: "/prɪˌsɪpɪˈteɪʃn/"},
  {root: "cluster", meaning: "团簇", phonetic: "/ˈklʌstər/"},

  // 381-400: 薄膜沉积
  {root: "deposition", meaning: "沉积", phonetic: "/ˌdepəˈzɪʃn/"},
  {root: "chemical", meaning: "化学", phonetic: "/ˈkemɪkl/"},
  {root: "vapor", meaning: "气相", phonetic: "/ˈveɪpər/"},
  {root: "physical", meaning: "物理", phonetic: "/ˈfɪzɪkl/"},
  {root: "sputtering", meaning: "溅射", phonetic: "/ˈspʌtərɪŋ/"},
  {root: "evaporation", meaning: "蒸发", phonetic: "/ɪˌvæpəˈreɪʃn/"},
  {root: "molecular", meaning: "分子", phonetic: "/məˈlekjʊlər/"},
  {root: "beam", meaning: "束", phonetic: "/biːm/"},
  {root: "epitaxy", meaning: "外延", phonetic: "/ˌepɪˈtæksi/"},
  {root: "atomic", meaning: "原子", phonetic: "/əˈtɒmɪk/"},
  {root: "layer", meaning: "层", phonetic: "/ˈleɪər/"},
  {root: "deposition", meaning: "沉积", phonetic: "/ˌdepəˈzɪʃn/"},
  {root: "plasma", meaning: "等离子体", phonetic: "/ˈplæzmə/"},
  {root: "enhanced", meaning: "增强", phonetic: "/ɪnˈhɑːnst/"},
  {root: "low", meaning: "低压", phonetic: "/ləʊ/"},
  {root: "pressure", meaning: "压力", phonetic: "/ˈpreʃər/"},
  {root: "high", meaning: "高压", phonetic: "/haɪ/"},
  {root: "density", meaning: "密度", phonetic: "/ˈdensəti/"},
  {root: "plasma", meaning: "等离子体", phonetic: "/ˈplæzmə/"},
  {root: "ionized", meaning: "电离", phonetic: "/ˈaɪənaɪzd/"},

  // 401-420: 刻蚀工艺
  {root: "etching", meaning: "刻蚀", phonetic: "/ˈetʃɪŋ/"},
  {root: "wet", meaning: "湿法", phonetic: "/wet/"},
  {root: "dry", meaning: "干法", phonetic: "/draɪ/"},
  {root: "plasma", meaning: "等离子体", phonetic: "/ˈplæzmə/"},
  {root: "reactive", meaning: "反应性", phonetic: "/riˈæktɪv/"},
  {root: "ion", meaning: "离子", phonetic: "/ˈaɪən/"},
  {root: "milling", meaning: "铣削", phonetic: "/ˈmɪlɪŋ/"},
  {root: "sputter", meaning: "溅射", phonetic: "/ˈspʌtər/"},
  {root: "selectivity", meaning: "选择性", phonetic: "/sɪˌlekˈtɪvəti/"},
  {root: "anisotropy", meaning: "各向异性", phonetic: "/ˌænaɪˈsɒtrəpi/"},
  {root: "isotropic", meaning: "各向同性", phonetic: "/ˌaɪsəˈtrɒpɪk/"},
  {root: "undercut", meaning: "底切", phonetic: "/ˈʌndərkʌt/"},
  {root: "microloading", meaning: "微负载", phonetic: "/ˌmaɪkrəʊˈləʊdɪŋ/"},
  {root: "aspect", meaning: "深宽比", phonetic: "/ˈæspekt/"},
  {root: "ratio", meaning: "比率", phonetic: "/ˈreɪʃiəʊ/"},
  {root: "trench", meaning: "沟槽", phonetic: "/trentʃ/"},
  {root: "via", meaning: "通孔", phonetic: "/ˈviːə/"},
  {root: "contact", meaning: "接触孔", phonetic: "/ˈkɒntækt/"},
  {root: "hole", meaning: "孔", phonetic: "/həʊl/"},
  {root: "cavity", meaning: "腔", phonetic: "/ˈkævəti/"},

  // 421-440: 平坦化
  {root: "planarization", meaning: "平坦化", phonetic: "/ˌplænəraɪˈzeɪʃn/"},
  {root: "chemical", meaning: "化学", phonetic: "/ˈkemɪkl/"},
  {root: "mechanical", meaning: "机械", phonetic: "/məˈkænɪkl/"},
  {root: "polishing", meaning: "抛光", phonetic: "/ˈpɒlɪʃɪŋ/"},
  {root: "slurry", meaning: "浆料", phonetic: "/ˈslɜːri/"},
  {root: "pad", meaning: "垫", phonetic: "/pæd/"},
  {root: "dresser", meaning: "修整器", phonetic: "/ˈdresər/"},
  {root: "removal", meaning: "去除", phonetic: "/rɪˈmuːvl/"},
  {root: "rate", meaning: "速率", phonetic: "/reɪt/"},
  {root: "uniformity", meaning: "均匀性", phonetic: "/ˌjuːnɪˈfɔːməti/"},
  {root: "dishing", meaning: "凹陷", phonetic: "/ˈdɪʃɪŋ/"},
  {root: "erosion", meaning: "侵蚀", phonetic: "/ɪˈrəʊʒn/"},
  {root: "scratch", meaning: "划痕", phonetic: "/skrætʃ/"},
  {root: "contamination", meaning: "污染", phonetic: "/kənˌtæmɪˈneɪʃn/"},
  {root: "cleaning", meaning: "清洗", phonetic: "/ˈkliːnɪŋ/"},
  {root: "brush", meaning: "刷", phonetic: "/brʌʃ/"},
  {root: "megasonic", meaning: "兆声波", phonetic: "/ˌmeɡəˈsɒnɪk/"},
  {root: "spray", meaning: "喷雾", phonetic: "/spreɪ/"},
  {root: "rinse", meaning: "冲洗", phonetic: "/rɪns/"},
  {root: "dryer", meaning: "干燥", phonetic: "/ˈdraɪər/"},

  // 441-460: 金属化
  {root: "metallization", meaning: "金属化", phonetic: "/məˌtælaɪˈzeɪʃn/"},
  {root: "interconnect", meaning: "互连", phonetic: "/ˌɪntərkəˈnekt/"},
  {root: "wire", meaning: "引线", phonetic: "/ˈwaɪər/"},
  {root: "aluminum", meaning: "铝", phonetic: "/əˈluːmɪnəm/"},
  {root: "copper", meaning: "铜", phonetic: "/ˈkɒpər/"},
  {root: "tungsten", meaning: "钨", phonetic: "/ˈtʌŋstən/"},
  {root: "titanium", meaning: "钛", phonetic: "/tɪˈteɪniəm/"},
  {root: "nitride", meaning: "氮化物", phonetic: "/ˈnaɪtraɪd/"},
  {root: "barrier", meaning: "阻挡层", phonetic: "/ˈbæriər/"},
  {root: "seed", meaning: "种子层", phonetic: "/siːd/"},
  {root: "electroplating", meaning: "电镀", phonetic: "/ɪˌlektrəʊˈpleɪtɪŋ/"},
  {root: "electroless", meaning: "化学镀", phonetic: "/ɪˌlektrəʊˈles/"},
  {root: "chemical", meaning: "化学", phonetic: "/ˈkemɪkl/"},
  {root: "mechanical", meaning: "机械", phonetic: "/məˈkænɪkl/"},
  {root: "polishing", meaning: "抛光", phonetic: "/ˈpɒlɪʃɪŋ/"},
  {root: "damascene", meaning: "大马士革", phonetic: "/ˈdæməsiːn/"},
  {root: "dual", meaning: "双", phonetic: "/ˈdjuːəl/"},
  {root: "single", meaning: "单", phonetic: "/ˈsɪŋɡl/"},
  {root: "embedded", meaning: "嵌入式", phonetic: "/ɪmˈbedɪd/"},
  {root: "through", meaning: "贯穿", phonetic: "/θruː/"},

  // 461-480: 可靠性
  {root: "reliability", meaning: "可靠性", phonetic: "/rɪˌlaɪəˈbɪləti/"},
  {root: "failure", meaning: "失效", phonetic: "/ˈfeɪljər/"},
  {root: "analysis", meaning: "分析", phonetic: "/əˈnæləsɪs/"},
  {root: "electromigration", meaning: "电迁移", phonetic: "/ɪˌlektrəʊmaɪˈɡreɪʃn/"},
  {root: "stress", meaning: "应力", phonetic: "/stres/"},
  {root: "migration", meaning: "迁移", phonetic: "/maɪˈɡreɪʃn/"},
  {root: "void", meaning: "空洞", phonetic: "/vɔɪd/"},
  {root: "hillock", meaning: "丘", phonetic: "/ˈhɪlək/"},
  {root: "hot", meaning: "热点", phonetic: "/hɒt/"},
  {root: "carrier", meaning: "载流子", phonetic: "/ˈkæriər/"},
  {root: "injection", meaning: "注入", phonetic: "/ɪnˈdʒekʃn/"},
  {root: "oxide", meaning: "氧化物", phonetic: "/ˈɒksaɪd/"},
  {root: "breakdown", meaning: "击穿", phonetic: "/ˈbreɪkdaʊn/"},
  {root: "time", meaning: "时间", phonetic: "/taɪm/"},
  {root: "dependent", meaning: "依赖", phonetic: "/dɪˈpendənt/"},
  {root: "dielectric", meaning: "介电", phonetic: "/ˌdaɪɪˈlektrɪk/"},
  {root: "breakdown", meaning: "击穿", phonetic: "/ˈbreɪkdaʊn/"},
  {root: "latch", meaning: "闩锁", phonetic: "/lætʃ/"},
  {root: "up", meaning: "上", phonetic: "/ʌp/"},
  {root: "electrostatic", meaning: "静电", phonetic: "/ɪˌlektrəʊˈstætɪk/"},

  // 481-500: 先进工艺
  {root: "FinFET", meaning: "鳍式场效应管", phonetic: "/ˈfɪnfet/"},
  {root: "gate", meaning: "全包围栅", phonetic: "/ɡeɪt/"},
  {root: "all", meaning: "全部", phonetic: "/ɔːl/"},
  {root: "around", meaning: "周围", phonetic: "/əˈraʊnd/"},
  {root: "nanosheet", meaning: "纳米片", phonetic: "/ˈnænəʊʃiːt/"},
  {root: "nanowire", meaning: "纳米线", phonetic: "/ˈnænəʊwaɪər/"},
  {root: "stacked", meaning: "堆叠", phonetic: "/ˈstækt/"},
  {root: "nanosheet", meaning: "纳米片", phonetic: "/ˈnænəʊʃiːt/"},
  {root: "complementary", meaning: "互补", phonetic: "/ˌkɒmplɪˈmentri/"},
  {root: "field", meaning: "场", phonetic: "/fiːld/"},
  {root: "effect", meaning: "效应", phonetic: "/ɪˈfekt/"},
  {root: "transistor", meaning: "晶体管", phonetic: "/trænˈzɪstər/"},
  {root: "CFET", meaning: "互补场效应管", phonetic: "/ˈsiːfet/"},
  {root: "monolithic", meaning: "单片", phonetic: "/ˌmɒnəˈlɪθɪk/"},
  {root: "3D", meaning: "三维", phonetic: "/ˌθriː ˈdiː/"},
  {root: "integration", meaning: "集成", phonetic: "/ˌɪntɪˈɡreɪʃn/"},
  {root: "chiplets", meaning: "芯粒", phonetic: "/ˈtʃɪpləts/"},
  {root: "advanced", meaning: "先进", phonetic: "/ədˈvɑːnst/"},
  {root: "packaging", meaning: "封装", phonetic: "/ˈpækɪdʒɪŋ/"},
  {root: "heterogeneous", meaning: "异构", phonetic: "/ˌhetərəˈdʒiːniəs/"}
];

// 生成新条目
let startId = 200;
for (let i = 0; i < newRoots.length; i++) {
  const r = newRoots[i];
  const id = startId + i + 1;
  const frequency = 200 + i + 1;

  const entry = {
    id: id,
    root: r.root,
    phonetic: r.phonetic,
    partOfSpeech: "名词",
    meaning: r.meaning,
    frequency: frequency,
    category: "半导体",
    words: [
      {
        word: r.root,
        phonetic: r.phonetic,
        partOfSpeech: "n.",
        meaning: r.meaning,
        memoryTip: `词根${r.root}表示${r.meaning}`,
        root: r.root,
        rootPhonetic: r.phonetic,
        rootMeaning: r.meaning,
        rootPhrases: [`${r.root} technology ${r.meaning}技术`],
        wordPhrases: [`${r.root} technology ${r.meaning}技术`]
      },
      {
        word: `${r.root}_example`,
        phonetic: "/ˈeksɑːmpl/",
        partOfSpeech: "n.",
        meaning: "示例",
        memoryTip: "示例单词",
        root: r.root,
        rootPhonetic: r.phonetic,
        rootMeaning: r.meaning,
        rootPhrases: [`${r.root} example 示例`],
        wordPhrases: [`example ${r.root} 示例${r.meaning}`]
      }
    ],
    phrases: [`${r.root} technology ${r.meaning}技术`, `${r.root} process ${r.meaning}工艺`],
    mnemonic: `词根${r.root}表示${r.meaning}，用于半导体制造`
  };

  data.push(entry);
}

console.log(`Added ${newRoots.length} entries`);
console.log(`Total: ${data.length} entries`);
console.log(`Last: id=${data[data.length-1].id}, freq=${data[data.length-1].frequency}`);

fs.writeFileSync('../src/data/semiconductor.json', JSON.stringify(data, null, 2));
console.log('File saved!');
